Update Readme with pre-commit
openstack-k8s-operators/nova-operator pull request #101
Opened 2022-10-11 15:15 UTC by SeanMooney

- This change adds more detail on how to configure pre-commit
- This change adds a pre-commit badge to show branch status.

2022-10-11 15:34 UTC, bogdando commented
I have this failure (it could be my env specific problem though)
```
make-generate............................................................Failed
- hook id: make-generate
- exit code: 2

test -s /opt/go/src/github.com/openstack-k8s-operators/nova-operator/bin/controller-gen || GOBIN=/opt/go/src/github.com/openstack-k8s-operators/nova-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
/opt/go/src/github.com/openstack-k8s-operators/nova-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Error: err: exit status 1: stderr: go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
        Remove the -mod flag to use the default readonly value,
        or set GOWORK=off to disable workspace mode.
```

2022-10-12 08:04 UTC, gibizer requested changes

2022-10-12 08:04 UTC, gibizer commented on README.md
> +python3 -m TODO(user): An in-depth paragraph about your project and overview of useTODO(user): An in-depth paragraph about your project and overview of useTODO(user): An in-depth paragraph about your
the `python3 -m` and a bunch of existing `TODO`s are now intermingled here.

2022-10-12 08:04 UTC, gibizer commented on README.md
> +confrim golangci-lint is installed
confirm

2022-10-12 08:06 UTC, gibizer commented
> I have this failure (it could be my env specific problem though)
> 
> ```
> make-generate............................................................Failed
> - hook id: make-generate
> - exit code: 2
> 
> test -s /opt/go/src/github.com/openstack-k8s-operators/nova-operator/bin/controller-gen || GOBIN=/opt/go/src/github.com/openstack-k8s-operators/nova-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
> /opt/go/src/github.com/openstack-k8s-operators/nova-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
> Error: err: exit status 1: stderr: go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
>         Remove the -mod flag to use the default readonly value,
>         or set GOWORK=off to disable workspace mode.
> ```

what is your go version?

> $ go version
> go version go1.18.5 linux/amd64
>

2022-10-12 08:06 UTC, SeanMooney commented on README.md
> +python3 -m TODO(user): An in-depth paragraph about your project and overview of useTODO(user): An in-depth paragraph about your project and overview of useTODO(user): An in-depth paragraph about your
oh odd i wonder how that happened ill fix that

2022-10-12 08:44 UTC, gibizer approved these changes
/lgtm
We can troubleshoot @bogdando 's env issue separately.

2022-10-12 08:44 UTC, merged

2022-10-12 12:02 UTC, gibizer commented
> On my side, the problem was in `GOFLAGS=-mod=mod`. If I unset it, everything works

Thanks for stating the fix. I checked I have no GOFLAGS in my env.