extract reconciler base
openstack-k8s-operators/nova-operator pull request #103
Opened 2022-10-11 21:52 UTC by SeanMooney

- Factor out common reconsiler base
- Refactor reconciler setup
- [WIP] extract contoller creation to utils files

2022-10-12 08:24 UTC, gibizer commented on controllers/utils.go
> +		"nova": &NovaReconciler{
Why the different casing for nova? All the rest is CameCase and the original reconciler also used "Nova"

2022-10-12 08:26 UTC, gibizer commented on test/functional/suite_test.go
> +			Log:     ctrl.Log.WithName("controllers").WithName("NovaMetadata"),
This seems damaged during refactor. The NovaAPIReconciler now has a logger for NovaMetadata

2022-10-12 08:51 UTC, SeanMooney commented on controllers/utils.go
> +		"nova": &NovaReconciler{
oh i proably typed this instead of copy paste that is not intentional

2022-10-12 11:53 UTC, SeanMooney commented on main.go
> +	}
lost the comment but i confirmed that the behavior is to just generate the if block in the main.go as normal because i left the marker comment there.

if you remove the marker it will just omit the generated stub so it looks like we cannot break the code gen by refactoring like this. at least not in this case

2022-10-12 11:54 UTC, SeanMooney commented on test/functional/suite_test.go
> +	// controllers.SetupReconcilers(k8sManager, ctrl.Log.WithName("testSetup"))
this was a simple case of not passing the config generated by envtest.
so the tests were running against crc and failing as this test could not run against a real env.

i have corrected that in the latest version by passing the config

we can figure out what to do with the test later since that is unrelated to this change.

2022-10-12 12:05 UTC, SeanMooney commented
this is going to fail since i have not asress the golint comments
i rebased this on the pre-commit change but forgot to update my hooks locally i bet that is the issue

2022-10-12 12:11 UTC, gibizer commented on test/functional/suite_test.go
> -	// in the test env.
Please keep this or something similar. When we add a new external dependency to nova-operator like mariadb here https://github.com/openstack-k8s-operators/nova-operator/pull/87/files#diff-9e438edde3e826eec37a179369bdcf4a85e4e6822f83bb1cad33d29097f26781R118 then we need to add the schema here otherwise test will start failing without really pointing to the missing schema here.

2022-10-12 16:04 UTC, gibizer submitted a review, later dismissed
/lgtm

2022-10-13 07:57 UTC, gibizer requested changes
-1 due to lost RequeueTimeout config from NovaReconciler. 
The test configurability issue can be fixed in a followup

2022-10-13 07:57 UTC, gibizer commented on main.go
> -		RequeueTimeout: time.Duration(5) * time.Second,
This was lost during the rebase / refactoring.

2022-10-13 07:57 UTC, gibizer commented on test/functional/suite_test.go
> -		RequeueTimeoutSeconds: 1,
After the refactor this (and below) is set back to 5 seconds making the overall test execution slower (from 26 sec to 70 sec). I'm OK to merge this as is and I will propose a follow up that moves the RequeueTimeout to the ReconcileBase and also expose the RequeueTimeout configuration for the test env.

2022-10-13 09:22 UTC, gibizer commented on controllers/utils.go
> +			os.Exit(1)
This is still not good for testing perspective. In the test we should not exit, but raise a panic to trigger cleanup.

2022-10-13 09:32 UTC, gibizer commented on controllers/utils.go
> +			os.Exit(1)
I will fix this in a followup

2022-10-13 09:44 UTC, gibizer commented on main.go
> -		RequeueTimeout: time.Duration(5) * time.Second,
actually I'm fixing this as well in a follow up

2022-10-13 09:44 UTC, gibizer approved these changes
All my comment is being fixed in a follow up so this can be merged.

2022-10-13 09:55 UTC, merged