[WIP] add suppport for scheduler
openstack-k8s-operators/nova-operator pull request #173
Opened 2022-12-02 19:50 UTC by SeanMooney

2022-12-04 15:53 UTC, gibizer commented
I haven't looked at the actual code yet just tried to deploy it.

I needed a small change in the scheduler types to have a defaulted PasswordSelector:
```diff
diff --git a/api/v1beta1/novascheduler_types.go b/api/v1beta1/novascheduler_types.go
index 9e54477..d490f43 100644
--- a/api/v1beta1/novascheduler_types.go
+++ b/api/v1beta1/novascheduler_types.go
@@ -73,6 +73,7 @@ type NovaSchedulerSpec struct {
        Secret string `json:"secret"`
 
        // +kubebuilder:validation:Optional
+       // +kubebuilder:default={service: NovaPassword}
        // PasswordSelectors - Field names to identify the passwords from the
        // Secret
        PasswordSelectors PasswordSelector `json:"passwordSelectors,omitempty"`
```

And I used the following sample to deploy NovaScheduler:
```yaml
$ cat config/samples/nova_v1beta1_novascheduler.yaml 
apiVersion: nova.openstack.org/v1beta1
kind: NovaScheduler
metadata:
  name: novascheduler-sample
spec:
  secret: osp-secret
  apiDatabaseHostname: openstack
  apiMessageBusSecretName: rabbitmq-transport-url-nova-api-transport
  cell0DatabaseHostname: openstack
  containerImage: quay.io/tripleozedcentos9/openstack-nova-scheduler:current-tripleo
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
```
Deploy steps:
```bash
# in install_yamls repo
make openstack
make openstack_deploy
oc edit OpenstackControlPlane # set nova.enabled = false to prevent openstack-operator to change Nova CR
oc delete Nova/nova
oc edit deployment.apps/nova-operator-controller-manager # and set replicas to 0 to stop the deployed nova-controller
# go to the nova-operator repo
make manifests generate install
OPERATOR_TEMPLATES=./templates make run 
# then another terminal
oc apply -f nova_v1beta1_novascheduler.yaml
```

With this the scheduler controller picked up the NovaScheduler CR and run config gen, then started a pod. The pod fails with:
```
$ oc logs -f  pod/novascheduler-sample-0
INFO:__main__:Loading config file at /var/lib/openstack/config/nova-scheduler-config.json
INFO:__main__:Validating config file
INFO:__main__:Kolla config strategy set to: COPY_ALWAYS
INFO:__main__:Copying service configuration files
INFO:__main__:Deleting /etc/nova/nova.conf
INFO:__main__:Copying /var/lib/openstack/config/01-nova.conf to /etc/nova/nova.conf
INFO:__main__:Setting permission for /etc/nova/nova.conf
INFO:__main__:Writing out command to execute
ERROR:__main__:Unexpected error:
Traceback (most recent call last):
  File "/usr/local/bin/kolla_set_configs", line 423, in main
    execute_config_strategy(config)
  File "/usr/local/bin/kolla_set_configs", line 391, in execute_config_strategy
    handle_permissions(config)
  File "/usr/local/bin/kolla_set_configs", line 349, in handle_permissions
    gid = grp.getgrnam(desired_group).gr_gid
KeyError: "getgrnam(): name not found: 'apache'"
```

2022-12-04 15:55 UTC, gibizer commented on templates/novascheduler/config/nova-scheduler-config.json
> +            "owner": "nova:apache",
the pod probably fails on this as the apache group might be missing from the container.

2022-12-04 17:17 UTC, SeanMooney commented on templates/novascheduler/config/nova-scheduler-config.json
> +            "owner": "nova:apache",
its not needed this is left over form the API code that can be deleted

2022-12-06 10:16 UTC, gibizer commented
Scheduler pod logs looks OK and the scheduler can register itself to the DB:
```
2022-12-06 10:10:17.477 1 DEBUG nova.servicegroup.drivers.db [None req-76f848d5-d4c8-468e-afed-c3b10404340c - - - - - -] DB_Driver: join new ServiceGroup member novascheduler-sample-0 to the scheduler group, service = <Service: host=novascheduler-sample-0, binary=nova-scheduler, manager_class_name=nova.scheduler.manager.SchedulerManager> join /usr/lib/python3.9/site-packages/nova/servicegroup/drivers/db.py:44
```

```
$ openstack compute service list
+--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
| ID                                   | Binary         | Host                   | Zone     | Status  | State | Updated At                 |
+--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
| 23ad7714-f272-4bb4-b622-de47f35bd6dd | nova-conductor | nova-cell0-conductor-0 | internal | enabled | up    | 2022-12-06T10:12:19.000000 |
| dc1a3fd2-5e71-41cf-9c6d-ba92ba17f452 | nova-scheduler | novascheduler-sample-0 | internal | enabled | up    | 2022-12-06T10:12:22.000000 |
| 49f2d08b-208c-440c-93de-7fef3a779765 | nova-conductor | nova-cell1-conductor-0 | internal | enabled | up    | 2022-12-06T10:12:20.000000 |
+--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
```

For some reason the controller thinks that the deployment is not ready. This was the last reconciliation happened:
```
2022-12-06T11:10:06.770+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-06T11:10:06.773+0100	INFO	controllers.NovaScheduler	StatefulSet novascheduler-sample - updated
2022-12-06T11:10:06.773+0100	INFO	controllers.NovaScheduler	Deployment is not ready	{"Status": {"replicas":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
```

This is also reflected in the Conditions:
```yaml
  status:
    conditions:
    - lastTransitionTime: "2022-12-06T10:10:06Z"
      message: Setup started
      reason: Requested
      status: Unknown
      type: Ready
    - lastTransitionTime: "2022-12-06T10:10:06Z"
      message: Deployment in progress
      reason: Requested
      severity: Info
      status: "False"
      type: DeploymentReady
    - lastTransitionTime: "2022-12-06T10:10:06Z"
      message: Input data complete
      reason: Ready
      status: "True"
      type: InputReady
    - lastTransitionTime: "2022-12-06T10:10:06Z"
      message: Service config create completed
      reason: Ready
      status: "True"
      type: ServiceConfigReady
    hash:
      input: n85h5c8h5c5h9fh558h57fh67ch5c5h654hf8h567hd7h5f9h6ch655h8h66bh574hdfhddh95h698h589h6fhb8h67fhd7h5f8h585hbh5b7h7cq
```

2022-12-12 23:32 UTC, SeanMooney commented
> Scheduler pod logs looks OK and the scheduler can register itself to the DB:
> 
> ```
> 2022-12-06 10:10:17.477 1 DEBUG nova.servicegroup.drivers.db [None req-76f848d5-d4c8-468e-afed-c3b10404340c - - - - - -] DB_Driver: join new ServiceGroup member novascheduler-sample-0 to the scheduler group, service = <Service: host=novascheduler-sample-0, binary=nova-scheduler, manager_class_name=nova.scheduler.manager.SchedulerManager> join /usr/lib/python3.9/site-packages/nova/servicegroup/drivers/db.py:44
> ```
> 
> ```
> $ openstack compute service list
> +--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
> | ID                                   | Binary         | Host                   | Zone     | Status  | State | Updated At                 |
> +--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
> | 23ad7714-f272-4bb4-b622-de47f35bd6dd | nova-conductor | nova-cell0-conductor-0 | internal | enabled | up    | 2022-12-06T10:12:19.000000 |
> | dc1a3fd2-5e71-41cf-9c6d-ba92ba17f452 | nova-scheduler | novascheduler-sample-0 | internal | enabled | up    | 2022-12-06T10:12:22.000000 |
> | 49f2d08b-208c-440c-93de-7fef3a779765 | nova-conductor | nova-cell1-conductor-0 | internal | enabled | up    | 2022-12-06T10:12:20.000000 |
> +--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
> ```
> 
> For some reason the controller thinks that the deployment is not ready. This was the last reconciliation happened:
> 
> ```
> 2022-12-06T11:10:06.770+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
> 2022-12-06T11:10:06.773+0100	INFO	controllers.NovaScheduler	StatefulSet novascheduler-sample - updated
> 2022-12-06T11:10:06.773+0100	INFO	controllers.NovaScheduler	Deployment is not ready	{"Status": {"replicas":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
> ```
> 
> This is also reflected in the Conditions:
> 
> ```yaml
>   status:
>     conditions:
>     - lastTransitionTime: "2022-12-06T10:10:06Z"
>       message: Setup started
>       reason: Requested
>       status: Unknown
>       type: Ready
>     - lastTransitionTime: "2022-12-06T10:10:06Z"
>       message: Deployment in progress
>       reason: Requested
>       severity: Info
>       status: "False"
>       type: DeploymentReady
>     - lastTransitionTime: "2022-12-06T10:10:06Z"
>       message: Input data complete
>       reason: Ready
>       status: "True"
>       type: InputReady
>     - lastTransitionTime: "2022-12-06T10:10:06Z"
>       message: Service config create completed
>       reason: Ready
>       status: "True"
>       type: ServiceConfigReady
>     hash:
>       input: n85h5c8h5c5h9fh558h57fh67ch5c5h654hf8h567hd7h5f9h6ch655h8h66bh574hdfhddh95h698h589h6fhb8h67fhd7h5f8h585hbh5b7h7cq
> ```

this i think was caused because i did not set the owner refernce for the stateful set.
i think thats what fixed it anyway but it should be adressed in the latest version

2022-12-13 09:18 UTC, gibizer requested changes
The scheduler seems to behave correctly now. I was able to toggle the debug config as well and the pod was restarted with the new config. Good progress.

I have left some code comment inline but I think this service is ready to be integrated to the nova controller.

```
2022-12-13T10:13:13.527+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:13.527+0100	INFO	controllers.NovaScheduler	Added finalizer to ourselves	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:13.532+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:13.535+0100	INFO	controllers.NovaScheduler	ConfigMap novascheduler-sample-config-data successfully reconciled - operation: created
2022-12-13T10:13:13.538+0100	INFO	controllers.NovaScheduler	StatefulSet novascheduler-sample - created
2022-12-13T10:13:13.538+0100	INFO	controllers.NovaScheduler	Deployment in progress	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:13.543+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:13.546+0100	INFO	controllers.NovaScheduler	StatefulSet novascheduler-sample - updated
2022-12-13T10:13:13.546+0100	INFO	controllers.NovaScheduler	Deployment is not ready	{"Status": {"replicas":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:13.549+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:13.552+0100	INFO	controllers.NovaScheduler	StatefulSet novascheduler-sample - updated
2022-12-13T10:13:13.552+0100	INFO	controllers.NovaScheduler	Deployment is not ready	{"Status": {"observedGeneration":1,"replicas":1,"currentReplicas":1,"updatedReplicas":1,"currentRevision":"novascheduler-sample-5dbc65585c","updateRevision":"novascheduler-sample-5dbc65585c","collisionCount":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:24.880+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:24.884+0100	INFO	controllers.NovaScheduler	StatefulSet novascheduler-sample - updated
2022-12-13T10:13:24.884+0100	INFO	controllers.NovaScheduler	Deployment is ready	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:24.886+0100	INFO	controllers.NovaScheduler	Reconciling	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
2022-12-13T10:13:24.889+0100	INFO	controllers.NovaScheduler	StatefulSet novascheduler-sample - updated
2022-12-13T10:13:24.889+0100	INFO	controllers.NovaScheduler	Deployment is ready	{"ObjectType": "*v1beta1.NovaScheduler", "ObjectNamespace": "openstack", "ObjectName": "novascheduler-sample"}
```

```
gibi@bedrock:/tmp/stack/nova (.venv)                                                                                                                                                                [000] [10:13:13]
$ openstack compute service list
+--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
| ID                                   | Binary         | Host                   | Zone     | Status  | State | Updated At                 |
+--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
| ad705222-d655-403c-ba44-57f33f530655 | nova-conductor | nova-cell1-conductor-0 | internal | enabled | up    | 2022-12-13T09:14:28.000000 |
| bb0c96dc-8310-4b3c-88ae-64c5d4316cf2 | nova-conductor | nova-cell0-conductor-0 | internal | enabled | up    | 2022-12-13T09:14:23.000000 |
| ba757a5a-cc75-4d58-8ee8-2a7fc0ec39e5 | nova-scheduler | novascheduler-sample-0 | internal | enabled | up    | 2022-12-13T09:14:28.000000 |
+--------------------------------------+----------------+------------------------+----------+---------+-------+----------------------------+
```

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-12-13T09:13:24Z"
    message: Setup complete
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-12-13T09:13:24Z"
    message: Deployment completed
    reason: Ready
    status: "True"
    type: DeploymentReady
  - lastTransitionTime: "2022-12-13T09:13:13Z"
    message: Input data complete
    reason: Ready
    status: "True"
    type: InputReady
  - lastTransitionTime: "2022-12-13T09:13:13Z"
    message: Service config create completed
    reason: Ready
    status: "True"
    type: ServiceConfigReady
```

2022-12-13 10:50 UTC, SeanMooney commented on .pre-commit-config.yaml
> -   - 'go-lint'
its deprecated and has been for 2 years and when i tried to install it 
following https://github.com/golang/lint#installation it did not seam to provide the binary anymore so i removed it.

2022-12-13 10:54 UTC, SeanMooney commented on controllers/novascheduler_controller.go
> +	}
yes you are right the schduler does not own any resouces other that need this ill drop this.

2022-12-13 10:57 UTC, SeanMooney commented on controllers/novascheduler_controller.go
> +		Owns(&v1.StatefulSet{}).
hehe yep just realised that above although i still need to convert this over to secrets too. for now ill add configmap and then ill convert it over in a followup.

2022-12-13 11:00 UTC, SeanMooney commented on main.go
> +	flag.StringVar(&probeAddr, "health-probe-bind-address", ":24601", "The address the probe endpoint binds to.")
yep i do i could technially pass --metrics-bind-address but i just chnaged them to a port that was much less likely to exist.

2022-12-13 11:01 UTC, SeanMooney commented on templates/novascheduler/config/nova-scheduler-config.json
> +            "source": "/var/lib/openstack/config/nova-blank.conf",
we dont i just wanted to delete /etc/nova/nova.conf so that people would not get confused if they look in the container but i can drop this if you like.

2022-12-13 11:02 UTC, SeanMooney commented
ill adress teh comments which all more or less look correct to me then im going to start on evntest and the nova contorller as addtional commits.

2022-12-13 11:17 UTC, SeanMooney commented on pkg/novascheduler/deployment.go
> +	startupProbe := &corev1.Probe{
thats fair. i guess eventually we will want this when we have the preprocess healthchecks in nova but your right we dont need this currently. i kind of like haveing this be consitnet so ill leave this for now but if you want me to remove it i can

2022-12-13 11:34 UTC, gibizer commented on .pre-commit-config.yaml
> -   - 'go-lint'
This still runs in prow and github action so we can rely on those job to catch violation there. We just won't catch it during the local pre-commit run

2022-12-13 11:40 UTC, gibizer commented on controllers/common.go
> +		"nova-blank.conf": "/nova-blank.conf",
Got it thanks

2022-12-13 11:40 UTC, gibizer commented on main.go
> +	flag.StringVar(&probeAddr, "health-probe-bind-address", ":24601", "The address the probe endpoint binds to.")
ack

2022-12-13 11:40 UTC, gibizer commented on pkg/novascheduler/deployment.go
> +	startupProbe := &corev1.Probe{
you can leave it as is.

2022-12-13 14:42 UTC, SeanMooney commented on .pre-commit-config.yaml
> -   - 'go-lint'
i can see if i can get it running i have it working on other dev envs but didn't really want to debug it until i got this working end to end.

2022-12-14 16:42 UTC, gibizer commented
The Optional NovaSchedulerTemplate only defaults properly to replicas:1 if we define something as a default in the NovaSpec similarly how it was done for the NovaAPITemplate in:
https://github.com/openstack-k8s-operators/nova-operator/blob/765b05f36b101a29743d2724fb90dbedc4a8629f/api/v1beta1/nova_types.go#L87-L94

I suggest to just default `{replicas:1}` for both as then we don't have re-add the container image which is a lot longer and also different per service.

2022-12-14 17:09 UTC, gibizer requested changes
The code work in my test env (except the defaulting issue I noted above). I have some comments inline. Also I haven't reviewed the test code yet.

2022-12-14 17:18 UTC, gibizer submitted a review, later dismissed
couple more copy paste issues

2022-12-14 17:18 UTC, gibizer commented on controllers/novascheduler_controller.go
> +		l.Error(err, "Failed to read the NovaAPI instance.")
copy paste

2022-12-14 17:18 UTC, gibizer commented on controllers/novascheduler_controller.go
> +	// Fetch the NovaAPI instance that needs to be reconciled
copy paste

2022-12-14 17:18 UTC, gibizer commented on pkg/novascheduler/deployment.go
> +// StatefulSet - returns the StatefulSet definition for the nova-api service
copy paste

2022-12-14 18:18 UTC, SeanMooney commented on api/v1beta1/novascheduler_types.go
> +	// APIDatabaseUser - username to use when accessing the cell0 DB
actully this was intenitally

its the user for the API database

i did not want this to be called scheduled Database


did you mean this should not say "accessing the cell0 DB"

if so then yes ill fix that here and in the place i copied this from :)

2022-12-14 18:19 UTC, SeanMooney commented on controllers/nova_controller.go
> +			h, fmt.Sprintf("NovaAPI %s.", string(op)), instance,
ack ya thats wrong.

2022-12-14 18:19 UTC, SeanMooney commented on api/v1beta1/novascheduler_types.go
> +	// APIDatabaseHostname - hostname to use when accessing the cell0 DB
same as above the parmter name is correct but the comment is wrong

2022-12-14 18:20 UTC, SeanMooney commented on controllers/nova_controller.go
> +	instance.Status.APIServiceReadyCount = scheduler.Status.ReadyCount
damb i thought i fixed that thanks

2022-12-14 18:21 UTC, SeanMooney commented on controllers/novascheduler_controller.go
> +// +kubebuilder:rbac:groups=keystone.openstack.org,resources=keystoneendpoints,verbs=get;list;watch;create;update;patch;delete;
i think your right we do not need too interact with the keystone endpoint cr we just need the keystone URL for the config so ill fix this thanks

2022-12-14 18:23 UTC, SeanMooney commented
cool the copy paste issues shoudl be quick to resolve.
ill fix those and resubmit by the end of the week.

i will start on the envtest commit on Friday. ill see if i can get it ready by the time i go on PTO but if not ill comeback to it in the new year.

2023-01-11 01:08 UTC, SeanMooney commented
this should now be ready.

i fitured out how to get golint to install again 

there readme say to do 

go get -u golang.org/x/lint/golint

but now its just 

go install golang.org/x/lint/golint

so i updated the series to not remove it.

2023-01-12 14:02 UTC, gibizer submitted a review, later dismissed
There is a couple of copy paste mistake to fix and I think this is still an issue from the past:

The Optional NovaSchedulerTemplate only defaults properly to replicas:1 if we define something as a default in the NovaSpec similarly how it was done for the NovaAPITemplate in:
https://github.com/openstack-k8s-operators/nova-operator/blob/765b05f36b101a29743d2724fb90dbedc4a8629f/api/v1beta1/nova_types.go#L87-L94

I suggest to just default `{replicas:1}` for both as then we don't have re-add the container image which is a lot longer and also different per service.

2023-01-12 17:35 UTC, gibizer commented
I've built nova-operator from this PR then built an openstack-operator that used this nova-operator. Then tested it with install_yamls. It seems everything OK. But until the defaulting of `SchedulerServiceTemplate` is fixed (see above) the OpenStackControlPlane CR will create a scheduler with 0 replicas. (Manually editing the CR resulted in a proper nova-scheduler pod)

You can replicate my test with
`OPENSTACK_IMG=quay.io/gibi/openstack-operator-index:v0.0.16 make openstack`

2023-01-12 20:22 UTC, SeanMooney reviewed
nits adressed ill look at the other top level comments shortly

2023-01-12 20:22 UTC, SeanMooney commented on controllers/novascheduler_controller.go
> +		}
done

2023-01-12 20:22 UTC, SeanMooney commented on controllers/nova_controller.go
> +			h, fmt.Sprintf("NovaAPI %s.", string(op)), instance,
im going to fix this now but also we need to remove this form of logging later too right

i don't know what that should lookliek off the top of my head so I'm not going to change the logging over in this pr but ill sync with you on this and address it in a follow up.

2023-01-12 20:22 UTC, SeanMooney commented on controllers/nova_controller.go
> +	instance.Status.APIServiceReadyCount = scheduler.Status.ReadyCount
done

2023-01-12 20:22 UTC, SeanMooney commented on test/functional/nova_scheduler_test.go
> +			// NOTE(gibi): NovaAPI has no external dependency right now to
done

2023-01-12 21:03 UTC, SeanMooney commented
ok https://github.com/openstack-k8s-operators/nova-operator/pull/211/files merged while i was working on this so i had to rebase again to pick up the test changes.

the latest version should not have address all issues and work with master

2023-01-13 16:39 UTC, gibizer approved these changes
/lgtm
did a new build and deployed this with success.

`OPENSTACK_IMG=quay.io/gibi/openstack-operator-index:v0.0.18 make openstack`

2023-01-13 16:50 UTC, merged