Add top level NodeSelector and wire into CRs
openstack-k8s-operators/nova-operator pull request #176
Opened 2022-12-05 22:25 UTC by dprince

We need the ability to set this at the top level and have it trickle down to each service as a default.

2022-12-06 20:41 UTC, gibizer commented
@dprince don't worry about the functional prow job. It is non voting yet. as I'm still trying to make the envtest work in the CI container: #175. The Same test still runs as github action so we are covered.

2022-12-06 20:51 UTC, gibizer requested changes
I agree with the general direction to provide a global NodeSelector in Nova CR to allow the user to specify the node constraint for all nova services in a single place, while we keep the per service overwriteabilty of it via the service templates.

2022-12-06 20:51 UTC, gibizer commented on api/v1beta1/nova_types.go
> +	// NodeSelector to target subset of worker nodes running this service
We discussed on slack that we need to document the behavior of this top level field compared to the ones in the service templates. Right now I don't know about a better place to document it than here as this is our API documentation right now.

2022-12-06 20:51 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	// NodeSelector to target subset of worker nodes running this service
Here we need documentation too.

2022-12-06 20:51 UTC, gibizer commented on controllers/nova_controller.go
> +		api.Spec.NodeSelector = instance.Spec.NodeSelector
As we discussed on slack we should only overwrite the service specific NodeSelector if it is unset, I.e.: it has a value of map[string]string{}

2022-12-06 20:51 UTC, gibizer commented on controllers/nova_controller.go
> +		api.Spec.NodeSelector = instance.Spec.NodeSelector
Also you probably want to do propagation of the global NodeSelector from Nova CR to NovaCell CR and from NovaCell to NovaConductor (and eventually we need to do that for the rest of the Nova services when we implement them)

2022-12-08 09:02 UTC, gibizer commented
/test functional

> @dprince don't worry about the functional prow job. It is non voting yet. as I'm still trying to make the envtest work in the CI container: #175. The Same test still runs as github action so we are covered.

Job is fixed now.

2022-12-09 16:18 UTC, dprince commented on controllers/nova_controller.go
> +		api.Spec.NodeSelector = instance.Spec.NodeSelector
I updated the logic to account for the conditional logic

2022-12-12 08:27 UTC, gibizer commented
I've tried the PR and I see the following behavior:
- Both setting and re-setting `Nova.Spec.NodeSelector` works if the label there is actually selecting nodes that can host the pods. E.g. `kubernetes.io/os: linux` `NodeSelector` works in CRC.
- Setting the `Nova.Spec.NodeSelector` to a label that does not match any worker, e.g. `foo: bar` pushes the pods into `Pending` state. This is expected as no nodes match. But then re-setting the `Nova.Spec.NodeSelector` only propagates the empty `NodeSelector` to the `StatefulSet` but then k8s does not kill / re-schedule the `Pending` pod so the system get stuck. I can get the system unstuck by setting `replicas` of the services to `0` first then setting them back to `1`.

As the `StatefulSet` get configured properly in every case I don't think this is a nova-operator problem. More like a non-intuitive (for me at least) behavior from k8s. I did not find confirmation of this with a quick google search. Did anybody see such behavior before? Is it the expected k8s behavior?

2022-12-12 14:59 UTC, gibizer commented
With the help of @SeanMooney I see a possible way forward.

There is a [KEP](https://github.com/kubernetes/enhancements/pull/3562) open that describes the problem we see with the Pending Pods. There is a workaround described there to set the `StatefulSet.Spec.PodManagementPolicy` to `Parallel` instead of the default `OrderedReady`. 

To be able to do that we need:
1. a lib-common change to allow setting `StatefulSet.Spec.PodManagementPolicy` https://github.com/openstack-k8s-operators/lib-common/pull/116
2. set the `StatefulSet.Spec.PodManagementPolicy` in https://github.com/openstack-k8s-operators/nova-operator/blob/f9e6b9363961ce1e2595b16308cbcc8c4b999597/pkg/novaapi/deployment.go#L112-L114 and in https://github.com/openstack-k8s-operators/nova-operator/blob/f9e6b9363961ce1e2595b16308cbcc8c4b999597/pkg/novaconductor/deployment.go#L128-L130 to `Parallel`

This will result in the following behavior based on my tests:
- scaling from 1 to 3 replicas happen in parallel, so 2 new pods are created simultaneously. I think this is expected due to the new policy
- setting global NodeSelector to match no nodes will push the *last* Pod in the StatefulSet to Pending. I would expected to have all replicas to go to Pending in parallel due to the new policy. But I guess this is OK as is and actually closer what we want from the StatefulSet
- re-setting the NodeSelector to empty kills the Pending Pod and start a new one and that reaches Running state properly. This is what we want.
- when NodeSelector is set in a way that is selects a node then Pods in the StatefulSet is restared one by one, not in parallel, to pick up the new NodeSelector.

2022-12-12 15:00 UTC, gibizer requested changes
We need to set PodManagementPolicy to Parallel.

2022-12-12 15:31 UTC, gibizer commented
I needed to push a rebase as well to pick up a fix for a breaking change from master.

2022-12-18 14:31 UTC, gibizer commented
The lib-common dependency landed. But we need #201 to merge first to be able to bring in that lib-common dep update.

2023-01-06 17:31 UTC, gibizer commented
All dependency merged. I would like to get some review from @SeanMooney before we land this.

2023-03-14 11:58 UTC, SeanMooney commented
sorry i missed this ping when i got back form pto

since this was written we have merge the schduler and we are close to having the metadata api

@dprince if you would like one of us can pick this up and add in the missing servcie and do the rebase. 

im not sure the current semantics are correct. i only looked breifly, while propagation is proably ok if you define a node selector on the api template or conductor that need to take precidnece over the one on the nova CR.

i didnt see any test coverage to assert that and im not sure the current code does that so i would like to see that coverd too before we merge this.

we might be able to squeeze this into q1 but we will see.

2023-04-06 09:31 UTC, gibizer commented
> since this was written we have merge the schduler and we are close to having the metadata api
> 

I see the logic applied to scheduler and metadata in the recent version of the PR.

> im not sure the current semantics are correct. i only looked breifly, while propagation is proably ok if you define a node selector on the api template or conductor that need to take precidnece over the one on the nova CR.

As far as I see we have the logic to propagate the template value to the spec value by default, but if it results in an empty selector and then we use the Nova CR level value. I think this is correct.

> 
> i didnt see any test coverage to assert that and im not sure the current code does that so i would like to see that coverd too before we merge this.

We have the test coverage in two cases:
* Nova reconfiguration when global NodeSelector is set is propagated to the pods
* Nova reconfiguration when global NodeSelector is set does not override non empty NodeSelector defined in the service template

2023-04-06 09:43 UTC, gibizer commented
> > i didnt see any test coverage to assert that and im not sure the current code does that so i would like to see that coverd too before we merge this.
> 
> We have the test coverage in two cases:
> 
> * Nova reconfiguration when global NodeSelector is set is propagated to the pods
> * Nova reconfiguration when global NodeSelector is set does not override non empty NodeSelector defined in the service template

One amendment to this. We use the NovaAPI service CR in the test we probably want to extend the test to show that the same thing works for NovaScheduler, NovaCell, NovaMetadata CRs as well.

2023-04-06 12:01 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +		Entry("is propagated to the nova api pods", "-api"),
so this would be something like:
```golang
Entry("is propagated to the nova api pods", types.NamespacedName{Namespace: namespace, Name:      novaName.Name + "-api",}),
// [...snip...]
Entry("is propagated to cell0 conductor", NewCell(novaName, "cell0").ConductorStatefulSetName),
// [...snip...]
```

The name handling is being simplified in the refactor @bogdando trying to rebase in #323

2023-04-06 12:04 UTC, bogdando commented on test/functional/nova_reconfiguration_test.go
> +				apiDeployment := th.GetStatefulSet(novaDeploymentName)
just to note that this sort of naming things is being rebased in https://github.com/openstack-k8s-operators/nova-operator/pull/323

2023-04-06 15:26 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				apiDeployment := th.GetStatefulSet(novaDeploymentName)
done and ack!

2023-04-06 15:27 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				}
done!

2023-04-06 15:27 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +		Entry("is propagated to the nova api pods", "-api"),
done, thanks!

2023-04-11 10:05 UTC, gibizer requested changes
I noticed one implementation flaw. And I have some test suggestions inline.

2023-04-11 10:05 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +				}
We don't need to test again that propagation without the service level selector works as that is tested in previous test case. So we can also check instead that the conductor in the cells can have its own NodeSelector that is not overridden by the top level selector.

2023-04-11 10:05 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +		DescribeTable("is propagated to the pods", func(serviceNameFunc func() types.NamespacedName) {
to get an OKish test case naming you need to change the string here to: "it is propagated to the"

2023-04-12 14:28 UTC, mrKisaoLamb commented on api/v1beta1/novacell_types.go
> +	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
Done I added NodeSelector to NovaCellTemplate and set it in nova_controller into NovaCellSpec.NodeSelector

2023-04-12 14:28 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +			// Set NovaAPI specific NodeSelector first
done

2023-04-12 14:28 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				// NovaAPI's deployment keeps it own selector
done

2023-04-12 14:29 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +		DescribeTable("is propagated to the pods", func(serviceNameFunc func() types.NamespacedName) {
done

2023-04-12 14:29 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +			Entry("is propagated to the nova api pods",
done

2023-04-13 08:07 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +				apiDeployment := th.GetStatefulSet(novaDeploymentName)
sorry I missed this in the previous round. I would rename this to serviceDeploymentName and serviceDeployment As this is not specific to API any more.

2023-04-14 09:21 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				}
thanks done!

2023-04-14 09:21 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				apiDeployment := th.GetStatefulSet(novaDeploymentName)
Thankd, done

2023-04-14 10:07 UTC, gibizer requested changes

2023-04-14 10:07 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			conductor := GetNovaConductor(cell0.ConductorStatefulSetName)
I think this set of changes are wrong. GetNovaConductor will read a novav1.NovaConductor instances from the API so we should pass the name of the NovaConductor CR to it not a the name of the StatefulSet resource. (It happens that the naming scheme uses the same name for both, but from typing perspective we have mismatch here)

2023-04-14 10:07 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +				g.Expect(metadataDeployment.Spec.Template.Spec.NodeSelector).To(Equal(serviceSelector))
you can assert as ell that GetStatefulSet(cell[0, 1, 2].ConductorStatefulSetName).Spec.Template.Spec.NodeSelector is set to the serviceSelector.

2023-04-14 10:07 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +				// But cell conductors get the global one
This needs to be updated as now you assert that the conductors also kept it service level selector instead of the global one.

2023-04-14 11:06 UTC, mrKisaoLamb commented on test/functional/nova_multicell_test.go
> +			conductor := GetNovaConductor(cell0.ConductorStatefulSetName)
Done

2023-04-14 11:06 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				g.Expect(metadataDeployment.Spec.Template.Spec.NodeSelector).To(Equal(serviceSelector))
Done

2023-04-14 11:06 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				// But cell conductors get the global one
Done

2023-04-17 07:55 UTC, gibizer requested changes

2023-04-17 07:55 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +				cell1Names.ConductorStatefulSetName,
Hups this still needs to be reverted.

2023-04-17 08:14 UTC, mrKisaoLamb commented on test/functional/nova_reconfiguration_test.go
> +				cell1Names.ConductorStatefulSetName,
Done. Sorry I missed this

2023-04-17 08:27 UTC, gibizer approved these changes
Thanks

2023-04-17 08:31 UTC, merged