Use switch when checking status enum values
openstack-k8s-operators/nova-operator pull request #204
Opened 2022-12-18 15:57 UTC by gibizer

2023-01-02 11:09 UTC, bogdando requested changes

2023-01-02 11:09 UTC, bogdando commented on controllers/nova_controller.go
> +		switch status {
this eats the err != nil case handling

2023-01-02 11:09 UTC, bogdando commented on controllers/nova_controller.go
> +		switch status {
ditto

2023-01-06 10:29 UTC, gibizer commented on controllers/nova_controller.go
> +		switch status {
`status == DBFailed` and `err != nil` are equivalent based on https://github.com/openstack-k8s-operators/nova-operator/blob/72619e749746e66f54d368615f34fa1bc0e5e2ae/controllers/nova_controller.go#L497-L499

2023-01-06 10:29 UTC, gibizer commented on controllers/nova_controller.go
> +		switch status {
ditto :)

2023-01-09 14:13 UTC, bogdando approved these changes

2023-01-09 14:27 UTC, merged