Switch to test helper resources operations
openstack-k8s-operators/nova-operator pull request #211
Opened 2023-01-05 16:20 UTC by bogdando

Use conditions, statefulsets, namespaces, jobs basic test ops
from test helper common lib

Consume ConditionGetterFunc from common lib.

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/131

2023-01-05 16:21 UTC, bogdando commented on go.mod
> +replace github.com/openstack-k8s-operators/lib-common/modules/test => /opt/go/src/github.com/openstack-k8s-operators/lib-common/modules/test
DNM, those are to go once the dependency merged

2023-01-05 16:27 UTC, bogdando commented on test/functional/suite_test.go
> +	logger = ctrl.Log.WithName("---Test---")
this is how operators can override the testhelper logger instance

2023-01-05 16:50 UTC, bogdando commented
/test all

2023-01-06 17:11 UTC, gibizer requested changes
it needs a rebase but otherwise looks good.

2023-01-09 15:11 UTC, bogdando commented on controllers/nova_controller.go
>  	"k8s.io/apimachinery/pkg/types"
go mod tidy in the rebased branch doesn't make this to vanish

2023-01-09 15:16 UTC, bogdando commented
> it needs a rebase but otherwise looks good.

done

2023-01-12 17:37 UTC, gibizer approved these changes
looks good. thanks!

2023-01-12 17:42 UTC, merged