Generate manifests before test run
openstack-k8s-operators/nova-operator pull request #227
Opened 2023-01-13 09:53 UTC by gibizer

The envtest uses our CRD definitions during test so we need to run `make manifests` and `make generate` before the test run to always test with an up to date CRD yaml and golang definition.

The `make test` target generats manifests today but the `make gotest` target doesn't. The latter is used in the prow CI job[1].

Also this patch switches the github action based test run to use `make gotest` instead of indirectly calling `go test`.

[1] https://github.com/openshift/release/blob/fe0b5ddd5c96f053a654883ae33ec05933ad6c5c/ci-operator/config/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master.yaml#L31

2023-01-13 14:28 UTC, bogdando requested changes

2023-01-13 14:28 UTC, bogdando commented on .github/workflows/golangci-lint.yaml
> +        run: make gotest
this prolly is missing GOWORK=off make gotest?

2023-01-13 15:09 UTC, gibizer commented on .github/workflows/golangci-lint.yaml
> +        run: make gotest
I'd like to keep GOWORK on if possible. We will see...

2023-01-13 15:11 UTC, gibizer commented
/test functional
the modification on prow side landed for this to work

2023-01-13 15:22 UTC, gibizer commented on .github/workflows/golangci-lint.yaml
> +        run: make gotest
and also this workflow goes away in favor of the prow's functional job

2023-01-16 16:45 UTC, gibizer commented
OK I had two tweak the test target but now `make gotest` is an alias of `make test`

2023-01-16 18:40 UTC, SeanMooney approved these changes

2023-01-16 18:40 UTC, SeanMooney commented on Makefile
> +gotest: test
ok so this basicaly just make it an alias as you mentioned in the PR message

i have tested this locally and both seam to work fine so if the ci is happy then
we can proceed with this

2023-01-16 19:07 UTC, merged