Multus envtest
openstack-k8s-operators/nova-operator pull request #265
Opened 2023-02-17 11:12 UTC by gibizer

Depends-on: https://github.com/openstack-k8s-operators/nova-operator/pull/248

2023-02-20 13:15 UTC, gibizer commented
/test all

2023-02-22 19:30 UTC, SeanMooney requested changes
so i think the evtests for the indivigual CRs make sense but i dont think i like the approch for the main nova cr as it should be testing without network attachments by default and then we should have addtional test with network attachments

2023-02-22 19:30 UTC, SeanMooney commented on test/functional/novaapi_controller_test.go
> +				HaveKeyWithValue("metallb.universe.tf/allow-shared-ip", "osp-internalapi"))
apparently this is just an arbiatry key
https://metallb.universe.tf/usage/#ip-address-sharing

i was expecting this to be a bool

2023-02-23 09:05 UTC, gibizer commented
> so i think the evtests for the indivigual CRs make sense but i dont think i like the approch for the main nova cr as it should be testing without network attachments by default and then we should have addtional test with network attachments

I will create separate network test for the Nova CR too. Be prepared for the inevitable duplication it causes.

2023-02-23 09:28 UTC, gibizer commented on test/functional/base_test.go
> +		Spec: networkv1.NetworkAttachmentDefinitionSpec{
It is a very simple CRD with a single config string field. So I went with the easier to type way. I don't see any dangerous defaulting here. Also I don't want to test the NetworkAttachmentDefinition creation logic here. I just need the CR to exists. So I will keep the simpler approach here.

2023-02-23 10:56 UTC, gibizer commented on test/functional/nova_scheduler_test.go
> +				map[string][]string{namespace + "/internalapi": {"IP for internalapi"}},
Done in the next revision

2023-02-23 10:56 UTC, gibizer commented on test/functional/base_test.go
> +	var externalEndpoints []interface{}
Done in the new revision

2023-02-23 11:18 UTC, SeanMooney commented on test/functional/novaapi_controller_test.go
> +			Expect(endpoints).To(HaveKeyWithValue("internal", "http://nova-internal."+namespace+".svc:8774/v2.1"))
ya so it does presently as we are only loadbalancing. we were previously dependingon the route to do the port translation.

I'm wondering should we change the container to run on port 80 but that would prevent the shared IP case.

i guess this is just a wrinkel we will have if you use this approach.

the intent of the original design (without network attachments) was to run all OpenStack services such that they would be exposed on 80/443 so that you did not have to punch a bunch of whole in your firewall and could server everything on the common webports.

i see with the multis approach that is going to be something we give up unless we also have an option to expose the multis VIP via a route/ingrees later too.

2023-02-23 12:11 UTC, SeanMooney reviewed
ok i think im happy with this

2023-02-23 12:11 UTC, SeanMooney commented on test/functional/novaapi_controller_test.go
> +				HaveKeyWithValue("metallb.universe.tf/allow-shared-ip", "osp-internalapi"))
this is documented in the comment on the metallb config object

so yes if you set the bool sharedIP to true it default the allo-shared-ip annotation to the same value as the address pool

2023-02-23 12:11 UTC, SeanMooney reviewed
ok i think im happy with this

2023-02-23 12:52 UTC, SeanMooney approved these changes

2023-02-23 14:23 UTC, gibizer commented
/test precommit-check
job config changed to limit memory usage

2023-02-23 14:46 UTC, merged