Run pre-commit with make
openstack-k8s-operators/nova-operator pull request #269
Opened 2023-02-22 10:20 UTC by amolkahat

Updating pre-commit hook with make. pre-commit-golang repo is no longer maintained[1]. Instead of using
unmaintained repo we can use make to run pre-commit.

[1] https://github.com/dnephin/pre-commit-golang/issues/98

2023-02-22 10:39 UTC, gibizer requested changes

2023-02-22 10:39 UTC, gibizer commented on .pre-commit-config.yaml
> -- repo: https://github.com/dnephin/pre-commit-golang
OK this is sunset so we probably don't want to depend on it. There are viable alternatives if we want e.g.: https://github.com/TekWizely/pre-commit-golang

2023-02-22 10:39 UTC, gibizer commented on Makefile
> +	go mod tidy
This will not tidy both go.mod files our repo has.

2023-02-22 10:39 UTC, gibizer commented on Makefile
> +	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
* how this makes sure that the golangci-lint binary actually get installed to $(LOCALBIN) used below?
* I don't like the idea that this downloads and installs the binary at every run

2023-02-22 11:39 UTC, amolkahat commented on .pre-commit-config.yaml
> -- repo: https://github.com/dnephin/pre-commit-golang
Idea is just use whatever we have there already.. so using pre-commit we can run make commands.

2023-02-22 11:39 UTC, amolkahat commented on Makefile
> +	go mod tidy
Can you suggest something here.. what need to use? I'm open for suggestions.

2023-02-22 11:39 UTC, amolkahat commented on Makefile
> +	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
* Script `install.sh` install it in the local directory `./bin/`[1].
* Ok. I'll add some checks for it.
 
[1] https://golangci-lint.run/usage/install/

2023-02-22 11:49 UTC, gibizer commented on Makefile
> +	go mod tidy
what I would do is along the line:
```make
tidy:
    cd ./api
    go mod tidy
    cd ../
    go mod tidy
```

2023-02-22 11:50 UTC, gibizer commented on Makefile
> +	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
> * Script `install.sh` install it in the local directory `./bin/`[1].

please add note about it as a comment

> 
>     * Ok. I'll add some checks for it.
> 
> 
> [1] https://golangci-lint.run/usage/install/

2023-02-22 12:07 UTC, amolkahat commented on Makefile
> +	go mod tidy
This also failed in CI
``` 
go mod tidy
go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
make: *** [Makefile:126: tidy] Error 1
```

2023-02-22 12:31 UTC, gibizer commented on Makefile
> +	go mod tidy
It means the image the job uses don't have go 1.19 installed.

2023-02-22 14:23 UTC, amolkahat commented on Makefile
> +	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
Done.

2023-02-22 14:24 UTC, amolkahat commented on Makefile
> +	go mod tidy
Updated with your comments. Resolving discussion.

2023-02-22 15:09 UTC, SeanMooney commented on Makefile
> +	go mod tidy
i dont think this does what we want it to

you should probably use pushd and popd or similar
i would expect this to do two execution fo go mod tidy in the API dir

2023-02-22 15:10 UTC, SeanMooney commented on Makefile
> +	go mod tidy
that or revers the order
do it for the top level go mod file then the api

2023-02-23 08:30 UTC, amolkahat commented on Makefile
> +	go mod tidy
Done.

2023-02-23 13:22 UTC, SeanMooney commented on .pre-commit-config.yaml
> +      pass_filenames: false
passing false actully feel like a regression here.

we really only want it to check the files you are modifying

2023-02-23 13:23 UTC, SeanMooney commented on .pre-commit-config.yaml
> +      pass_filenames: false
actully i guess it dose not use it currently 
anyway 

https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml

2023-02-23 13:26 UTC, SeanMooney commented on Makefile
> +	$(LOCALBIN)/golangci-lint run --fix
we need to include this change

https://github.com/openshift/release/pull/36636/files

    # see tradeoff between speed and memory usage at https://golangci-lint.run/usage/performance/
    export GOGC=10

2023-02-23 13:27 UTC, SeanMooney commented on .pre-commit-config.yaml
> +      entry: bashate --error . --ignore=E006,E040,E011,E020,E012
we can fix it later but i would prefer to have a comment explaining what each of the ignored errors are.

2023-02-23 13:29 UTC, gibizer commented on Makefile
> +	$(LOCALBIN)/golangci-lint run --fix
I don't want to include it here. This target is run locally and locally I have enough ram not to get OOM killed. So I would like to keep the speed and only limit the memory usage when it runs from the prow job where memory is limited

2023-02-27 09:23 UTC, amolkahat commented on .pre-commit-config.yaml
> +      entry: bashate --error . --ignore=E006,E040,E011,E020,E012
Updated.

2023-02-28 08:57 UTC, amolkahat commented
/test precommit-check

2023-03-02 06:46 UTC, amolkahat commented
/test precommit-check

2023-03-10 14:10 UTC, gibizer approved these changes

2023-03-14 14:20 UTC, SeanMooney commented
/test precommit-check

2023-03-14 21:26 UTC, SeanMooney commented
it failed on go tidy
lets see if a rebase will fix it

2023-03-14 21:38 UTC, SeanMooney requested changes
go tidy is still failing


gotidy...................................................................Failed
- hook id: gotidy
- duration: 1.14s
- files were modified by this hook

2023-03-15 12:43 UTC, amolkahat commented
@SeanMooney Updated. Thank you.

2023-03-21 10:35 UTC, amolkahat commented
/test precommit-check

2023-03-23 08:40 UTC, gibizer commented
please consider https://github.com/openstack-k8s-operators/nova-operator/pull/302 here as well

2023-03-27 08:36 UTC, amolkahat commented on .pre-commit-config.yaml
> -    - id: go-fmt
Removed `go-fmt go-vet and go-mod-tidy` which already added in local repo.

2023-03-27 11:33 UTC, SeanMooney commented
in general i would prefer to reference the ci logs then local executions
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_nova-operator/269/pull-ci-openstack-k8s-operators-nova-operator-master-precommit-check/1640269815828451328/artifacts/test/build-log.txt
but it also passes there so i think this is good ill review it quickly

2023-03-27 11:35 UTC, SeanMooney requested changes

2023-03-27 11:35 UTC, SeanMooney commented on .pre-commit-config.yaml
>      - id: go-lint
if the intent is to remove the use of this external repo then this should also be ported.
Note it is pinned by the git tag so the deprecation does not actually affect our usage of the repo.

2023-03-27 11:48 UTC, amolkahat commented on .pre-commit-config.yaml
>      - id: go-lint
Ok. I think removing it would be better and use make to run lint will make seance.

2023-03-27 12:24 UTC, amolkahat commented
/retest-required

2023-03-27 15:50 UTC, gibizer reviewed
Looks OK to me

2023-03-28 05:54 UTC, amolkahat commented
/retest-required  nova-operator-build-deploy failed.

2023-03-28 05:55 UTC, amolkahat commented
/retest-required

2023-03-28 06:19 UTC, amolkahat commented
/test nova-operator-build-deploy

2023-03-28 09:32 UTC, SeanMooney commented on .pre-commit-config.yaml
> +      # E012: here doc didn't end before EOF
# E012: here doc didn't end before EOF

i dont really like skiping this check

2023-03-28 09:35 UTC, SeanMooney commented on Makefile
> +	test -s $(LOCALBIN)/golangci-lint || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
the correct way to install it would be 
go install golang.org/x/lint/golint

but since we are working on removing this now i guess this is fine for now

2023-03-28 09:35 UTC, SeanMooney approved these changes

2023-03-28 09:57 UTC, merged