Refactor tests help function
openstack-k8s-operators/nova-operator pull request #284
Opened 2023-03-07 11:56 UTC by mrKisaoLamb

Refactor tests helping function and remove redundunt code

2023-03-07 12:39 UTC, bogdando commented on test/functional/base_test.go
> -func DeleteNovaAPI(name types.NamespacedName) {
I think dropping these ``DeleteFoo*`` is ok, as we don't want really test k8s capabilities on removing custom resources here?

2023-03-07 15:07 UTC, gibizer requested changes

2023-03-07 15:07 UTC, gibizer commented on test/functional/nova_controller_test.go
> +			DeferCleanup(DeleteInstance, &novav1.Nova{}, novaName)
So instead of passing an empty Nova{} and a novaName separately I think we can pass a single Nova with the metadata filled. Something like: Nova{Name:novaName.Name, Namespace:novaName.Namespace}

2023-03-08 10:25 UTC, mrKisaoLamb commented on test/functional/base_test.go
> -func DeleteNovaAPI(name types.NamespacedName) {
thanks for review! IMO covering finalizer sound better than testing k8s itself

2023-03-08 10:26 UTC, mrKisaoLamb commented on test/functional/nova_controller_test.go
> +			DeferCleanup(DeleteInstance, &novav1.Nova{}, novaName)
Probably finalizers or any 'clearing' func that we come up in future is better plase to test for checking if resources are deleted

2023-03-08 10:26 UTC, mrKisaoLamb commented on test/functional/base_test.go
> -	logger.Info("Deleting Nova", "Nova", name)
Done, be38a94be3282e4b6d6c16be4bb2896e9c99aca7

2023-03-08 10:26 UTC, mrKisaoLamb commented on test/functional/base_test.go
> +func DeleteInstance(instance client.Object, name types.NamespacedName) {
Done, be38a94be3282e4b6d6c16be4bb2896e9c99aca7

2023-03-08 10:26 UTC, mrKisaoLamb commented on test/functional/nova_controller_test.go
> +			DeferCleanup(DeleteInstance, &novav1.Nova{}, novaName)
Done, be38a94be3282e4b6d6c16be4bb2896e9c99aca7

2023-03-08 10:59 UTC, gibizer requested changes

2023-03-08 10:59 UTC, gibizer commented on test/functional/base_test.go
> +	logger.Info("Deleting", "Name", instance.GetName(), "Namespace", instance.GetNamespace(), "Kind", instance.GetObjectKind())
This result in a log

```
"Kind": "&TypeMeta{Kind:,APIVersion:,}"}
```

Probably because we are not calling the Delete with an object that has the TypeMeta part filled.

I have a fix for a particular case (see below). And if that applicable for every call then:
```golang
	logger.Info("Deleting", "Name", instance.GetName(), "Namespace", instance.GetNamespace(), "Kind", instance.GetObjectKind().GroupVersionKind().Kind)
```
would be enough here.  (Yeah `GetObjectKind` is more than what we need hence my digging into it`)

2023-03-08 10:59 UTC, gibizer commented on test/functional/nova_controller_test.go
> +			DeferCleanup(DeleteInstance, &novav1.Nova{ObjectMeta: metav1.ObjectMeta{Name: novaName.Name, Namespace: novaName.Namespace}})
We can change this to pass the object to DeleteInstance that was created by CreateNovaWithCell0. This solves the logging issue and actually make the code more readable here.

```golang
                       DeferCleanup(DeleteInstance, CreateNovaWithCell0(novaName))
```

This needs additional work in CreateNovaWithCell0 to return the created object. See the whole change I needed to support it:

```diff
diff --git a/test/functional/base_test.go b/test/functional/base_test.go
index 54143bd..4d062b7 100644
--- a/test/functional/base_test.go
+++ b/test/functional/base_test.go
@@ -50,12 +50,13 @@ const (
 	consistencyTimeout = timeout
 )
 
-func CreateUnstructured(rawObj map[string]interface{}) {
+func CreateUnstructured(rawObj map[string]interface{}) *unstructured.Unstructured {
 	logger.Info("Creating", "raw", rawObj)
 	unstructuredObj := &unstructured.Unstructured{Object: rawObj}
 	_, err := controllerutil.CreateOrPatch(
 		ctx, k8sClient, unstructuredObj, func() error { return nil })
 	Expect(err).ShouldNot(HaveOccurred())
+	return unstructuredObj
 }
 
 func GetDefaultNovaAPISpec() map[string]interface{} {
@@ -174,7 +175,7 @@ func CreateNovaWithoutCell0(name types.NamespacedName) {
 	CreateUnstructured(rawNova)
 }
 
-func CreateNovaWithCell0(name types.NamespacedName) {
+func CreateNovaWithCell0(name types.NamespacedName) client.Object {
 	rawNova := map[string]interface{}{
 		"apiVersion": "nova.openstack.org/v1beta1",
 		"kind":       "Nova",
@@ -193,12 +194,12 @@ func CreateNovaWithCell0(name types.NamespacedName) {
 		},
 	}
 
-	CreateUnstructured(rawNova)
+	return CreateUnstructured(rawNova)
 }
 
 func DeleteInstance(instance client.Object) {
 	// We have to wait for the controller to fully delete the instance
-	logger.Info("Deleting", "Name", instance.GetName(), "Namespace", instance.GetNamespace(), "Kind", instance.GetObjectKind())
+	logger.Info("Deleting", "Name", instance.GetName(), "Namespace", instance.GetNamespace(), "Kind", instance.GetObjectKind().GroupVersionKind().Kind)
 	Eventually(func(g Gomega) {
 		name := types.NamespacedName{Name: instance.GetName(), Namespace: instance.GetNamespace()}
 		err := k8sClient.Get(ctx, name, instance)
diff --git a/test/functional/nova_controller_test.go b/test/functional/nova_controller_test.go
index 09a0b32..c0e1fa6 100644
--- a/test/functional/nova_controller_test.go
+++ b/test/functional/nova_controller_test.go
@@ -177,8 +177,7 @@ var _ = Describe("Nova controller", func() {
 			)
 			DeferCleanup(th.DeleteKeystoneAPI, th.CreateKeystoneAPI(namespace))
 
-			CreateNovaWithCell0(novaName)
-			DeferCleanup(DeleteInstance, &novav1.Nova{ObjectMeta: metav1.ObjectMeta{Name: novaName.Name, Namespace: novaName.Namespace}})
+			DeferCleanup(DeleteInstance, CreateNovaWithCell0(novaName))
 		})
 
 		It("registers nova service to keystone", func() {
```

I'm not 100% sure we can apply this in all DeleteInstance cases but I hope we can

2023-03-09 08:14 UTC, mrKisaoLamb commented on test/functional/nova_controller_test.go
> +			DeferCleanup(DeleteInstance, &novav1.Nova{ObjectMeta: metav1.ObjectMeta{Name: novaName.Name, Namespace: novaName.Namespace}})
Thanks! Done all CreateFooInstance return client.Object now instead nil or namespace

2023-03-09 08:43 UTC, gibizer commented on test/functional/nova_controller_test.go
> +			DeferCleanup(DeleteInstance, &novav1.Nova{ObjectMeta: metav1.ObjectMeta{Name: novaName.Name, Namespace: novaName.Namespace}})
Log looks good now.
```
2023-03-09T09:40:31.765+0100	INFO	---Test---	Deleting	{"Name": "c262c9f3-7a82-441d-9737-bacc0b6ca1f8", "Namespace": "723eaa21-bb60-454c-b094-769914135b30", "Kind": "Nova"}
```

2023-03-09 10:59 UTC, gibizer approved these changes
Looks good to me. Thanks for simplifying the test code!

2023-03-09 11:05 UTC, merged