[WIP] [EnvTest]Factor out name handling
openstack-k8s-operators/nova-operator pull request #323
Opened 2023-03-31 16:18 UTC by bogdando

Resubmitted https://github.com/openstack-k8s-operators/nova-operator/pull/203 after rebase and extending factoring out for the new things added

The transport URL related change to be dropped as have been extracted https://github.com/openstack-k8s-operators/nova-operator/pull/338

There is clear pattern how the nova-operator names the resources it
creates but we repeating the same naming logic all over our test code.
So this patch moves the naming logic to a single place in the test.

Rebase and extend the original factoring out change to the newly
added services (Metadata, Scheduler, and ExternalCompute (partially)).

Move novaName(s) with a 3 cells names initialization from a generated
namespace uuid into the shared BeforeEach() for all tests.

Align individual names prefixes for NovaName/CellName with the internal
Nova controllers logic.

Remove no longer needed instance getters as using predictable names,
when instantiating things.

2023-04-03 10:07 UTC, gibizer requested changes

2023-04-03 10:11 UTC, gibizer commented
/test all

2023-04-03 10:13 UTC, gibizer commented
Did you managed to run the `make test` target successfully on this? I see multiple failure locally...

2023-04-03 10:37 UTC, gibizer commented
```
  Ginkgo detected an issue with your spec structure
  It("does not create NovaAPI", func() {
  /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/nova_controller_test.go:343
    It looks like you are trying to add a [It] node
    to the Ginkgo spec tree in a leaf node after the specs started running.

    To enable randomization and parallelization Ginkgo requires the spec tree
    to be fully constructed up front.  In practice, this means that you can
    only create nodes like [It] at the top-level or within the
    body of a Describe, Context, or When.
```

2023-04-03 12:32 UTC, bogdando commented
> Did you manage to run the make test target successfully on this? I see multiple failure locally...

not yet :(

2023-04-03 14:52 UTC, bogdando commented
another problem is novaNames is instanciated with empty values, like here https://github.com/bogdando/nova-operator/blob/e6020fed4ad48dbe389362fd0e39dbdf2a66e064/test/functional/nova_scheduler_test.go#L252 (but in many other places as well)

2023-04-04 13:16 UTC, gibizer commented
> this is still WIP, the recent update ([7633b81 ](https://github.com/openstack-k8s-operators/nova-operator/commit/7633b81ecbefc00cd3cb794b6a5224dea7cc3370)to [626a058](https://github.com/openstack-k8s-operators/nova-operator/commit/626a0587ed633547f7a8ed32fd7b6fdce69b330a)) illustrates the direction needed to re-initialize novaNames after the GetName() called. We might want to introduce some novaNames updater method for that. @gibizer WDYT?

It think the NovaNames  idea is now pushed further than I originally intended. In the original PR the struct was used in the tests where Nova CR is created. It was used there because when a Nova CR is created with a name X then the nova controller will create sub resource using that X name as the basis for the name of the sub resources. E.g. when Nova/X is created nova-controller will create NovaAPI/X-api and StatefulSet/X-api. Also the tests always generate the name X to be a unique UUID for test case separation and to validate that the controller code never assumes that X is set to "nova".

Subsequently when the test just creates a sub resource like NovaAPI, it will also generate a unique UUID for its name. This makes reusing the NovaNames struct a bit hard. As in Nova CR tests NovaAPI will have X-api name but in NovaAPI tests it will have just X. 

As both X and X-api is unique across tests due to X being generated for each test, I think the better approach would be to change the sub resource tests to generate sub resources with the same name pattern as when the nova-controller generates the subresoruce. For that you need to change the CreateNovaXXX[1] functions to take the name of the resource as a parameter instead of internally generating one. Then you can initialize a NovaNames struct at the start with a unique novaName and pass the specific service name from the struct to CreateNovaXXX.

[1] https://github.com/openstack-k8s-operators/nova-operator/blob/7c7bb242828804c3f7d357b703e095391abb0f79/test/functional/base_test.go#L73-L74

2023-04-04 15:41 UTC, bogdando commented
> It think the NovaNames idea is now pushed further than I originally intended

Thank you for the hints, I'll return this back to the intended design then

2023-04-04 16:15 UTC, gibizer commented
> > It think the NovaNames idea is now pushed further than I originally intended
> 
> Thank you for the hints, I'll return this back to the intended design then

In the contrary, later in my comment above pointed you to a direction that would make it possible to use the NovaNames for the sub resource tests too.

2023-04-06 13:13 UTC, bogdando commented
> > > It think the NovaNames idea is now pushed further than I originally intended
> > 
> > 
> > Thank you for the hints, I'll return this back to the intended design then
> 
> In the contrary, later in my comment above pointed you to a direction that would make it possible to use the NovaNames for the sub resource tests too.

In the [recent update](https://github.com/openstack-k8s-operators/nova-operator/compare/626a0587ed633547f7a8ed32fd7b6fdce69b330a..a794dfad5de3e240cc6e64ca2f6fb968ee8bf235)
I tried to address that, but still not sure about certain things, especially which names to use for all CreateNovaMessageBusSecret / CreateNovaSecret calls

2023-04-07 14:37 UTC, bogdando commented
73 Passed | 79 Failed - I'm making a progress ! :)

2023-04-11 14:27 UTC, gibizer requested changes
Looks better

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_metadata_controller_test.go
>  	})
you can drop the empty BeforeEach now

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			// TODO(bogdando): test creating KeystoneAPI in its own namespace?
Nope. There should not be cross namespace dependency between our CRs. So the whole openstack deployment needs to be the a single namespace. (The operator controller managers might be a different one but we are not testing those here)

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			keystoneApiName := th.CreateKeystoneAPI(novaNames.NovaName.Namespace)
Based on https://github.com/golang/go/wiki/CodeReviewComments#initialisms This should be `keystoneAPIName`

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell0Template["cellDatabaseInstance"] = cell0.MariaDBDatabaseName.Name // or openstack ?
cell0.MaraiDBDatabaseName.Name is the correct one the `openstack` is just a defaulting in OpenstackControlPlane https://github.com/openstack-k8s-operators/openstack-operator/blob/f04c6106bf409ce669baa03dd66743229d09f9ad/config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml#L63

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell1Template["cellDatabaseInstance"] = cell1.MariaDBDatabaseName.Name // or openstack ?
ditto, the code you proposed here is correct.

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			spec["apiDatabaseInstance"] = novaNames.APIMariaDBDatabaseName.Name // or openstack ?
ditto, the code you proposed here is correct.

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			keystoneAPIName := th.CreateKeystoneAPI(novaNames.NovaName.Namespace)
we should not have cross namespace dependencies

2023-04-11 14:27 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +	// TODO(bogdando): test KeystoneAPI creation in its own namespace?
nope

2023-04-11 14:27 UTC, gibizer commented on test/functional/suite_test.go
> +	cell2     CellNames
I would call them `cell0Names` to distingush between a NovaCell instance from a CellName instance.

2023-04-11 14:27 UTC, gibizer commented on test/functional/novaapi_controller_test.go
> +						Name:      fmt.Sprintf("%s-config-data", novaNames.APIName.Name),
Don't need do it in this PR but the config-data ConfigMap name generation can be hidden in NovaNames also.

2023-04-11 14:27 UTC, gibizer commented on test/functional/novaexternalcompute_controller_test.go
> +			// TODO(bogdando): maybe also switch to novaNames.Compute*
Yeah we might need to support more than one compute for testing. But we can take that separately

2023-04-11 14:39 UTC, bogdando commented on test/functional/suite_test.go
> +	cell2     CellNames
that makes sense, although that would be names changes over pretty much a tone of test cases that used to use these names

2023-04-11 15:25 UTC, gibizer commented on test/functional/suite_test.go
> +	cell2     CellNames
I think vscode can handle the rename automatically. But I'm OK to keep it for now and do the rename in a separate step to limit the diff size in the current PR.

2023-04-11 15:34 UTC, gibizer commented
I'm trying to help by debugging one failing test case here.
I selected `[FAIL] NovaAPI controller when NovAPI is created [It] creates KeystoneEndpoint` as it is a fairly simple one to start with.

I run that single test case with `make test GINKGO_ARGS="--focus 'when NovAPI is created.*creates KeystoneEndpoint' -v"`

It produced the log:
```
NovaAPI controller when NovAPI is created creates KeystoneEndpoint
/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:312
2023-04-11T16:45:51.518+0200	INFO	---Test---	Creating	{"raw": {"apiVersion":"nova.openstack.org/v1beta1","kind":"NovaAPI","metadata":{"name":"322fe3f5-0e8c-4169-84ed-9ec206e62b86-api","namespace":"b42f4aa9-cfc3-455d-825a-bc816c0a3b79"},"spec":{"apiDatabaseHostname":"nova-api-db-hostname","apiMessageBusSecretName":"rabbitmq-secret","cell0DatabaseHostname":"nova-cell0-db-hostname","containerImage":"test://nova","keystoneAuthURL":"keystone-auth-url","secret":"test-secret"}}}
2023-04-11T16:45:51.715+0200	INFO	Starting workers	{"controller": "novaexternalcompute", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaExternalCompute", "worker count": 1}
2023-04-11T16:45:51.715+0200	INFO	Starting workers	{"controller": "novaconductor", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaConductor", "worker count": 1}
2023-04-11T16:45:51.715+0200	INFO	Starting workers	{"controller": "novacell", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaCell", "worker count": 1}
2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novametadata", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaMetadata", "worker count": 1}
2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novaapi", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaAPI", "worker count": 1}
2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novascheduler", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaScheduler", "worker count": 1}
2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novanovncproxy", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaNoVNCProxy", "worker count": 1}
2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "nova", "controllerGroup": "nova.openstack.org", "controllerKind": "Nova", "worker count": 1}
2023-04-11T16:45:53.628+0200	INFO	---Test---	ExpectCondition	{"type": "ServiceConfigReady", "expected status": "True", "on": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79/322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.628+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.628+0200	INFO	controllers.NovaAPI	Added finalizer to ourselves	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.632+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.734+0200	INFO	controllers.NovaAPI	ConfigMap 322fe3f5-0e8c-4169-84ed-9ec206e62b86-api-config-data successfully reconciled - operation: created
2023-04-11T16:45:53.736+0200	INFO	controllers.NovaAPI	StatefulSet 322fe3f5-0e8c-4169-84ed-9ec206e62b86-api - created
2023-04-11T16:45:53.736+0200	INFO	controllers.NovaAPI	Deployment is not ready	{"Status": {"replicas":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.736+0200	INFO	controllers.NovaAPI	Waiting for the Deployment to become Ready before exposing the sevice in Keystone	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.738+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.749+0200	INFO	controllers.NovaAPI	StatefulSet 322fe3f5-0e8c-4169-84ed-9ec206e62b86-api - updated
2023-04-11T16:45:53.749+0200	INFO	controllers.NovaAPI	Deployment is not ready	{"Status": {"replicas":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.749+0200	INFO	controllers.NovaAPI	Waiting for the Deployment to become Ready before exposing the sevice in Keystone	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:45:53.832+0200	INFO	---Test---	ExpectCondition succeeded	{"type": "ServiceConfigReady", "expected status": "True", "on": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79/322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
  [FAILED] in [It] - /home/gibi/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.0.0-20230307144813-39ed0da90b23/helpers/statefulset.go:29 @ 04/11/23 16:46:03.833
2023-04-11T16:46:03.833+0200	INFO	---Test---	Deleting	{"Name": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api", "Namespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "Kind": "NovaAPI"}
2023-04-11T16:46:03.836+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:46:03.836+0200	INFO	controllers.NovaAPI	Reconciling delete	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:46:03.837+0200	INFO	controllers.NovaAPI	Removed finalizer from ourselves	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:46:03.837+0200	INFO	controllers.NovaAPI	Reconciled delete successfully	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
2023-04-11T16:46:03.839+0200	INFO	NovaAPI instance not found, probably deleted before reconciled. Nothing to do.	{"controller": "novaapi", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaAPI", "NovaAPI": {"name":"322fe3f5-0e8c-4169-84ed-9ec206e62b86-api","namespace":"b42f4aa9-cfc3-455d-825a-bc816c0a3b79"}, "namespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "name": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api", "reconcileID": "c92c522d-f0b9-4f54-92ea-e7105a68296a"}
• [FAILED] [12.427 seconds]
NovaAPI controller when NovAPI is created [It] creates KeystoneEndpoint
/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:312

  [FAILED] Timed out after 10.001s.
  The function passed to Eventually failed at /home/gibi/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.0.0-20230307144813-39ed0da90b23/helpers/statefulset.go:28 with:
  Expected success, but got an error:
      <*errors.StatusError | 0xc000d9e1e0>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "statefulsets.apps \"322fe3f5-0e8c-4169-84ed-9ec206e62b86-api-statefulset\" not found",
              Reason: "NotFound",
              Details: {
         [...]

2023-04-12 11:35 UTC, bogdando commented
> I'm trying to help by debugging one failing test case here. I selected `[FAIL] NovaAPI controller when NovAPI is created [It] creates KeystoneEndpoint` as it is a fairly simple one to start with.
> 
> I run that single test case with `make test GINKGO_ARGS="--focus 'when NovAPI is created.*creates KeystoneEndpoint' -v"`
> 
> It produced the log:
> 
> ```
> NovaAPI controller when NovAPI is created creates KeystoneEndpoint
> /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:312
> 2023-04-11T16:45:51.518+0200	INFO	---Test---	Creating	{"raw": {"apiVersion":"nova.openstack.org/v1beta1","kind":"NovaAPI","metadata":{"name":"322fe3f5-0e8c-4169-84ed-9ec206e62b86-api","namespace":"b42f4aa9-cfc3-455d-825a-bc816c0a3b79"},"spec":{"apiDatabaseHostname":"nova-api-db-hostname","apiMessageBusSecretName":"rabbitmq-secret","cell0DatabaseHostname":"nova-cell0-db-hostname","containerImage":"test://nova","keystoneAuthURL":"keystone-auth-url","secret":"test-secret"}}}
> 2023-04-11T16:45:51.715+0200	INFO	Starting workers	{"controller": "novaexternalcompute", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaExternalCompute", "worker count": 1}
> 2023-04-11T16:45:51.715+0200	INFO	Starting workers	{"controller": "novaconductor", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaConductor", "worker count": 1}
> 2023-04-11T16:45:51.715+0200	INFO	Starting workers	{"controller": "novacell", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaCell", "worker count": 1}
> 2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novametadata", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaMetadata", "worker count": 1}
> 2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novaapi", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaAPI", "worker count": 1}
> 2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novascheduler", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaScheduler", "worker count": 1}
> 2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "novanovncproxy", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaNoVNCProxy", "worker count": 1}
> 2023-04-11T16:45:51.716+0200	INFO	Starting workers	{"controller": "nova", "controllerGroup": "nova.openstack.org", "controllerKind": "Nova", "worker count": 1}
> 2023-04-11T16:45:53.628+0200	INFO	---Test---	ExpectCondition	{"type": "ServiceConfigReady", "expected status": "True", "on": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79/322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.628+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.628+0200	INFO	controllers.NovaAPI	Added finalizer to ourselves	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.632+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.734+0200	INFO	controllers.NovaAPI	ConfigMap 322fe3f5-0e8c-4169-84ed-9ec206e62b86-api-config-data successfully reconciled - operation: created
> 2023-04-11T16:45:53.736+0200	INFO	controllers.NovaAPI	StatefulSet 322fe3f5-0e8c-4169-84ed-9ec206e62b86-api - created
> 2023-04-11T16:45:53.736+0200	INFO	controllers.NovaAPI	Deployment is not ready	{"Status": {"replicas":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.736+0200	INFO	controllers.NovaAPI	Waiting for the Deployment to become Ready before exposing the sevice in Keystone	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.738+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.749+0200	INFO	controllers.NovaAPI	StatefulSet 322fe3f5-0e8c-4169-84ed-9ec206e62b86-api - updated
> 2023-04-11T16:45:53.749+0200	INFO	controllers.NovaAPI	Deployment is not ready	{"Status": {"replicas":0,"availableReplicas":0}, "ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.749+0200	INFO	controllers.NovaAPI	Waiting for the Deployment to become Ready before exposing the sevice in Keystone	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:45:53.832+0200	INFO	---Test---	ExpectCondition succeeded	{"type": "ServiceConfigReady", "expected status": "True", "on": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79/322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
>   [FAILED] in [It] - /home/gibi/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.0.0-20230307144813-39ed0da90b23/helpers/statefulset.go:29 @ 04/11/23 16:46:03.833
> 2023-04-11T16:46:03.833+0200	INFO	---Test---	Deleting	{"Name": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api", "Namespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "Kind": "NovaAPI"}
> 2023-04-11T16:46:03.836+0200	INFO	controllers.NovaAPI	Reconciling	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:46:03.836+0200	INFO	controllers.NovaAPI	Reconciling delete	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:46:03.837+0200	INFO	controllers.NovaAPI	Removed finalizer from ourselves	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:46:03.837+0200	INFO	controllers.NovaAPI	Reconciled delete successfully	{"ObjectType": "*v1beta1.NovaAPI", "ObjectNamespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "ObjectName": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api"}
> 2023-04-11T16:46:03.839+0200	INFO	NovaAPI instance not found, probably deleted before reconciled. Nothing to do.	{"controller": "novaapi", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaAPI", "NovaAPI": {"name":"322fe3f5-0e8c-4169-84ed-9ec206e62b86-api","namespace":"b42f4aa9-cfc3-455d-825a-bc816c0a3b79"}, "namespace": "b42f4aa9-cfc3-455d-825a-bc816c0a3b79", "name": "322fe3f5-0e8c-4169-84ed-9ec206e62b86-api", "reconcileID": "c92c522d-f0b9-4f54-92ea-e7105a68296a"}
> • [FAILED] [12.427 seconds]
> NovaAPI controller when NovAPI is created [It] creates KeystoneEndpoint
> /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:312
> 
>   [FAILED] Timed out after 10.001s.
>   The function passed to Eventually failed at /home/gibi/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.0.0-20230307144813-39ed0da90b23/helpers/statefulset.go:28 with:
>   Expected success, but got an error:
>       <*errors.StatusError | 0xc000d9e1e0>: {
>           ErrStatus: {
>               TypeMeta: {Kind: "", APIVersion: ""},
>               ListMeta: {
>                   SelfLink: "",
>                   ResourceVersion: "",
>                   Continue: "",
>                   RemainingItemCount: nil,
>               },
>               Status: "Failure",
>               Message: "statefulsets.apps \"322fe3f5-0e8c-4169-84 [...]

2023-04-12 12:43 UTC, gibizer commented
> 
> @gibizer This could be a naming issue in the code, so then we should not adjust the test case, but fix it.
> 
> While debugging it, I'm seeing that the [caller](https://github.com/bogdando/nova-operator/blob/pr/gibizer/203/controllers/novaapi_controller.go#L393) has `instance.ObjectMeta.Name=<uuid>-api` (also the `req` already does at the `Reconcile()` [entrance](https://github.com/bogdando/nova-operator/blob/pr/gibizer/203/controllers/novaapi_controller.go#L76)). And then [inside](https://github.com/bogdando/nova-operator/blob/pr/gibizer/203/pkg/novaapi/deployment.go#L147) the func we'll get `*-api-api`.

That is not the name of the StatefulSet that is the name of the containers in the Pod of the StatefulSet. There we have two containers. On that runs the service and one that tails the service logs to the stdout. The former is called nova-api-api the latter is called nova-api-log. But the StatefulSet is called the same as the NovaAPI CR creating the StatefulSet. 

So extending the naming three that I mentioned on slack:
```
Nova=foo
|
-- NovaAPI=foo-api
|  |
|   -- StatefulSet=foo-api
|      |
|      -- ... Container foo-api-api
|      -- ... Container foo-api-log
|
-- NovaScheduler=foo-scheduler
...
```

We can discuss renaming the Containers I can see that -api-api might be confusing.

2023-04-17 12:36 UTC, bogdando commented
111 Passed | 23 Failed , almost done!

2023-04-27 13:02 UTC, gibizer commented on test/functional/base_test.go
> +		Name:      fmt.Sprintf("%s-api", uuid.New().String()),
https://github.com/openstack-k8s-operators/nova-operator/blob/0919c990d8eb45a6f13961e00eb8f37628ec3c8f/controllers/nova_controller.go#L731-L733

2023-04-27 13:35 UTC, bogdando commented on test/functional/base_test.go
> +		Name:      fmt.Sprintf("%s-api", uuid.New().String()),
Thanks, fixing these all. What about ext compute name?

2023-04-27 13:40 UTC, gibizer commented on test/functional/base_test.go
> +		Name:      fmt.Sprintf("%s-api", uuid.New().String()),
Good point. NovaExternalCompute CRs are created by the dataplane-operator with its own naming scheme that uses the name of the OpenstackDataPlaneNode CR as the name of the NovaExternalCompute CR. So there is not dependency between the name of the Nova CR and the name of the NovaExternalCompute CR. So generating a new uuid there is the good solution.

https://github.com/openstack-k8s-operators/dataplane-operator/blob/c0a31c89531b0c7fc085b3fba1214d6955a37c56/pkg/deployment/nova.go#L40-L45
https://github.com/openstack-k8s-operators/dataplane-operator/blob/c0a31c89531b0c7fc085b3fba1214d6955a37c56/controllers/openstackdataplane_controller.go#L262-L267

2023-04-27 14:11 UTC, bogdando commented
Just 26 Failures so far. I sense victory :)

2023-04-27 14:12 UTC, bogdando commented
> > 111 Passed | 23 Failed , almost done!
> 
> 121 Passed | 39 Failed

yes, tjat was after a recent rebase on mastere

2023-04-28 10:03 UTC, mrKisaoLamb requested changes

2023-04-28 12:55 UTC, mrKisaoLamb commented on test/functional/novaconductor_controller_test.go
> -						InterfaceRequest: "internalapi",
you shoudn't remove InterfaceRequest plus I thing that correct namespace shoud be Namespace: novaNames.NovaName.Namespace. Same thing should apply in other "reports that network attachment is missing" tests

2023-04-28 12:55 UTC, mrKisaoLamb commented on test/functional/novaapi_controller_test.go
> +			th.SimulateKeystoneEndpointReady(novaNames.NovaName)
this should be novaNames.APIKeystoneEndpointName

2023-04-28 12:57 UTC, bogdando commented on test/functional/base_test.go
> +			Name:      cell + "-transport",
thank you for spotting that! that's likely was a cause for some remaining test failures

2023-04-28 13:05 UTC, mrKisaoLamb commented on test/functional/nova_multicell_test.go
> +			th.SimulateMariaDBDatabaseCompleted(novaNames.APIMariaDBDatabaseName)
because now all databases are separate you will need to add :
`DeferCleanup(
				th.DeleteDBService,
				th.CreateDBService(cell1.MariaDBDatabaseName.Namespace, cell1.MariaDBDatabaseName.Name, serviceSpec))
			DeferCleanup(
				th.DeleteDBService,
				th.CreateDBService(cell0.MariaDBDatabaseName.Namespace, cell0.MariaDBDatabaseName.Name, serviceSpec))`

2023-04-28 13:06 UTC, bogdando commented on test/functional/novaconductor_controller_test.go
> -						InterfaceRequest: "internalapi",
oh, that was unintentional... Thank you, having a fresh sight always helps!

2023-04-28 13:16 UTC, bogdando commented on test/functional/nova_metadata_controller_test.go
> +var _ = Describe("NovaMetadata controller", func() {
will do, added TODO in the commit msg for now

2023-04-28 13:17 UTC, bogdando commented
Summarizing 6 Failures:
  [FAIL] Nova multicell when Nova CR instance is created with collapsed cell deployment [It] cell0 becomes ready with 0 conductor replicas and the rest of nova is deployed
  /opt/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.0.0-20230413063528-4486d492bfc6/helpers/database.go:75
  [FAIL] NovaMetadata controller when NovaMetadata is created with networkAttachments [It] reports that an IP is missing
  /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/nova_metadata_controller_test.go:379
  [FAIL] NovaAPI controller when NovaAPI is created with networkAttachments [It] reports that an IP is missing
  /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:449
  [FAIL] NovaScheduler controller when NovaScheduler is created with networkAttachments [It] reports that an IP is missing
  /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/nova_scheduler_test.go:364
  [FAIL] Nova multicell when Nova CR instance is created with 3 cells [It] creates NovaAPI
  /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/nova_multicell_test.go:159
  [FAIL] NovaConductor controller when NovaConductor is created with networkAttachments [It] reports that an IP is missing
  /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/novaconductor_controller_test.go:549

Ran 160 of 160 Specs in 51.619 seconds
FAIL! -- 154 Passed | 6 Failed | 0 Pending | 0 Skipped

2023-04-28 13:21 UTC, mrKisaoLamb commented
> Summarizing 6 Failures: [FAIL] Nova multicell when Nova CR instance is created with collapsed cell deployment [It] cell0 becomes ready with 0 conductor replicas and the rest of nova is deployed /opt/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.0.0-20230413063528-4486d492bfc6/helpers/database.go:75 [FAIL] NovaMetadata controller when NovaMetadata is created with networkAttachments [It] reports that an IP is missing /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/nova_metadata_controller_test.go:379 [FAIL] NovaAPI controller when NovaAPI is created with networkAttachments [It] reports that an IP is missing /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:449 [FAIL] NovaScheduler controller when NovaScheduler is created with networkAttachments [It] reports that an IP is missing /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/nova_scheduler_test.go:364 [FAIL] Nova multicell when Nova CR instance is created with 3 cells [It] creates NovaAPI /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/nova_multicell_test.go:159 [FAIL] NovaConductor controller when NovaConductor is created with networkAttachments [It] reports that an IP is missing /opt/go/src/github.com/openstack-k8s-operators/nova-operator/test/functional/novaconductor_controller_test.go:549
> 
> Ran 160 of 160 Specs in 51.619 seconds FAIL! -- 154 Passed | 6 Failed | 0 Pending | 0 Skipped

2023-05-03 13:06 UTC, gibizer reviewed
This look OK to me. There is a need for a rebase and fixing the remaining failing tests then it is good to land.

2023-05-03 13:06 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +				g.Expect(conductorDeployment.Spec.Template.Spec.NodeSelector).To(Equal(conductorSelector))
you could keep the for loop iterating on CellNames but as this is just 3 items, I'm OK to unroll the loop

2023-05-05 14:26 UTC, bogdando commented on test/functional/nova_multicell_test.go
> +			th.SimulateMariaDBDatabaseCompleted(novaNames.APIMariaDBDatabaseName)
Added https://github.com/openstack-k8s-operators/nova-operator/pull/323/files#diff-501dc8d477c6c1c5a4ce5baa1398b7aac81e561f78563f882f508e8efe539745R508 and 509

2023-05-05 15:47 UTC, gibizer reviewed
I have an explanation and fix for
```
  [FAIL] Nova multicell when Nova CR instance is created with 3 cells [It] creates NovaAPI
```
inline

2023-05-05 15:47 UTC, gibizer commented on test/functional/nova_multicell_test.go
> -			cell0["cellDatabaseInstance"] = "db-for-api"
Here cell0 hadn't have a its one MariaDB service. But it was used the same as the NovaAPI. (Probably the same confusion I ended up with on slack today).

2023-05-05 15:47 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell0Template["cellDatabaseInstance"] = cell0.MariaDBDatabaseName.Name
Instead you configured a separate MariaDB DB server instance for cell0 here. This is a valid configuration. So I think we should keep it. (Yes in my today confusion in slack I said it is not valid, but that was a mistake on my side.)

2023-05-05 15:47 UTC, gibizer commented on test/functional/nova_multicell_test.go
>  			Expect(api.Spec.Cell0DatabaseHostname).To(Equal(api.Spec.APIDatabaseHostname))
due to the above test config change this assert is not true any more. It was only true on master due to cell0 used the same MariaDB DB service as the NovaAPI. So this should be replaced with the following now:
```diff
-                       Expect(api.Spec.Cell0DatabaseHostname).To(Equal(api.Spec.APIDatabaseHostname))
+                       Expect(api.Spec.APIDatabaseHostname).To(Equal(fmt.Sprintf("hostname-for-%s", novaNames.APIMariaDBDatabaseName.Name)))
                        Expect(api.Spec.APIMessageBusSecretName).To(Equal(fmt.Sprintf("%s-secret", cell0.TransportURLName.Name)))
```

2023-05-05 16:04 UTC, gibizer reviewed
I think I also have the reason why the following failed:
```
[FAIL] Nova multicell when Nova CR instance is created with collapsed cell deployment [It] cell0 becomes ready with 0 conductor replicas and the rest of nova is deployed
```
See inline

2023-05-05 16:04 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +				th.CreateDBService(novaNames.APIMariaDBDatabaseName.Namespace, novaNames.APIMariaDBDatabaseName.Name, serviceSpec))
this is the single Maria DB service we create

2023-05-05 16:04 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			spec["apiMessageBusInstance"] = cell0.TransportURLName.Name
this looks OK as it uses the single DB and MQ we have

2023-05-05 16:04 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			DeferCleanup(th.DeleteDBService, th.CreateDBService(cell0.MariaDBDatabaseName.Namespace, cell0.MariaDBDatabaseName.Name, serviceSpec))
Don't do this. This goes against the intended test setup

2023-05-08 10:21 UTC, bogdando commented on test/functional/nova_multicell_test.go
>  	When("Nova CR instance is created with collapsed cell deployment", func() {
will do

2023-05-08 10:26 UTC, bogdando commented on test/functional/nova_multicell_test.go
> +			th.SimulateMariaDBDatabaseCompleted(novaNames.APIMariaDBDatabaseName)
this test case is the only that that fails

2023-05-08 10:27 UTC, bogdando commented on test/functional/nova_multicell_test.go
>  		It("cell0 becomes ready with 0 conductor replicas and the rest of nova is deployed", func() {
this test case is the only that that fails for the recent update (I'll push it shortly)

2023-05-08 10:32 UTC, bogdando commented on test/functional/nova_multicell_test.go
>  		It("cell0 becomes ready with 0 conductor replicas and the rest of nova is deployed", func() {
nvm, all works now! so, pushing the *final* revision (well, until the next rebase!)

2023-05-08 10:35 UTC, bogdando commented on test/functional/base_test.go
> +	AdminNovaServiceName            types.NamespacedName
let's leave this for a follow-up please

2023-05-08 10:35 UTC, bogdando commented on test/functional/base_test.go
> +type NovaNames struct {
let's leave this for a follow-up please

2023-05-08 12:17 UTC, bogdando commented
and here we go the [latest rebase](https://github.com/openstack-k8s-operators/nova-operator/compare/ebb29a67a38d5b0faa2fb1a08f101c3a9fdd8e3b..71d5b72f72b816f33e8c4ad8afd2193755e81c6b) breaks it again

2023-05-08 13:08 UTC, bogdando commented
@SeanMooney @gibizer @mrKisaoLamb @stuggi I fixed the most recent rebase, by that morning, as a new one has arrived. Please hold on merging other patches to nova-operator for a moment

2023-05-08 13:12 UTC, bogdando commented
good to go (passes locally with current master branch rebased)

2023-05-08 13:22 UTC, gibizer requested changes

2023-05-08 13:22 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +				novaNames.NovaName,
L403 still fails as the generated config has `mysql+pymysql://nova_cell2:12345678@hostname-for-nova-cell2/nova_cell2` 
I think you forgot to apply the refactoring there:

```
			Expect(configDataMap.Data["01-nova.conf"]).To(
				ContainSubstring(fmt.Sprintf("[database]\nconnection = mysql+pymysql://nova_cell2:12345678@hostname-for-%s/nova_cell2", cell2.MariaDBDatabaseName.Name)),
			)
```

2023-05-08 13:23 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +				novaNames.NovaName,
I haaaate that I cannot comment on a nonchanged line :/

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell0Template["cellName"] = cell0.CellName.Name
the reintroduces https://github.com/openstack-k8s-operators/nova-operator/pull/359

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell1Template["cellName"] = cell1.CellName.Name
ditto

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell2Template["cellName"] = cell2.CellName.Name
ditto

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +	cell0Template["cellName"] = cell0.CellName.Name
ditto

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +	cell1Template["cellName"] = cell1.CellName.Name
ditto

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +	cell2Template["cellName"] = cell2.CellName.Name
ditto

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell0Template["cellName"] = cell0.CellName.Name
ditto

2023-05-08 13:33 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			cell1Template["cellName"] = cell1.CellName.Name
ditto

2023-05-09 08:28 UTC, gibizer commented
/test precommit-check

It seem like an infra issue that made the pre-commit setup extremely slow
```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/openstack/bashate.git.
[INFO] Initializing environment for https://github.com/golangci/golangci-lint.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/openstack/bashate.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:168","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2023-05-08T14:00:31Z"}
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:251","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 1h0m0s grace period","severity":"error","time":"2023-05-08T14:00:31Z"}
```

2023-05-09 08:42 UTC, merged