Webhooks for default images
openstack-k8s-operators/nova-operator pull request #335
Opened 2023-04-14 16:21 UTC by abays

Default container images are now handled via env vars and internal webhooks. This defaulting logic will in turn later be integrated with OpenStack Operator via webhooks there that use the new defaulting mechanism (while at the same time disabling the Nova service operator internal webhooks in that context).

2023-04-14 16:22 UTC, abays commented on api/v1beta1/nova_types.go
> +	// +kubebuilder:default={replicas:1,containerImage:""}
This is needed to satisfy the new `Required` constraint of the sub-components.  Otherwise CRD installation/creation fails.

2023-04-14 16:33 UTC, SeanMooney requested changes

2023-04-14 16:33 UTC, SeanMooney commented on api/v1beta1/nova_webhook.go
> +// NovaDefaults -
this seam incomplete to me.

when we discussed this before we had 3 levels of precidnece

1st the CR field
2nd the env vars
3rd a default in code that would be used when nothing is set in the env

this seams to be missing form this webhook implemenation.

2023-04-14 16:33 UTC, SeanMooney commented on main.go
> +	}
so what missing to resolve my previous comment
is we need to add ad decault for all the os.Getenv() calls to set a default in code if there is no env var defined and we don't have it set in the CR.

2023-04-14 16:33 UTC, SeanMooney commented on Makefile
> +	NOVA_API_IMAGE_URL_DEFAULT=quay.io/tripleozedcentos9/openstack-nova-api:current-tripleo \
if we have defaulted this in code properly then this should not be required.

2023-04-14 16:36 UTC, abays commented on api/v1beta1/nova_webhook.go
> +// NovaDefaults -
That is not the pattern we have used elsewhere, but it is something we can consider.

2023-04-17 08:53 UTC, mrKisaoLamb commented on test/functional/suite_test.go
We either do not have an image in config/samples/nova_v1beta1_novaexternalcompute.yaml (although we do have a containerimage in other samples), or there may be an issue with the defaulting in the test helper function (then we also should remove containerImage from other samples)

2023-04-17 09:14 UTC, abays commented on api/v1beta1/nova_webhook.go
> +Copyright 2022.
Scaffolding injected this.  Will fix.

2023-04-17 09:22 UTC, abays commented on api/v1beta1/webhook_suite_test.go
This file is created and adding by the `operator-sdk` scaffolding command for webhooks.  We can look into placing it elsewhere, but this is the recommended location for whatever reason.

2023-04-17 11:19 UTC, abays commented on main.go
> +	}
That does seem like an appropriate and reasonable thing to do.  Perhaps fall back to predefined constant if the associated environment variable is missing or is the zero-value empty string.

2023-04-17 11:36 UTC, SeanMooney commented on api/v1beta1/nova_webhook.go
> +Copyright 2023.
as an fyi I generally just avoid this entirely and only add the license header. That has been my upstream policy for years and what i would prefer to do here too
especially since we are not ascribing the copyright to anyone in this case.

so i would prefer to remove these rather then update them but this is not sufficient enough to warrant a respin on its own just a nit.

2023-04-17 11:38 UTC, SeanMooney commented on config/samples/nova_v1beta1_nova_collapsed_cell.yaml
> +        containerImage: quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo
we should not need to specify this in the samples
this should be defaulted by the defaulting webhook

2023-04-17 11:39 UTC, SeanMooney commented on config/samples/nova_v1beta1_nova_collapsed_cell.yaml
> +        containerImage: quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo
that is sepseicaly true when setting replicas: 0

i would be more ok with this if it was "" instead of a URL
but it should not be required to set contaienrImage in the samples.
we put effort into making sure they were not required in the past so this would be a regression if its currently required with this patch.

2023-04-17 11:45 UTC, SeanMooney commented on main.go
> +	}
yep so i think instead of s.Getenv

we can do something like this

func defaultEnv(key, default string) string {
    if value, ok := os.LookupEnv(key); ok {
        return value
    }
    return default
}


novaDefaults := novav1beta1.NovaDefaults{
		APIContainerImageURL:       os.defaultEnv("NOVA_API_IMAGE_URL_DEFAULT", "quay.io/tripleozedcentos9/openstack-nova-api:current-tripleo"),
		ConductorContainerImageURL: os.defaultEnv("NOVA_CONDUCTOR_IMAGE_URL_DEFAULT","quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo"),
		MetadataContainerImageURL:  os.defaultEnv("NOVA_METADATA_IMAGE_URL_DEFAULT","quay.io/tripleozedcentos9/openstack-nova-api:current-tripleo"),
		NoVNCContainerImageURL:     os.defaultEnv("NOVA_NOVNC_IMAGE_URL_DEFAULT","quay.io/tripleozedcentos9/openstack-nova-novnc:current-tripleo"),
		SchedulerContainerImageURL: os.defaultEnv("NOVA_SCHEDULER_IMAGE_URL_DEFAULT","quay.io/tripleozedcentos9/openstack-nova-scheduler:current-tripleo"),
	}

2023-04-17 11:50 UTC, gibizer reviewed
About the testing changes. 
I think we can enable the webhook to run during the existing envtests so 
1. we can minimize the test change needed
2. we can cover the webhook logic during the testing. 

I did some trials here https://github.com/gibizer/simple-operator-example/commit/16a188a210efee50ebb7cc54785c73b145bff8b8#diff-0b47813b56876b912e922bfe885d4529c58407ff08d6b7c422abed6aff774d65 about webhooks in envtest.

2023-04-17 13:05 UTC, abays commented on api/v1beta1/nova_types.go
> +	// +kubebuilder:default={replicas:1,containerImage:""}
Yes, I think we can switch it to optional and remove these.  I'll push another change for those and to include fall-back defaults for the various env vars as @SeanMooney suggested, and then the `containerImages` should hopefully always get a default value.  In that sense the `required` validation won't be needed.

2023-04-17 16:47 UTC, gibizer commented
Here is my stab on integrating the webhook with the existing envtest https://github.com/gibizer/nova-operator/commit/d1074224f9e746b4749e5e08ecc1938de5b16ba1

2023-04-17 17:33 UTC, abays commented on config/samples/nova_v1beta1_nova_collapsed_cell.yaml
> +        containerImage: quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo
The problem currently is that the `envtest` logic doesn't use the webhooks but does use these samples.  So for my initial local `envtest` testing, I had to add these.  @gibizer is investigating a solution to this such that webhooks can be used in `envtest`.

2023-05-01 09:47 UTC, abays commented
> @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/nova-operator-build-deploy 	[3685d00](https://github.com/openstack-k8s-operators/nova-operator/commit/3685d00dbc6de21411991060125e700cf52bf2d1) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_nova-operator/335/pull-ci-openstack-k8s-operators-nova-operator-master-nova-operator-build-deploy/1652957531942686720) 	false 	`/test nova-operator-build-deploy`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=nova-operator&pr=335). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).

This CI failure seems to be caused by something setting the webhooks to be disabled (this snippet is from the `nova-controller-manager` `describe` log):

```
Environment:
      NOVA_API_IMAGE_URL_DEFAULT:         quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
      NOVA_CONDUCTOR_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-conductor:current-podified
      NOVA_METADATA_IMAGE_URL_DEFAULT:    quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
      NOVA_NOVNC_IMAGE_URL_DEFAULT:       quay.io/podified-antelope-centos9/openstack-nova-novncproxy:current-podified
      NOVA_SCHEDULER_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-scheduler:current-podified
      NOVA_COMPUTE_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified
      NOVA_LIBVIRT_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-libvirt:current-podified
      NOVA_ANSIBLE_EE_IMAGE_URL_DEFAULT:  quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
      ENABLE_WEBHOOKS:                    false    <------- *** webhooks disabled ***
      WATCH_NAMESPACE:                    openstack
      OPERATOR_CONDITION_NAME:            openstack-operator.v0.0.1
```

2023-05-01 10:07 UTC, abays commented
> > @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/nova-operator-build-deploy 	[3685d00](https://github.com/openstack-k8s-operators/nova-operator/commit/3685d00dbc6de21411991060125e700cf52bf2d1) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_nova-operator/335/pull-ci-openstack-k8s-operators-nova-operator-master-nova-operator-build-deploy/1652957531942686720) 	false 	`/test nova-operator-build-deploy`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=nova-operator&pr=335). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).
> 
> This CI failure seems to be caused by something setting the webhooks to be disabled (this snippet is from the `nova-controller-manager` `describe` log):
> 
> ```
> Environment:
>       NOVA_API_IMAGE_URL_DEFAULT:         quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
>       NOVA_CONDUCTOR_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-conductor:current-podified
>       NOVA_METADATA_IMAGE_URL_DEFAULT:    quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
>       NOVA_NOVNC_IMAGE_URL_DEFAULT:       quay.io/podified-antelope-centos9/openstack-nova-novncproxy:current-podified
>       NOVA_SCHEDULER_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-scheduler:current-podified
>       NOVA_COMPUTE_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified
>       NOVA_LIBVIRT_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-libvirt:current-podified
>       NOVA_ANSIBLE_EE_IMAGE_URL_DEFAULT:  quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
>       ENABLE_WEBHOOKS:                    false    <------- *** webhooks disabled ***
>       WATCH_NAMESPACE:                    openstack
>       OPERATOR_CONDITION_NAME:            openstack-operator.v0.0.1
> ```
> 
> As a result, the `Nova` CR does not have its various `containerImage` fields populated and they are instead the empty-string.

Actually, this is proper.  The webhooks should be turned off in the Nova controller-manager.  I think this is a chicken-and-egg problem, however.  While Nova controller-manager's webhooks should be disabled in the context of an OpenStack operator deployment (which this is), the OpenStack operator needs to have this version of Nova so that it can call the defaulting mechanism from within its own webhooks.  My guess is that previous initial webhook PRs for other operators avoided this problem by happening to have the `containerImage`s set in the `OpenStackControlPlane` sample YAML [1] used by CI.

[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/master/config/samples/core_v1beta1_openstackcontrolplane.yaml

2023-05-01 17:39 UTC, abays commented on api/v1beta1/nova_webhook.go
> +// NovaDefaults -
BTW, I did end up adding this suggestion

2023-05-01 17:40 UTC, abays commented on api/v1beta1/novaexternalcompute_types.go
> -	// +kubebuilder:validation:Optional
Ack, added

2023-05-02 10:16 UTC, gibizer commented
> > > @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > > Test name 	Commit 	Details 	Required 	Rerun command
> > > ci/prow/nova-operator-build-deploy 	[3685d00](https://github.com/openstack-k8s-operators/nova-operator/commit/3685d00dbc6de21411991060125e700cf52bf2d1) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_nova-operator/335/pull-ci-openstack-k8s-operators-nova-operator-master-nova-operator-build-deploy/1652957531942686720) 	false 	`/test nova-operator-build-deploy`
> > > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=nova-operator&pr=335). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).
> > 
> > 
> > This CI failure seems to be caused by something setting the webhooks to be disabled (this snippet is from the `nova-controller-manager` `describe` log):
> > ```
> > Environment:
> >       NOVA_API_IMAGE_URL_DEFAULT:         quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
> >       NOVA_CONDUCTOR_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-conductor:current-podified
> >       NOVA_METADATA_IMAGE_URL_DEFAULT:    quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
> >       NOVA_NOVNC_IMAGE_URL_DEFAULT:       quay.io/podified-antelope-centos9/openstack-nova-novncproxy:current-podified
> >       NOVA_SCHEDULER_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-scheduler:current-podified
> >       NOVA_COMPUTE_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified
> >       NOVA_LIBVIRT_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-libvirt:current-podified
> >       NOVA_ANSIBLE_EE_IMAGE_URL_DEFAULT:  quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
> >       ENABLE_WEBHOOKS:                    false    <------- *** webhooks disabled ***
> >       WATCH_NAMESPACE:                    openstack
> >       OPERATOR_CONDITION_NAME:            openstack-operator.v0.0.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As a result, the `Nova` CR does not have its various `containerImage` fields populated and they are instead the empty-string.
> 
> Actually, this is proper. The webhooks should be turned off in the Nova controller-manager. I think this is a chicken-and-egg problem, however. While Nova controller-manager's webhooks should be disabled in the context of an OpenStack operator deployment (which this is), the OpenStack operator needs to have this version of Nova so that it can call the defaulting mechanism from within its own webhooks. My guess is that previous initial webhook PRs for other operators avoided this problem by happening to have the `containerImage`s set in the `OpenStackControlPlane` sample YAML [1] used by CI.
> 
> [1] https://github.com/openstack-k8s-operators/openstack-operator/blob/master/config/samples/core_v1beta1_openstackcontrolplane.yaml

I agree with your analysis. This is one of the example where testing nova-operator PR with the latest openstack-operator version does not really work as this nova-operator PR will only be compatible with openstack-operator after the webhook in openstack-operator is turned on. 

I think one way to solve this is to not remove the defaulting of the containerImage fields by kubebuilder in this PR to keep the compatibility with the openstack-operator. Then we can merge this PR with green CI. Then bump nova-operator version in openstack-operator and do the webhook integration in the same PR. Then a second nova-operator PR is needed to remove the kubebuilder defaulting from containerImages here.

An alternative solution could be to temporary merge a PR in openstack-operator where the nova part of the samples define the containerImage fields explicitly. And revert that after we did the webhook integration there.

2023-05-02 10:17 UTC, gibizer commented on pkg/common/env.go
> +}
I don't think we need to check `value != ""` if the ENV variable is set we get `ok==true`  if it is unset then we get `ok==false`.  If somebody explicitly set the ENV variable to "" then we are allowed to fail later if the explicitly set "" value is invalid.

2023-05-02 10:17 UTC, gibizer commented on pkg/common/env.go
> +// TODO: Move to lib-common?
Yepp, lets move it there. But it is OK to do that in a follow up

2023-05-02 10:17 UTC, gibizer commented on api/v1beta1/webhook_suite_test.go
> +/*
We can drop this whole file. The webhook is started by the test/functional/suite_test.go now.

2023-05-02 10:17 UTC, gibizer commented on test/functional/suite_test.go
> +	novav1.SetupNovaExternalComputeDefaults(novaExternalComputeDefaults)
This is now the same as in main.go so to avoid divergence of this setup between the test run and the production run, I suggest to pull it out to a common place.

2023-05-02 10:35 UTC, gibizer commented on config/samples/nova_v1beta1_nova_collapsed_cell.yaml
> +        containerImage: quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo
I think we should be able to drop these (here and below) from the samples now.

2023-05-02 10:35 UTC, gibizer commented on config/samples/nova_v1beta1_novacell0.yaml
> +    containerImage: quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo
I think it should work even if we leave the whole `conductorServiceTemplate` field out from the sample. If it does not work today that means we have yet another defaulting issue around this field in the template struct. I'm fine to investigate this in a separate PR.

2023-05-02 10:57 UTC, abays commented on Makefile
> +	NOVA_API_IMAGE_URL_DEFAULT=quay.io/tripleozedcentos9/openstack-nova-api:current-tripleo \
Updated to not need this

2023-05-02 10:57 UTC, abays commented on config/samples/nova_v1beta1_nova_collapsed_cell.yaml
> +        containerImage: quay.io/tripleozedcentos9/openstack-nova-conductor:current-tripleo
Ack, will try

2023-05-02 11:20 UTC, abays commented on main.go
> +	}
Understood.  If there are use cases where all the individual types could be created independently, then we should add webhooks for them.  I just started with `Nova`, `NovaCell` and `NovaExternalCompute` based on my current (limited) understanding.  I will do those in a follow-up PR.

2023-05-02 11:21 UTC, abays commented on pkg/common/env.go
> +}
Ack, will remove

2023-05-02 11:21 UTC, abays commented on test/functional/suite_test.go
> +	novav1.SetupNovaExternalComputeDefaults(novaExternalComputeDefaults)
Good suggestion.  I will do that.

2023-05-02 13:42 UTC, abays commented on api/v1beta1/nova_types.go
> +func NewNovaSpec(passwordSecretName string) NovaSpec {
Ack, will remove

2023-05-02 15:31 UTC, abays commented
> > > > @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > > > Test name 	Commit 	Details 	Required 	Rerun command
> > > > ci/prow/nova-operator-build-deploy 	[3685d00](https://github.com/openstack-k8s-operators/nova-operator/commit/3685d00dbc6de21411991060125e700cf52bf2d1) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_nova-operator/335/pull-ci-openstack-k8s-operators-nova-operator-master-nova-operator-build-deploy/1652957531942686720) 	false 	`/test nova-operator-build-deploy`
> > > > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=nova-operator&pr=335). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).
> > > 
> > > 
> > > This CI failure seems to be caused by something setting the webhooks to be disabled (this snippet is from the `nova-controller-manager` `describe` log):
> > > ```
> > > Environment:
> > >       NOVA_API_IMAGE_URL_DEFAULT:         quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
> > >       NOVA_CONDUCTOR_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-conductor:current-podified
> > >       NOVA_METADATA_IMAGE_URL_DEFAULT:    quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
> > >       NOVA_NOVNC_IMAGE_URL_DEFAULT:       quay.io/podified-antelope-centos9/openstack-nova-novncproxy:current-podified
> > >       NOVA_SCHEDULER_IMAGE_URL_DEFAULT:   quay.io/podified-antelope-centos9/openstack-nova-scheduler:current-podified
> > >       NOVA_COMPUTE_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified
> > >       NOVA_LIBVIRT_IMAGE_URL_DEFAULT:     quay.io/podified-antelope-centos9/openstack-nova-libvirt:current-podified
> > >       NOVA_ANSIBLE_EE_IMAGE_URL_DEFAULT:  quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
> > >       ENABLE_WEBHOOKS:                    false    <------- *** webhooks disabled ***
> > >       WATCH_NAMESPACE:                    openstack
> > >       OPERATOR_CONDITION_NAME:            openstack-operator.v0.0.1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > As a result, the `Nova` CR does not have its various `containerImage` fields populated and they are instead the empty-string.
> > 
> > 
> > Actually, this is proper. The webhooks should be turned off in the Nova controller-manager. I think this is a chicken-and-egg problem, however. While Nova controller-manager's webhooks should be disabled in the context of an OpenStack operator deployment (which this is), the OpenStack operator needs to have this version of Nova so that it can call the defaulting mechanism from within its own webhooks. My guess is that previous initial webhook PRs for other operators avoided this problem by happening to have the `containerImage`s set in the `OpenStackControlPlane` sample YAML [1] used by CI.
> > [1] https://github.com/openstack-k8s-operators/openstack-operator/blob/master/config/samples/core_v1beta1_openstackcontrolplane.yaml
> 
> I agree with your analysis. This is one of the example where testing nova-operator PR with the latest openstack-operator version does not really work as this nova-operator PR will only be compatible with openstack-operator after the webhook in openstack-operator is turned on.
> 
> I think one way to solve this is to not remove the defaulting of the containerImage fields by kubebuilder in this PR to keep the compatibility with the openstack-operator. Then we can merge this PR with green CI. Then bump nova-operator version in openstack-operator and do the webhook integration in the same PR. Then a second nova-operator PR is needed to remove the kubebuilder defaulting from containerImages here.
> 
> An alternative solution could be to temporary merge a PR in openstack-operator where the nova part of the samples define the containerImage fields explicitly. And revert that after we did the webhook integration there.

Okay, let's try keeping the `kubebuilder` defaults for now and then removing them in a follow-up.

2023-05-03 12:28 UTC, gibizer reviewed
This looks OK to me. We discussed with @abays that there will be follow ups:
* after the openstack-operator is using the nova-operator defaulting interface the kubebuilder defaults can be removed from nova-operator for containerImage fields
* separately, a followup can add webhooks for the sub CRs not handled today.

@SeanMooney do you have any open issues with this PR or can we land this now?

2023-05-05 08:16 UTC, SeanMooney commented on api/v1beta1/nova_webhook.go
> +// NovaDefaults -
ack

2023-05-05 08:21 UTC, SeanMooney approved these changes

2023-05-05 08:36 UTC, merged