Metadata multi cell
openstack-k8s-operators/nova-operator pull request #346
Opened 2023-04-26 13:34 UTC by mrKisaoLamb

Add support for multicell deployment

2023-05-03 13:38 UTC, gibizer requested changes
Overall looks good I have some minor comments inline.

Also I have an additional request to add a Nova sample file that deploys metadata. And a follow up request to do a validation so that nova-metadata is never requested to be deployed to cell0.

2023-05-03 13:38 UTC, gibizer commented on controllers/nova_controller.go
> +		return ctrl.Result{}, nil
you can drop this, so that we end up logging "Successfully reconciled" in both Replica==0 and !=0 cases.

2023-05-03 13:38 UTC, gibizer commented on controllers/novacell_controller.go
> +		return ctrl.Result{}, nil
ditto

2023-05-03 13:38 UTC, gibizer commented on controllers/novacell_controller.go
> +func (r *NovaCellReconciler) ensureMetadata(
how similar this to the ensureMetata in NovaReconciler? Can we pull out a common function?

2023-05-03 13:38 UTC, gibizer commented on controllers/novacell_controller.go
> +	metadataSpec := novav1.NewNovaMetadataSpec(instance.Spec)
I guess the main difference between the two ensureMetadata is what is the input we use for creating the metadataSpec.

2023-05-03 13:38 UTC, gibizer commented on test/functional/nova_metadata_controller_test.go
> +		It("generated config with correct local_metadata_per_cell", func() {
Please add more check to the name of the exposed service name, as that also depends on the CellName now.

2023-05-03 13:38 UTC, gibizer commented on controllers/novacell_controller.go
> +	if instance.Spec.MetadataServiceTemplate.Replicas != 0 {
I remember we discussed that we don't need nova-metadata service deployed to cell0 as there are never running instances in cell0 as there are no computes in cell0. I think we should simply reject the cell0Template in the validation webhook if it has a metadataTemplate with replicas > 0. As the webhook PR is still open (but I think close to merge) this needs to be done in a follow up after the webhook PR lands.

2023-05-09 14:29 UTC, mrKisaoLamb commented on controllers/novacell_controller.go
> +		return ctrl.Result{}, nil
Done

2023-05-09 14:30 UTC, mrKisaoLamb commented on controllers/novacell_controller.go
> +	metadataSpec := novav1.NewNovaMetadataSpec(instance.Spec)
Yes and because this difference it's hard to find good type to valid what we use there, using interface and cases make code overcomplicated IMO

2023-05-15 14:23 UTC, gibizer reviewed
My only currently actionable comment is about mixing collapsed cell setup and metadata per cell in the test case.

2023-05-15 14:23 UTC, gibizer commented on controllers/nova_controller.go
> +		instance.Status.Conditions.Remove(novav1.NovaMetadataReadyCondition)
This looks OK. We are only saving the instance in the deferred function at the end of Reconcile. So even though we add NovaMetadataReadyCondition at the start and removing it here, this is not visible to the outside word as we only save the conditions after this point.

2023-05-15 14:23 UTC, gibizer commented on controllers/novacell_controller.go
> +	if *instance.Spec.MetadataServiceTemplate.Replicas != 0 && instance.Spec.CellName != Cell0Name {
if we already rejecting MetadataServiceTemplate.Replicas != 0 for cell0 in the validation hook, then the extra check `instance.Spec.CellName != Cell0Name` here is not necessary.

2023-05-15 14:23 UTC, gibizer commented on controllers/novacell_controller.go
> +	metadataSpec := novav1.NewNovaMetadataSpec(instance.Spec)
OK. I guess we can maintain this 50 lines here and in the nova_controller. No worries.

2023-05-15 14:23 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			}
You copied here the setup for collapsed cells from above. I think you don't need such complication here to test the metadata per cell setup.

2023-05-15 14:23 UTC, gibizer commented on controllers/novacell_controller.go
> +	if *instance.Spec.MetadataServiceTemplate.Replicas != 0 && instance.Spec.CellName != Cell0Name {
//later
I see we haven't added this to the validation hook. So the check here is OK. But I suggest to do a follow up where we reject cell0 metadata from the validation webhook.

2023-05-16 10:13 UTC, mrKisaoLamb commented on test/functional/nova_multicell_test.go
> +			}
Done, 2a7d74b9df71524bcea48ab779f1d53d3c97de11

2023-05-16 10:33 UTC, gibizer approved these changes
looks good

2023-05-16 10:33 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +				"replicas": 1,
OK, so this gets ignored. And later on this will be rejected by the validation webhook. Cool

2023-05-16 10:33 UTC, gibizer approved these changes
looks good

2023-05-16 10:36 UTC, merged