PoC: Use dataplane extraMounts
openstack-k8s-operators/nova-operator pull request #374
Opened 2023-05-16 17:23 UTC by fao89

Currently, we pass the inventory configmap name and the ssh secret name  to mount AEE, we could get the extraMounts from dataplane instead. It would allow store the logs when dataplane.extraMounts is set

https://openstack-k8s-operators.github.io/openstack-ansibleee-operator/logs/ 

https://github.com/openstack-k8s-operators/install_yamls/pull/271

2023-05-16 18:52 UTC, SeanMooney commented
im not entirely convicne this is the right approach

we could leverage 
https://openstack-k8s-operators.github.io/openstack-ansibleee-operator/logs/
to get logs but i don't agree that we should use ExtraMounts []storage.VolMounts ` on the NovaExternalCompute CRD for this.

i want to reserve ExtraMounts for future use to mount additional volume to the nova-compute and or libvirt container not the AEE

2023-05-16 18:53 UTC, SeanMooney requested changes

2023-05-16 18:53 UTC, SeanMooney commented on controllers/novaexternalcompute_controller.go
> -	// mount ssh keys
i think we shoudl continue to generate the mounts like this and not take them form the dataplane operator but we can append the mounts required for logging.

2023-05-16 18:53 UTC, SeanMooney commented on api/v1beta1/novaexternalcompute_types.go
> +	ExtraMounts []storage.VolMounts `json:"extraMounts"`
this is not what we want extra mounts on the nova external compute to be used for

we want to keep this for additional mounts to the libvirt/nova-compute container

2023-05-17 12:05 UTC, fao89 commented
https://github.com/openstack-k8s-operators/install_yamls/pull/271#issuecomment-1550417446

2023-05-17 12:05 UTC, closed without merging