[WIP][noVNCProxy] Add basic reconciler and templates
openstack-k8s-operators/nova-operator pull request #376
Opened 2023-05-19 13:26 UTC by mrKisaoLamb

2023-05-26 12:15 UTC, gibizer commented
/test nova-operator-build-deploy-tempest

The failed test case `tempest.api.compute.admin.test_networks.NetworksTest.test_list_all_networks` has known issues and being fixed in https://review.opendev.org/c/openstack/tempest/+/883892

2023-05-26 13:19 UTC, gibizer requested changes
I haven't looked at the test code yet but left some comments inline for the controller code.

2023-05-26 13:19 UTC, gibizer commented on controllers/novanovncproxy_controller.go
> +		"transport_url":               "",
We need to fill this with the transport_url of the cell this proxy is running in. The proxy needs to call down to the computes in this cell

2023-05-26 13:19 UTC, gibizer commented on test/functional/suite_test.go
> +		Name:      uuid.New().String()[:30],
I would add a comment here:
```golang
// We need to limit the lenght of the name of the Nova CR as the operator generates names 
// for the sub CRs from this name as a prefix. 
// E.g. <nova-CR-name>-<cell name>-metadata-internal 
// K8s limits the name of a CR to 63 chars so we can easily hit that limit with uuids as names
// here.
```

2023-05-26 14:31 UTC, gibizer commented on api/v1beta1/novanovncproxy_types.go
> +			NetworkAttachments:     novaCell.MetadataServiceTemplate.NetworkAttachments,
This causes that if I try to deploy with the default openstackcontrolplane sample then I get 0 NovaNoVNCProxy's as metadata.replicas in cell is 0. :)

2023-05-26 14:37 UTC, gibizer commented
I tried to deploy this in crc. 

I had to set cell1 metadata replicas to 1 to trigger novnc deployment due to the bug https://github.com/openstack-k8s-operators/nova-operator/pull/376#discussion_r1206703241 

Then I see that the novnc statefulset is failed

```
$ oc describe statefulset nova-cell1-novncproxy | grep Events: -A 20
Events:
  Type     Reason        Age                     From                    Message
  ----     ------        ----                    ----                    -------
  Warning  FailedCreate  3m45s (x18 over 9m13s)  statefulset-controller  create Pod nova-cell1-novncproxy-0 in StatefulSet nova-cell1-novncproxy failed error: pods "nova-cell1-novncproxy-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000680000, 1000689999], spec.containers[1].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000680000, 1000689999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "hostpath-provisioner": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

2023-05-26 15:11 UTC, gibizer commented on pkg/novncproxy/deployment.go
> +				Spec: corev1.PodSpec{
the service account issue probably due to missing service account here. E.g. https://github.com/openstack-k8s-operators/nova-operator/blob/a274e18fdceadc3bd4646d29fd9914d64ad18773/pkg/novametadata/deployment.go#L123

2023-06-06 07:48 UTC, mrKisaoLamb commented on api/v1beta1/novanovncproxy_types.go
> +	APIEndpoints map[string]string `json:"apiEndpoint,omitempty"`
Now yes, for config generation (previously it wasn't used)

2023-06-06 07:48 UTC, mrKisaoLamb commented on pkg/novncproxy/deployment.go
> +				Spec: corev1.PodSpec{
Thanks! Done

2023-06-06 07:48 UTC, mrKisaoLamb commented on test/functional/suite_test.go
> +		Name:      uuid.New().String()[:30],
Done, thanks!

2023-06-08 12:06 UTC, gibizer requested changes

2023-06-08 12:06 UTC, gibizer commented on controllers/novacell_controller.go
> +	op, err := controllerutil.CreateOrPatch(ctx, r.Client, novncproxy, func() error {
The cell controller's Ready state depends on the Ready state of the novncproxy CR therefore this controller needs to declare `Owns(&novav1.NovaNoVNCProxy{}).` below to get notified when that CR changes. This caused the strange test failure.

2023-06-12 10:07 UTC, SeanMooney commented on api/v1beta1/novanovncproxy_types.go
> +	APIEndpoints map[string]string `json:"apiEndpoint,omitempty"`
i dont think we should be adding this to the status.

the nova-operator should not need to ever read form the status field.

2023-06-12 11:43 UTC, SeanMooney requested changes
i dont really see much that needs to be resolved before we can merge this.

gibi's comment regarding the owns relationship between the cell and the vnc proxy is the main issue.

there are some things that could be clean up later and some hardening of the test case but i dont think that really blocks this merging

2023-06-12 11:43 UTC, SeanMooney commented on pkg/novncproxy/deployment.go
> +		}
ack, hitting the web ui endpoint makes sense

2023-06-12 11:43 UTC, SeanMooney commented on controllers/novanovncproxy_controller.go
> +		"novncproxy_base_url":         instance.Status.APIEndpoints["public"],
you should not be reading form the status filed you should be getting this form the route.

2023-06-12 11:43 UTC, SeanMooney commented on test/functional/nova_novncproxy_test.go
> +			spec["customServiceConfig"] = "foo=bar"
a "standard" spec would not have custom config defined

you shoudl really just assert the default spec behavior first

2023-06-12 11:43 UTC, SeanMooney commented on test/functional/nova_novncproxy_test.go
> +	When("with standard spec without network interface", func() {
When("created with a default spec without network interface", func() {

2023-06-12 11:43 UTC, SeanMooney commented on test/functional/nova_novncproxy_test.go
> +	When("with standard spec without network interface", func() {
is this when needed by the way can the before each just go a the top of the describe?

2023-06-12 11:43 UTC, SeanMooney commented on test/functional/nova_novncproxy_test.go
> +				th.ExpectCondition(
you could use ExepectCondtionWithDetails?, i think that is the function name,  to assert the message

2023-06-12 11:43 UTC, SeanMooney commented on test/functional/nova_novncproxy_test.go
> +			It("reports that the inputs are not ready", func() {
it shouls also say why its not ready so again this is a good case to not just expect the condtion but also assert the reason

2023-06-12 11:43 UTC, SeanMooney commented on test/functional/nova_novncproxy_test.go
> +					HaveKeyWithValue("02-nova-override.conf", "foo=bar"))
i would pull this out into its own test personally but this also works

i slightly dislink asserting that invlaid config is present but on the other hand
we are not really ment to be inpseciting it.

if its not clear why this is invilaid, conf formant and i think ini requrie all keys to be in a section
so "foo=bar" is not valid as its not in a section.

2023-06-12 11:43 UTC, SeanMooney commented on test/functional/novaexternalcompute_controller_test.go
> +		k8sClient.Delete, ctx, CreateNovaNoVNCProxySecret(cell.CellName.Namespace, SecretName))
this will work but we proably should have a geneic CreateNovaCellSecret

we shoudl not really be reusing the service specific ones here.

Thats an existing issue not a new one added by your change

2023-06-14 14:20 UTC, mrKisaoLamb commented on api/v1beta1/novanovncproxy_types.go
> +			NetworkAttachments:     novaCell.MetadataServiceTemplate.NetworkAttachments,
done, 158ae6cfb8b448dadb25bc1f880f02f9b9b6435e

2023-06-14 14:20 UTC, mrKisaoLamb commented on controllers/novacell_controller.go
> +	op, err := controllerutil.CreateOrPatch(ctx, r.Client, novncproxy, func() error {
done, 158ae6cfb8b448dadb25bc1f880f02f9b9b6435e

2023-06-14 14:20 UTC, mrKisaoLamb commented on api/v1beta1/novanovncproxy_types.go
> +	APIMessageBusSecretName string `json:"apiMessageBusSecretName"`
done, 158ae6cfb8b448dadb25bc1f880f02f9b9b6435e

2023-06-14 14:20 UTC, mrKisaoLamb commented on controllers/novanovncproxy_controller.go
> +		"transport_url":               string(apiMessageBusSecret.Data["transport_url"]),
done, 158ae6cfb8b448dadb25bc1f880f02f9b9b6435e

2023-06-14 14:21 UTC, mrKisaoLamb commented on test/functional/nova_novncproxy_test.go
> +	When("with standard spec without network interface", func() {
Unfortunatly last test in this 'describe' have separate before so we can make it global only if we move that test outside

2023-06-14 14:21 UTC, mrKisaoLamb commented on test/functional/nova_novncproxy_test.go
> +				th.ExpectCondition(
done, 158ae6cfb8b448dadb25bc1f880f02f9b9b6435e

2023-06-14 14:21 UTC, mrKisaoLamb commented on test/functional/nova_novncproxy_test.go
> +			It("reports that the inputs are not ready", func() {
done 158ae6cfb8b448dadb25bc1f880f02f9b9b6435e

2023-06-15 13:37 UTC, mrKisaoLamb commented on api/v1beta1/novanovncproxy_types.go
> +	APIEndpoints map[string]string `json:"apiEndpoint,omitempty"`
Removed, done 7379e8d2f30a25b547b31404959768d8ff10efb8

2023-06-15 13:37 UTC, mrKisaoLamb commented on controllers/novanovncproxy_controller.go
> +		"transport_url":               "",
Done

2023-06-16 15:57 UTC, SeanMooney commented
i was wondering why i could not checkout this pr

you didn not create this in your fork you pushed the branch directly to 
https://github.com/openstack-k8s-operators/nova-operator
which you should never do.

this should be recreated using you own fork of the repo

2023-06-22 14:15 UTC, mrKisaoLamb commented on test/functional/novaexternalcompute_controller_test.go
> +		k8sClient.Delete, ctx, CreateNovaNoVNCProxySecret(cell.CellName.Namespace, SecretName))
done

2023-06-22 14:22 UTC, mrKisaoLamb commented
> i was wondering why i could not checkout this pr
> 
> you didn not create this in your fork you pushed the branch directly to https://github.com/openstack-k8s-operators/nova-operator which you should never do.
> 
> this should be recreated using you own fork of the repo

Sorry for that, force of habbit from previous project that I worked on . I  recreated the pull request (PR) at https://github.com/openstack-k8s-operators/nova-operator/pull/414. However, for now, I will keep both the original PR and the new one open to preserve the discussion history.  I will create future PRs from my fork

2023-06-23 11:51 UTC, mrKisaoLamb commented
/retest

2023-06-28 14:15 UTC, gibizer commented
this feature is merged as #414

2023-06-28 14:15 UTC, closed without merging