update ceph bind mounts
openstack-k8s-operators/nova-operator pull request #383
Opened 2023-05-25 12:32 UTC by SeanMooney

This change ensure we nolonger do a direct passthough of the hosts
/etc/ceph and instead bind it to a read only location and copy
the files with updated permissions to /etc/ceph in the container.

This change is applied to teh nova_compute and libvirt_virtqemud
containers.

Closes: OSPRH-209
Signed-off-by: Sean Mooney <work@seanmooney.info>

2023-05-25 13:03 UTC, gibizer approved these changes
Looks good

2023-05-25 13:04 UTC, gibizer commented
@fultonj feel free to approve it once it looks good to you. For me it is OK to land.,

2023-05-25 13:07 UTC, fultonj commented
> @fultonj feel free to approve it once it looks good to you. For me it is OK to land.,

ack! testing this change

2023-05-26 13:47 UTC, fultonj requested changes

2023-05-26 14:37 UTC, fultonj approved these changes
/lgtm

2023-05-26 14:42 UTC, merged