Added playbook to install meta operator
openstack-k8s-operators/nova-operator pull request #400
Opened 2023-06-05 14:48 UTC by raukadah

https://github.com/openstack-k8s-operators/ci-framework/pull/201 changes the parent from base-crc to base-simple-crc.

base-simple-crc job will provide an crc based openshift cluster. It lacks the meta operator installation bits which breaks the existing job.

https://github.com/openstack-k8s-operators/ci-framework/pull/245 refines the cifmw-base-crc-openstack job and moves the ci-framework pre playbooks in pre-run and collect-logs in post-run playbook. It will help to drop the existing collect-logs.yaml playbook.

In order to fix the job, It uses install_yamls_make role to install meta operator.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/245

2023-06-06 10:29 UTC, SeanMooney commented
we could probably proceed with this once the ci issues are addressed

I actually have already started working on the same change but in a different way https://github.com/openstack-k8s-operators/nova-operator/compare/main...SeanMooney:nova-operator:zuul-jobs-part-2

effectively i was trying to figure out how to install the meta operator without install_yamls but i still need to figure out some of the network isolation bits.

2023-06-06 15:52 UTC, SeanMooney requested changes

2023-06-06 15:52 UTC, SeanMooney commented on ci/nova-operator-base/playbooks/install_meta_operators.yaml
> +
we need to add the addtional interface to CRC before we do make OpenStack

that is why its failing waiting for enp6s0

2023-06-06 15:52 UTC, SeanMooney commented on ci/nova-operator-base/playbooks/pre.yaml
> +        export ANSIBLE_CONFIG={{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/ansible.cfg
export ANSIBLE_CONFIG={{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/ansible.cfg

can be

export ANSIBLE_CONFIG={{ ci_framework_basedir }}/ansible.cfg

2023-06-06 15:52 UTC, SeanMooney commented on ci/nova-operator-base/playbooks/pre.yaml
> +        ansible-playbook install_meta_operators.yaml -e ci_framework_basedir={{ ci_framework_basedir }}
in generall i dont really like the pattern of invoking a playbook via a shell like this.

this feels like an anisble anti pattern to me 

i would prefer to do an import

- name: Install meta operator
  ansible.builtin.import_playbook: { nova_operator_basedir }}/ci/nova-operator-base/playbooks/install_meta_operators.yaml

or 

just add install_meta_operators.yaml as a pre-run playbook to the nova-base job

2023-06-07 05:34 UTC, raukadah commented on ci/nova-operator-base/playbooks/install_meta_operators.yaml
> +
Done

2023-06-07 05:35 UTC, raukadah commented on ci/nova-operator-base/playbooks/pre.yaml
> +        ansible-playbook install_meta_operators.yaml -e ci_framework_basedir={{ ci_framework_basedir }}
Thank you @SeanMooney for the review, I will address in the upcoming patch updates.

2023-06-07 07:33 UTC, raukadah commented
@SeanMooney Thank you for the valuable comment. I am moving this to draft till it ready for review.

2023-06-07 13:14 UTC, raukadah commented
recheck

2023-06-08 13:08 UTC, SeanMooney commented on .zuul.yaml
> +      - github.com/openstack-k8s-operators/ci-framework
ah so this was previosuly a required project in the parent job but now its not ya that makes sesnes.

2023-06-08 13:09 UTC, SeanMooney commented on .zuul.yaml
> +      - github.com/openstack-k8s-operators/ci-framework
you might want to adrees the zuul job issue by 
adding cifmw_basedir to the vars section below

2023-06-08 16:07 UTC, raukadah commented on .zuul.yaml
> +      - github.com/openstack-k8s-operators/ci-framework
Done

2023-06-08 16:07 UTC, raukadah commented on ci/nova-operator-base/playbooks/install_meta_operators.yaml
> +
Done

2023-06-08 16:14 UTC, raukadah commented
Thank you @SeanMooney for all those suggestions. I have added them and now it is failing with [following error](https://review.rdoproject.org/zuul/build/40f28303dcf54aed808dfbd55b75e903/log/job-output.txt#686)
```
ERROR! couldn't resolve module/action 'get_makefiles_env'. This often indicates a misspelling, missing collection, or incorrect module path.
```

It is expected because there is no way to tell zuul to discover[ these action plugins and modules](https://github.com/openstack-k8s-operators/ci-framework/tree/main/ci_framework/plugins/modules).

`[get_makefiles_env](https://github.com/openstack-k8s-operators/ci-framework/blob/main/ci_framework/plugins/modules/get_makefiles_env.py)` is used to the env file from install_yamls and [generate_make_tasks](https://github.com/openstack-k8s-operators/ci-framework/blob/main/ci_framework/plugins/modules/generate_make_tasks.py ) generates the install_yamls_makes roles with all make target task files.

In order to fix that in ci-framework, we went with nested ansible-playbook call approach with shell (which is not ansible way).

2023-06-08 16:43 UTC, SeanMooney commented
you likely need to follow https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#adding-standalone-local-modules-for-all-playbooks-and-roles

2023-06-08 16:48 UTC, SeanMooney commented
you might be able to do somethign like this when invoking the role

env:
 ANSIBLE_LIBRARY: "${ANSIBLE_LIBRARY}:~/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/plugins/modules"

2023-06-12 08:12 UTC, raukadah commented
recheck

2023-06-12 09:58 UTC, SeanMooney commented on ci/nova-operator-base/playbooks/install_meta_operators.yaml
> +    ANSIBLE_ROLES_PATH: "~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
this wont work you removed all the zuul roles from the roles path.

so it wont be able to find install_yamls_makes

2023-06-12 13:44 UTC, raukadah commented
recheck

2023-06-15 09:28 UTC, raukadah commented
@SeanMooney I have applied all the above suggestion and passed ansible_library and roles_path via environment . But I am still hitting the [same issue](https://logserver.rdoproject.org/00/400/594bf348b412fdc9202189c514aab9faecd9c31f/github-check/nova-operator-compute-kit/0ed9b6e/job-output.txt).
```
TASK [Generate install_yamls_make role name=install_yamls] *********************
2023-06-15 08:47:30.879701 | ERROR! couldn't resolve module/action 'get_makefiles_env'. This often indicates a misspelling, missing collection, or incorrect module path.
2023-06-15 08:47:30.879706 | 
2023-06-15 08:47:30.879710 | The error appears to be in '/var/lib/zuul/builds/0ed9b6ef11d44f5cab26ffdf71894e09/untrusted/project_0/github.com/openstack-k8s-operators/ci-framework/ci_framework/roles/install_yamls/tasks/main.yml': line 27, column 3, but may
2023-06-15 08:47:30.879718 | be elsewhere in the file depending on the exact syntax problem.
2023-06-15 08:47:30.879723 | 
2023-06-15 08:47:30.879729 | The offending line appears to be:
2023-06-15 08:47:30.879734 | 
```
Zuul is not able to discover the ansible modules.Please have a look.
I think we should go with calling ansible-playbook via shell (It is not a ansible thing, but it works).

2023-06-15 10:42 UTC, SeanMooney commented
ya i think for now we can go back to calling it via the shell.

this code might get reworked/removed in the future and you have given a decent effort of getting this to work without the sub shell so lets move this forward with the working solution and we can revisit this again later.

2023-12-22 15:28 UTC, SeanMooney commented
this si no longer required so closing to clean up the stale prs

2023-12-22 15:28 UTC, closed without merging