Validate lenght of cell name
openstack-k8s-operators/nova-operator pull request #402
Opened 2023-06-06 14:24 UTC by mrKisaoLamb

We need to limit the lenght of the name of the nova-cell as the operator generates names for the sub CRs from this name as a prefix. E.g. <nova-CR-name>-<cell name>-metadata-internal
K8s limits the name of a CR to 63 chars.

2023-06-07 11:56 UTC, bogdando commented on test/functional/suite_test.go
> +		Name:      uuid.New().String()[:25],
why 25? shouldn't it be 35?

2023-06-14 14:12 UTC, mrKisaoLamb commented on test/functional/suite_test.go
> +		Name:      uuid.New().String()[:25],
This namespace limit applies to the novaName and not the cellName. If we set this limit to 35, it will cause failures in tests that involve the cell because we add additional letters when creating the cellName.

2023-06-15 13:28 UTC, SeanMooney requested changes

2023-06-15 13:57 UTC, mrKisaoLamb commented on api/v1beta1/novacell_webhook.go
> +		return field.Forbidden(field.NewPath("spec").Child("CellName"), "should be shorter than 35 signs")
thanks, done!

2023-06-15 14:00 UTC, SeanMooney approved these changes

2023-06-15 15:23 UTC, mrKisaoLamb commented
/retest-required

2023-06-16 06:28 UTC, mrKisaoLamb commented
/retest

2023-06-16 11:38 UTC, SeanMooney approved these changes
ah yes the ensure secret change has merged hence the rebase

still looks good to me

2023-06-16 11:42 UTC, merged