[testenv] Address novaNames replacements on todo
openstack-k8s-operators/nova-operator pull request #421
Opened 2023-06-26 13:59 UTC by bogdando

Use novaNames and cellXNames for other places from the todo list.

2023-06-29 09:45 UTC, mrKisaoLamb requested changes
small comment and need rebase. Except that lgtm

2023-06-29 09:45 UTC, mrKisaoLamb commented on test/functional/base_test.go
> +	AdminNovaRouteName      types.NamespacedName
this also can be removed

2023-06-29 12:26 UTC, gibizer reviewed
good direction. I think we can easily land this after the conflict is resolved.

2023-07-03 12:38 UTC, mrKisaoLamb reviewed
I rebase and IMO can be merged

2023-07-04 12:59 UTC, gibizer approved these changes
Looks good.

2023-07-04 13:17 UTC, merged