Remove NovaExternalCompute CRD
openstack-k8s-operators/nova-operator pull request #476
Opened 2023-07-26 12:24 UTC by gibizer

We are removing the support for deploying nova-compute on EDPM nodes
from nova-operator directly. The nova-compute deployment will be handled
by the dataplane-operator and nova-operator only generates config for it
implemented in https://github.com/openstack-k8s-operators/nova-operator/pull/452

Depends-on: #452

2023-08-16 18:29 UTC, SeanMooney requested changes
ok so this is almost correct.
this should also delete teh playbook dir

https://github.com/openstack-k8s-operators/nova-operator/tree/main/playbooks

other then that this looks good to me

2023-08-17 13:26 UTC, gibizer commented
> ok so this is almost correct. this should also delete teh playbook dir
> 
> https://github.com/openstack-k8s-operators/nova-operator/tree/main/playbooks
> 
> other then that this looks good to me

Good point. Done.

2023-08-17 13:33 UTC, SeanMooney approved these changes

2023-08-17 14:04 UTC, SeanMooney approved these changes
good catch i forgot we included the playbooks in the docker image

2023-08-17 14:49 UTC, merged