[ironic-compute] Add nova-compute-ironic controller
openstack-k8s-operators/nova-operator pull request #477
Opened 2023-07-26 13:52 UTC by mrKisaoLamb

2023-07-27 13:58 UTC, gibizer requested changes

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/conditions.go
> +	// NovaComputeIronicReadyCondition indicates when the given NoVNCProxy instance is Ready
copy paste: NoVNCProxy

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/conditions.go
> +	NovaComputeIronicReadyCondition condition.Type = "NovaComputeIronicReady"
Wondering if we want a separate condition type per virt driver. But this depends on if we create a specific NovaComputeIronic instead of a generic NovaCompute with a virt driver field. (see my specific comment below)

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/novacomputeironic_types.go
> +	ExternalEndpoints []MetalLBConfig `json:"externalEndpoints,omitempty"`
I don't think we need to externally expose anything from the compute service

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/novacomputeironic_types.go
> +	ExternalEndpoints []MetalLBConfig `json:"externalEndpoints,omitempty"`
I don't think we need to externally expose anything from the compute service

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	ComputeDriver string `json:"computeDriver"`
hm hm. I thought we wanted to add the ComputeDriver to the NovaCompute(Ironic)Template to select from Ironic and Fake drivers.

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	NovaComputeIronicServiceTemplate NovaComputeIronicTemplate `json:"novaComputeIronicServiceTemplate"`
I thought we wanted to allow multiple instances of the compute in the cell. @SeanMooney am I correct that for compute with Ironic virt driver we want to keep the replicas to 0-1 and allow adding more than one NovaCompute(Ironic)ServiceTemplate to the Cell instead? 
For fake driver we might want to support both increasing the replica count and therefore having more but identically configured fake computes, as well as adding more NovaCompute(Ironic)ServiceTemplate instances to support differently configured computes in a same cell.

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	// NovaComputeIronicServiceTemplate - defines the novvncproxy service dedicated for
copy paste: novvncpoxy

2023-07-27 13:58 UTC, gibizer commented on api/v1beta1/novacomputeironic_types.go
> +	Replicas *int32 `json:"replicas"`
If we go with the specific NovaComputeIronicTemplate then this should be maximum of 1. If we go with a generic NovaComputeTemplate then the current Replicas definition is OK, but we need a validation  webhook that reject replicas > 1 for NovaComputeTemplate with virt driver == ironic while allows it for virt driver == fake.

2023-07-27 13:59 UTC, gibizer commented
I only looked at the CRD definitions so far but I think we need to discuss this a bit further.

2023-08-04 14:33 UTC, SeanMooney commented on api/v1beta1/novacompute_types.go
> +	// +kubebuilder:default="ironic.IronicDriver"
i would prefer to remove the default and make this required

2023-08-04 14:33 UTC, SeanMooney commented on api/v1beta1/novacompute_types.go
> +	ComputeDriver string `json:"computeDriver"`
same here

2023-08-04 14:33 UTC, SeanMooney commented on api/v1beta1/novacompute_webhook.go
> +}
we need to validat that replica is 1 if the compute driver is ironic

2023-08-04 14:33 UTC, SeanMooney commented on api/v1beta1/common_types.go
> +	NovaIronicComputeContainerImage = "quay.io/podified-antelope-centos9/openstack-nova-compute-ironic:current-podified"
we do not need a seperate container for ironic.

looking at 
https://github.com/openstack-k8s-operators/tcib/blob/main/container-images/tcib/base/os/nova-base/nova-compute-ironic/nova-compute-ironic.yaml

everything that is required is in 
https://github.com/openstack-k8s-operators/tcib/blob/main/container-images/tcib/base/os/nova-base/nova-compute/nova-compute.yaml

2023-08-08 14:18 UTC, mrKisaoLamb commented on api/v1beta1/novacomputeironic_types.go
> +type NovaComputeIronicTemplate struct {
Added generic template

2023-08-08 14:18 UTC, mrKisaoLamb commented on api/v1beta1/novacompute_types.go
> +	// +kubebuilder:default="ironic.IronicDriver"
done, 9e5fe712f3d0fb2ece9a389b80b83ffa1334827c

2023-08-21 09:46 UTC, gibizer commented on api/v1beta1/common_types.go
> +	NovaIronicComputeContainerImage = "quay.io/podified-antelope-centos9/openstack-nova-compute-ironic:current-podified"
The removal of the NovaExternalCompute is merged and I removed the images there. So I think we are good here after the necessary rebase.

2023-08-21 10:38 UTC, gibizer reviewed
I re-reviewed the API definition part. It looks better. I still have some comments but the overall direction is OK to me. I still have to look at the implementation and the test later

2023-08-21 10:38 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	// List of nova computes with selected drivers
I don't fully understand this field def. The documentation says it is a list but actually it is a map. Also it does not define what is the key of  the map. At least the doc needs to be improved so the user understands how to use this field.

nit: please follow the documentation pattern. The doc text of the field should start with the name of the field documented.

2023-08-21 10:38 UTC, gibizer commented on api/v1beta1/common_types.go
> +	AnsibleEEContainerImage         = "quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest"
This is one of the merge conflict caused by the removal of NovaExternalCompute.

2023-08-21 10:38 UTC, gibizer commented on api/v1beta1/common_types.go
> +		NovaIronicComputeContainerImageURL: util.GetEnvVar("NOVA_IRONIC_COMPUTE_IMAGE_URL_DEFAULT", NovaIronicComputeContainerImage),
L167, L184, and L230 shows a duplication of logic. As the rest of the image URL field initialization is also duplicated I'm OK the follow that pattern here. But I think we should be able to deduplicate this in a separate PR. 
// later
I realized that the propagation of this value is also seems to be duplicated between the top level and the cell level.

2023-08-21 10:38 UTC, gibizer commented on api/v1beta1/novacell_webhook.go
> +		for _, computeTemplate := range r.NovaComputeTemplates{
I think we can simply this and drop the condition. If the templates map is empty then the iteration will be a noop anyhow. 
Do we need to handle if NovaComputeTemplate is nil?

2023-08-21 10:38 UTC, gibizer commented on api/v1beta1/novacompute_types.go
> +	ComputeDriver string `json:"computeDriver"`
I think in most of the production cases the user wants to use Ironic. So to help the user we can make this field optional with an Ironic default. @SeanMooney How do you feel about it?

2023-08-21 10:38 UTC, gibizer commented on api/v1beta1/novacompute_types.go
> +// NewNovaComputeSpec constructs a NovaMetadataSpec
nit: copy paste NovaMetadataSpec

2023-08-21 10:38 UTC, gibizer commented on api/v1beta1/novacompute_webhook.go
> +}
It is a bit more complicated than that. We have the validation wired up on the Template (see the webhook for the cell). It is again depends on if we allow the user to create a standalone NovaCompute CR. If yes, then we need input validation on the Spec here, if no, then the validation on the template is enough. I'm not sure about the pattern we have here.

2023-09-05 13:10 UTC, mrKisaoLamb commented on api/v1beta1/novacompute_webhook.go
> +}
done

2023-09-05 13:10 UTC, mrKisaoLamb commented on api/v1beta1/novacompute_types.go
> +	ExternalEndpoints []MetalLBConfig `json:"externalEndpoints,omitempty"`
done

2023-09-05 13:11 UTC, mrKisaoLamb commented on api/v1beta1/novacell_webhook.go
> +		for _, computeTemplate := range r.NovaComputeTemplates{
done

2023-09-05 13:11 UTC, mrKisaoLamb commented on api/v1beta1/novacompute_types.go
> +// NewNovaComputeSpec constructs a NovaMetadataSpec
done

2023-09-05 13:11 UTC, mrKisaoLamb commented on config/default/manager_default_images.yaml
> +        - name: NOVA_IRONIC_COMPUTE_IMAGE_URL_DEFAULT
done

2023-09-05 13:13 UTC, mrKisaoLamb commented on api/v1beta1/novacell_types.go
> +	// List of nova computes with selected drivers
done, this is now really the map and it use keys in compute name

2023-09-05 13:13 UTC, mrKisaoLamb commented on api/v1beta1/novacompute_types.go
> +	// CellName is the name of the Nova Cell this novncproxy belongs to.
done

2023-09-05 13:19 UTC, mrKisaoLamb commented on controllers/novacell_controller.go
> +				novav1.NovaComputeReadyCondition,
change name to 'NovaAllCompusteReadyCondition' and status is map of status per compute node

2023-09-05 13:19 UTC, mrKisaoLamb commented on controllers/novacell_controller.go
> +		instance.Status.Conditions.Remove(novav1.NovaComputeReadyCondition)
done, applied same schema here

2023-09-05 13:19 UTC, mrKisaoLamb commented on controllers/novacell_controller.go
> +	instance.Status.NovaComputeReadyCount = novacompute.Status.ReadyCount
done removed this one

2023-09-05 13:20 UTC, mrKisaoLamb commented on controllers/novacell_controller.go
> +		instance.Status.Conditions.Set(c)
done, moved

2023-09-12 11:34 UTC, gibizer reviewed
We are moving to the right direction. I have couple comments on the CRD, validation, and condition handling. I haven't reviewed the test coverage yet but I like the fact that it is green.

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +	for computeName, computeTemplate := range instance.Spec.NovaComputeTemplates {
I think we can move this whole section before 
`if cellHasVNCService && !instance.Status.Conditions.IsTrue(novav1.NovaNoVNCProxyReadyCondition)`
so that the ironic compute deployment can progress in parallel with the NovaNoVNCProxy deployment to generate the compute config for the EDPM computes.

This will only be relevant for cells with mixed ironic and libvirt computes as for pure ironic cells NovaNoVNCProxy would not be deployed (if the human deployer is smart enough) as ironic does not support vnc proxy.

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +			instance.Status.NovaComputesStatuses[computeName] = true
I think at this point you only want to add the key to the status map, but with bool = false.
We have to model 3 states:
1. compute CR is created but not mapped (`nova-manage cell_v2 discover_hosts` isn't run): the key exists but with value false
2. compute CR is created and mapped: the key exists and the value is true
3. compute CR does not exist: the key does not exists

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +	return types.NamespacedName{Namespace: instance.GetNamespace(), Name: instance.GetName() + "-" + computeName + "-compute"}
We need to limit computeName in the API with a validation to avoid generating a too long CR name here.

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +			h, "NovaCompute is disabled, but there is a "+
"NovaCompute isn't defined in the cell, but there is a "

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +		h, "NovaCompute is disabled, so deleted NovaCompute",
"NovaCompute isn't defined in the cell...

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +	computeNovaName := getNovaComputeName(instance, computeName)
supernit: I liked the `fullComputeName` local variable name in the delete function :)

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +			"NovaCompute is enabled, but there is a "+
NovaCompute is defined in the cell,

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +		instance.Status.Conditions.Set(condition.FalseCondition(
ensureNovaCompute is called in a loop for each compute defined, so if two those calls fails then the second overrides the condition set by the first call. If you want to have a single condition for a list of computes then you have to aggregate the result of the ensureNovaCompute calls and set the aggregated result to the condition.

2023-09-12 11:34 UTC, gibizer commented on controllers/novacell_controller.go
> +		instance.Status.Conditions.Set(condition.FalseCondition(
ditto this Set call will override the result of the previous compute in the list in the same cell

2023-09-15 08:42 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	// because of that there is a limit 20 signs
nit: There is a 20 character limit on the compute name.

2023-09-15 08:42 UTC, gibizer commented on controllers/novacell_controller.go
> +	}
Sorry I wasn't clear before. I would move this also before the compute config generation to keep the NovaCompute logic in a single place

2023-09-15 08:42 UTC, gibizer commented on controllers/novacompute_controller.go
> +		Owns(&routev1.Route{}).
we don't create any routes here

2023-09-15 08:42 UTC, gibizer commented on controllers/novacompute_controller.go
> +		Owns(&corev1.Service{}).
we don't create any service here

2023-09-15 08:42 UTC, gibizer commented on pkg/novacompute/const.go
> +	ServiceName = "nova-compute"
I don't see any usage of these constants

2023-09-15 08:42 UTC, gibizer commented on pkg/novacompute/deployment.go
> +	}
You can use a the check what we use for the conductor, i.e. checking if the process exists `"/usr/bin/pgrep", "-r", "DRST", "nova-conductor",`

2023-09-15 08:42 UTC, gibizer commented on pkg/novacompute/deployment.go
> +						// by oc log so define the log stream container first.
We only need the sidecar container for logging from wsgi services. For directly started processes like this (and conductor, scheduler) we can let the process to log to its standard out and k8s will capture it without issue,

2023-09-15 08:42 UTC, gibizer commented on templates/nova.conf
> +{{ if (index . "compute_driver") }}
I would simplify this by adding this template parameter to the EDPM compute config generation codepath too and hardcode it to libvirt.LibvirtDriver there: https://github.com/openstack-k8s-operators/nova-operator/blob/532bc7f74c7f8893ad9ab53690bed442c843619b/controllers/novacell_controller.go#L573-L584

2023-09-15 08:42 UTC, gibizer commented on templates/nova.conf
> +# TODO(ksambor) in tripleo we disable vnc console
This feels strange. Do you mean vnc is disable for ironic computes or all computes in tripleo?

2023-09-15 08:45 UTC, gibizer commented
I still haven't reviewed the test coverage yet. 
Also during my review I noted the following missing pieces:
* having a struct for compute status
* AllComputeReady aggregate condition handling
* running discover hosts after computes are ready

2023-09-15 11:10 UTC, mrKisaoLamb commented on templates/nova.conf
> +# TODO(ksambor) in tripleo we disable vnc console
we disable only for ironic driver not all computes

2023-09-15 11:15 UTC, gibizer commented on templates/nova.conf
> +# TODO(ksambor) in tripleo we disable vnc console
Ahh but this now disable for all computes as far as I understand.
I agree to disable it for ironic computes

2023-09-18 09:38 UTC, gibizer commented on api/v1beta1/novacompute_webhook.go
> +	if *r.Replicas > 1 {
thanks. It seems that when the webhook deserialize the request into NovaCompueTemplate struct the kubebuilder default, which is 1, applied.

2023-09-25 08:13 UTC, gibizer commented
recheck

2023-09-25 08:14 UTC, gibizer commented
/test nova-operator-build-deploy

2023-09-25 10:13 UTC, gibizer commented on controllers/novacompute_controller.go
> +		"nova_compute_image":     instance.Spec.ContainerImage,
Why do we need this in the nova-compute config?

2023-09-25 10:13 UTC, gibizer commented on controllers/novacompute_controller.go
> +	}
As far as I see currently there is no finalizer added to NovaCompute. Either you add a finalizer at the beginning of Reconcile or remove the reconcileDelete codepath.

2023-09-25 10:13 UTC, gibizer commented on pkg/nova/common.go
> +	ComputeDiscoverReady NovaComputeStatus = iota
Please put this in a separate const() block to reset the iota value back to 0 as this is a separate enum from the cell status.

2023-09-26 16:15 UTC, gibizer commented on controllers/novacell_controller.go
> +	if instance.Status.Hash[novav1.ComputeDiscoverHashKey] != computeTemplatesHash && allComputeDeployed {
See https://github.com/openstack-k8s-operators/lib-common/blob/main/modules/common/test/functional/job_test.go for details about how NewJob and DoJob can be used to run a Job only once if none of the input of the job changes.

2023-09-26 16:15 UTC, gibizer commented on controllers/novacell_controller.go
> +	for computeName, computeTemplate := range instance.Spec.NovaComputeTemplates {
Please be aware that iterating a map in golang is done in an undefined order that can also change between each iteration. So if there is something that depends on the order of the iteration the you have to sort manually. I think at the moment it is not an issue as computes are independent. But if you follow my suggestion below to use the `readyCompute` list to make the Job's hash then you need to ensure that the list is sorted before hashed otherwise the different reconcile runs will generate the same list in different orders that will lead to differnt hashes.

2023-09-27 11:45 UTC, gibizer commented
About the CI failures:
```
[pod/nova-operator-controller-manager-6454b77f47-kmss2/manager] 2023-09-27T11:07:39.660Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "NovaCompute.nova.openstack.org", "error": "no matches for kind \"NovaCompute\" in version \"nova.openstack.org/v1beta1\""}
```
This is because the build in CI does not bump the nova-operator version in the openstack-operator and therefore the new NovaCompute CRD is never installed.

2023-09-27 12:05 UTC, gibizer commented on test/functional/nova_compute_ironic_controller_test.go
> +			spec["cellName"] = "some-cell-name"
if you pass cell1 to GetDefaultNovaComputeSpec then it already sets the cellName field on the spec so you don't need to do it here again.

2023-09-27 12:05 UTC, gibizer commented on test/functional/nova_compute_ironic_controller_test.go
> +		It("and deployment is Ready", func() {
OK this is another case we need to handle when doing the host discovery. If the compute is Ready because it was created with 0 replicas then we can run a discovery but it will not discovery anything. When the replica changes to >0 we need to discover again. But you are hashing the template so I guess ti will work.

2023-09-27 12:05 UTC, gibizer commented on test/functional/novacell_controller_test.go
> +				"ironic-compute": GetDefaultNovaComputeTemplate(),
you have a constant for "ironic-compute" in base_test.go

2023-09-27 12:05 UTC, gibizer commented on test/functional/novacell_controller_test.go
> +			Expect(cell.Status.NovaComputesStatus).To(HaveKey("ironic-compute"))
use the constant from base_test.go for the name

2023-09-27 13:16 UTC, gibizer commented on config/crd/bases/nova.openstack.org_novacomputeironics.yaml
This seems to be a remnant of before the rename as it is called novacomputeironics

2023-09-27 14:58 UTC, gibizer commented on controllers/novacompute_controller.go
> +		"log_file":               "/var/log/nova/nova-compute.log",
I just realized that this means the pod does not log anything to the standard out. In a follow up PR please change this to allow the podified compute service to log to the standard out. You can take nova-scheduler or nova-conductor as an example

2023-09-27 16:12 UTC, gibizer commented on pkg/nova/common.go
> +type NovaComputeStatus int
nit (fix it in a separate PR): this is unused now

2023-09-27 16:15 UTC, gibizer commented on test/functional/novacell_controller_test.go
in a different PR: you can assert here in this test suite that the instance.Status.NovaComputesStatus is filled properly.

2023-09-27 16:29 UTC, gibizer commented
/test nova-operator-build-deploy-tempest

2023-09-28 07:22 UTC, gibizer approved these changes
This works for me locally with the fake driver ( I can deploy multiple computes and boot fake VMs) and does not seem to break any existing functionality. @mrKisaoLamb tested it with ironic. So I think this OK to land now. There is a list of followup in previous comments that we will address separately and iteratively. 

Thanks @mrKisaoLamb for making this happen.

2023-09-28 07:27 UTC, merged