switch to structured logging
openstack-k8s-operators/nova-operator pull request #496
Opened 2023-08-22 01:22 UTC by pinikomarov

2023-08-22 08:59 UTC, gibizer commented
/ok-to-test

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +		l("Waiting for the Deployment to become Ready before exposing the sevice in Keystone")
I think you wanted to say l.Info(...

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +		l.Error(err, "Deployment failed", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/nova_controller.go
> +	l.Info(fmt.Sprintf("Job %s hash added - %s", jobDef.Name, instance.Status.RegisteredCells[cell.Name]))
to make it structured it should look something like:
```golang
l.Info("Job hash added", "job", jobDef.Name, "hash", instance.Status.RegisteredCells[cell.Name])
```

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +		l.Info("Deployment in progress", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +		l.Info("Deployment is ready", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +		l.Info("Deployment is not ready", "instance", instance, "Status", ss.GetStatefulSet().Status)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +	l.Info("Removed finalizer from nova KeystoneEndpoint", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +	l.Info("Reconciling delete", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +		l.Info("Removed finalizer from ourselves", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novaapi_controller.go
> +	l.Info("Reconciled delete successfully", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novacell_controller.go
> +	l.Info("Reconciling", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novacell_controller.go
> +		l.Info("Waiting for the NovaNoVNCProxyService to become Ready before generating the compute config", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novacell_controller.go
> +	l.Info("Successfully reconciled", "instance", instance)
You don't need to pass the instance that is already part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novacell_controller.go
> +		l.Info("", "NovaConductor", string(op), "instance", instance, "NovaConductor.Name", conductor.Name)
The empty log seems strange. I would do the following instead:
```golang
l.Info(fmt.Sprintf("NovaConductor %s.", string(op)))
```
Both the conductor name and the instance is part of the logger.

2023-08-22 09:10 UTC, gibizer commented on controllers/novacell_controller.go
> +		l.Info("", "NovaNoVNCProxy", string(op), "instance", instance, "NovaNoVNCProxy.Name", novncproxy.Name)
```golang
l.Info(fmt.Sprintf("NovaNoVNCProxy %s.", string(op)))
```

2023-08-22 09:10 UTC, gibizer commented on controllers/novacell_controller.go
> +		l.Info("", "NovaMetadata", string(op), "instance", instance, "NovaMetadata.Name", metadata.Name)
```golang
l.Info(fmt.Sprintf("NovaMetadata %s.", string(op)))
```

2023-08-22 09:10 UTC, gibizer commented on controllers/novaconductor_controller.go
> +	l.Info("Reconciling", "instance", instance)
you can drop the instance it is already part of the logger

2023-08-22 09:10 UTC, gibizer commented on controllers/novaconductor_controller.go
> +	l.Info("Successfully reconciled", "instance", instance)
you can drop the instance it is already part of the logger

2023-08-22 09:10 UTC, gibizer commented on controllers/novaconductor_controller.go
> +		l.Info("Failed reading Secret", "instance", instance,
you can drop the instance it is already part of the logger

2023-08-22 12:02 UTC, SeanMooney requested changes

2023-08-22 12:02 UTC, SeanMooney commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
is this really needed.
why cant we use r.Log since that is already created via 
GetLog(ctx, "nova")

2023-08-24 22:30 UTC, pinikomarov commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
I believe we discussed it here : 
It's to do with parallel reconcile use case and making room for differeantianting each reconcile_id if that happens.
https://github.com/openstack-k8s-operators/keystone-operator/pull/220#issuecomment-1483117420

2023-08-24 23:03 UTC, pinikomarov commented on controllers/nova_controller.go
> +	l.Info(fmt.Sprintf("Job %s hash added - %s", jobDef.Name, instance.Status.RegisteredCells[cell.Name]))
ack

2023-08-24 23:05 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +	l.Info("Reconciled delete successfully", "instance", instance)
done

2023-08-24 23:06 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +		l.Info("Removed finalizer from ourselves", "instance", instance)
done

2023-08-24 23:07 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +	l.Info("Reconciling delete", "instance", instance)
done

2023-08-24 23:07 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +	l.Info("Removed finalizer from nova KeystoneEndpoint", "instance", instance)
done

2023-08-24 23:07 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +		l.Info("Deployment is not ready", "instance", instance, "Status", ss.GetStatefulSet().Status)
done

2023-08-24 23:08 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +		l.Info("Deployment is ready", "instance", instance)
done

2023-08-24 23:08 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +		l.Info("Deployment in progress", "instance", instance)
done

2023-08-24 23:09 UTC, pinikomarov commented on controllers/novaapi_controller.go
> +		l("Waiting for the Deployment to become Ready before exposing the sevice in Keystone")
done

2023-08-24 23:19 UTC, pinikomarov commented on controllers/novacell_controller.go
> +		l.Info("", "NovaMetadata", string(op), "instance", instance, "NovaMetadata.Name", metadata.Name)
done

2023-08-24 23:28 UTC, pinikomarov commented on controllers/novacell_controller.go
> +		l.Info("", "NovaConductor", string(op), "instance", instance, "NovaConductor.Name", conductor.Name)
done

2023-08-24 23:29 UTC, pinikomarov commented on controllers/novacell_controller.go
> +	l.Info("Successfully reconciled", "instance", instance)
done

2023-08-24 23:29 UTC, pinikomarov commented on controllers/novacell_controller.go
> +		l.Info("Waiting for the NovaNoVNCProxyService to become Ready before generating the compute config", "instance", instance)
done

2023-08-24 23:29 UTC, pinikomarov commented on controllers/novacell_controller.go
> +	l.Info("Reconciling", "instance", instance)
done

2023-08-24 23:30 UTC, pinikomarov commented on controllers/novaconductor_controller.go
> +		l.Info("Failed reading Secret", "instance", instance,
done

2023-08-24 23:30 UTC, pinikomarov commented on controllers/novaconductor_controller.go
> +	l.Info("Successfully reconciled", "instance", instance)
done

2023-08-24 23:31 UTC, pinikomarov commented on controllers/novaconductor_controller.go
> +	l.Info("Reconciling", "instance", instance)
done

2023-08-25 10:44 UTC, SeanMooney commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
ok but we dont plan to do that.

if were are not going to use that logger then done use l as the log var

2023-08-27 10:56 UTC, pinikomarov commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
Since this is a wide set of patches , ad they should be the same across all operators, I'm for the path of least resistance here , @SeanMooney I believe @gibizer mentioned you brought the parallel usage issue up , so if we're not ever going to use that , then we can use the receiver to hold the logger object, the plus side is less lines of code, and the negative is if we do use parallelism then we have to revisit this set of patches again.
 @gibizer wdyt ?

2023-08-28 12:59 UTC, gibizer commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
> why cant we use r.Log since that is already created via

r.Log is not request local but reconciler global. But the logger we get from the context has request specific information attached. Anything request specific we store in the reconciler will promote a dangerous pattern. Not just because it prevents parallelism (that we don't use today but might want to use in the future) but also because  data in the reconciler struct automatically passed between two subsequent request. 

> if were are not going to use that logger then done use l as the log var

I'm not sure I can follow.  Does your comment about using a longer name as the variable name for the logger?

2023-08-28 14:01 UTC, SeanMooney commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
yes im asking for the variable to be changed

l := GetLog(ctx, "nova")

to

log := GetLog(ctx, "nova")

or 

logger := GetLog(ctx, "nova")

I'm generally not ok with single character variable names unless its a loop variable
and env then it generally better to use a real name.

2023-08-28 15:47 UTC, gibizer commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
In general I agree that the specificity of the name of a variable should be related to the size of its context. In this specific case I would be OK to name this as "l" as convention. But I'm OK to rename it to "log" too.

2023-08-28 23:08 UTC, pinikomarov commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
I think to use it like:

	info, error := GetLog(ctx, "novaapi").Info, GetLog(ctx, "novaapi").Error

	if err != ...

			info("NovaAPI instance not found, probably deleted before reconciled. Nothing to do.")
		}
		error(err, "Failed to read the NovaAPI instance.")



*and make lib-common's func NewHelper drop the log instantiation parameter, since it's being replaced anyway by these patches

wdyt ?

2023-08-29 11:02 UTC, gibizer commented on controllers/nova_controller.go
> +	l := GetLog(ctx, "nova")
I would not go to that direction. Let's name it `log` as a compromise

2023-10-16 23:27 UTC, closed without merging

2023-10-17 22:39 UTC, pinikomarov commented
continued in : 
https://github.com/openstack-k8s-operators/nova-operator/pull/576