Stop using KOLLA_CONFIG_FILE environment variable
openstack-k8s-operators/nova-operator pull request #501
Opened 2023-08-25 04:53 UTC by kajinamit

2023-08-25 07:26 UTC, gibizer commented
The kuttl result feels relevant, cell1 did not become ready

2023-08-25 07:33 UTC, kajinamit commented
> The kuttl result feels relevant, cell1 did not become ready

That failure was a real one caused by wrong pod getting the kolla config file mount. But I fixed that problem so zuul should post a new result, though I don't see any jobs running in rdo zuul job status, which is very strange.

2023-08-25 07:34 UTC, gibizer commented
The novncproxy pod did not come up
```
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       4m10s                  default-scheduler  Successfully assigned nova-kuttl-default/nova-kuttl-cell1-novncproxy-0 to crc-74q6p-master-0
  Normal   AddedInterface  4m8s                   multus             Add eth0 [10.217.0.138/23] from openshift-sdn
  Normal   Pulling         4m7s                   kubelet            Pulling image "quay.io/podified-antelope-centos9/openstack-nova-novncproxy:current-podified"
  Normal   Pulled          4m3s                   kubelet            Successfully pulled image "quay.io/podified-antelope-centos9/openstack-nova-novncproxy:current-podified" in 4.71532787s (4.71534361s including waiting)
  Normal   Created         4m2s                   kubelet            Created container nova-kuttl-cell1-novncproxy-log
  Normal   Started         4m2s                   kubelet            Started container nova-kuttl-cell1-novncproxy-log
  Normal   Pulled          3m44s (x3 over 4m2s)   kubelet            Container image "quay.io/podified-antelope-centos9/openstack-nova-novncproxy:current-podified" already present on machine
  Normal   Created         3m43s (x3 over 4m1s)   kubelet            Created container nova-kuttl-cell1-novncproxy-novncproxy
  Normal   Started         3m43s (x3 over 4m1s)   kubelet            Started container nova-kuttl-cell1-novncproxy-novncproxy
  Warning  BackOff         3m26s (x7 over 4m)     kubelet            Back-off restarting failed container
  Warning  Unhealthy       3m19s (x5 over 3m59s)  kubelet            Startup probe failed: Get "http://10.217.0.138:6080/vnc_lite.html": dial tcp 10.217.0.138:6080: connect: connection refused
```

2023-08-25 07:35 UTC, gibizer commented
> > The kuttl result feels relevant, cell1 did not become ready
> 
> That failure was a real one caused by wrong pod getting the kolla config file mount. But I fixed that problem so zuul should post a new result, though I don't see any jobs running in rdo zuul job status, which is very strange.

Ohh, so I looked at an old result.

2023-08-25 07:35 UTC, gibizer commented
recheck

2023-08-25 07:37 UTC, kajinamit commented
The failure in tempest job looks strange. It failed because tempest got 503 from nova api but looking at the nova pod and deployment are ready. No 503 response is recorded in nova api log. My current impression is that tempest hit nova api before it becomes ready but that means tempest is executed without readiness of control plane...

2023-08-25 07:54 UTC, kajinamit commented
Might be some problem in the cluster (especially its route resource) ? Let me rerun the job.

2023-08-25 07:54 UTC, kajinamit commented
/test nova-operator-build-deploy-tempest

2023-08-25 07:54 UTC, gibizer commented
> Might be some problem in the cluster (especially its route resource) ? Let me rerun the job.

could be it. Lets run it again

2023-08-25 09:08 UTC, gibizer commented
/test nova-operator-build-deploy-tempest

It seems the tempest job does not use make openstack_wait before start make openstack_deploy causing the next failure:
```
secret/osp-secret created
+ oc kustomize /alabama/install_yamls/out/openstack/openstack/cr/
+ oc apply -f -
error: resource mapping not found for name: "openstack-galera" namespace: "openstack" from "STDIN": no matches for kind "OpenStackControlPlane" in version "core.openstack.org/v1beta1"
ensure CRDs are installed first
```

2023-08-25 10:42 UTC, SeanMooney requested changes

2023-08-25 10:42 UTC, SeanMooney commented on pkg/novaconductor/deployment.go
> +							},
please dont create a seperate config map for this

2023-08-25 10:42 UTC, SeanMooney commented on pkg/nova/volumes.go
> +}
this is not the correct way to do this.
we do not want this file to be generated into a different configmap.

2023-08-25 10:42 UTC, SeanMooney commented on templates/libvirt_virtlogd/libvirt_virtlogd.json
> +        "/var/lib/openstack/config/libvirt/libvirt-virtlogd.json:/var/lib/kolla/config_files/config.json:ro",
instead of this
change 
"/var/lib/openstack/config/libvirt:/var/lib/openstack/config:ro
to
"/var/lib/openstack/config/libvirt:/var/lib/kolla/config_files:ro"

then update the source path in the templates https://github.com/openstack-k8s-operators/nova-operator/blob/main/templates/libvirt_virtlogd/libvirt-virtlogd.json#L5

2023-08-25 10:58 UTC, kajinamit commented on pkg/novaconductor/deployment.go
> +							},
No this is not creating a different config map but added additional mount to present the kolla config file to the fixed path.

2023-08-25 10:59 UTC, kajinamit commented on pkg/nova/volumes.go
> +}
See my comment above.

2023-08-25 10:59 UTC, raukadah commented
recheck after zuul restart

2023-08-25 11:03 UTC, kajinamit commented on templates/libvirt_virtlogd/libvirt_virtlogd.json
> +        "/var/lib/openstack/config/libvirt/libvirt-virtlogd.json:/var/lib/kolla/config_files/config.json:ro",
it does not work because there are multiple files created in that libvirt directory and we have to present one of these to the static file name kolla commands look up (`config.json`)

2023-08-25 11:03 UTC, SeanMooney commented on pkg/nova/volumes.go
> +}
fail but i still want to keep this consistent with how i did this in the edpm-anshbile nova role where i update the config location to be /var/lib/kolla/config_files created by the operator that we bind mount in.

https://github.com/openstack-k8s-operators/edpm-ansible/blob/main/roles/edpm_nova/templates/config.json.j2#L5

its not strictly required but i think it would be cleaner.

2023-08-25 11:04 UTC, SeanMooney commented on templates/libvirt_virtlogd/libvirt_virtlogd.json
> +        "/var/lib/openstack/config/libvirt/libvirt-virtlogd.json:/var/lib/kolla/config_files/config.json:ro",
actully thinking about it the libvirt templates should all be deleted so ill push up a pr for that

2023-08-25 11:11 UTC, SeanMooney commented on templates/libvirt_virtlogd/libvirt_virtlogd.json
> +        "/var/lib/openstack/config/libvirt/libvirt-virtlogd.json:/var/lib/kolla/config_files/config.json:ro",
https://github.com/openstack-k8s-operators/nova-operator/pull/503

2023-08-25 11:14 UTC, SeanMooney commented on templates/libvirt_virtlogd/libvirt_virtlogd.json
> +        "/var/lib/openstack/config/libvirt/libvirt-virtlogd.json:/var/lib/kolla/config_files/config.json:ro",
ah but that just because i havent gotten around to renaming the file to config.json yet.

i guess we could do this for now and it can always revisit this later.

2023-08-28 06:44 UTC, kajinamit commented
I've rebased this on the latest main with conflicts resolved.

2023-08-28 11:26 UTC, SeanMooney approved these changes

2023-08-28 12:33 UTC, merged