switch to structured logging
openstack-k8s-operators/nova-operator pull request #576
Opened 2023-10-17 22:38 UTC by pinikomarov

fix logging

l as log controllers

update logging

update logging

2023-10-19 13:08 UTC, gibizer commented
/ok-to-test

2023-10-20 08:45 UTC, mrKisaoLamb requested changes
Unfortunatly tests are failing with error:
`  panic: odd number of arguments passed as key-value pairs for logging [recovered]
  	panic: odd number of arguments passed as key-value pairs for logging
`. Looks like some log texts need to be reformated by fmt.Sprintf

2023-10-22 13:23 UTC, pinikomarov commented
thanks @mrKisaoLamb , I have uploaded a fix in all locations I saw a syntax mishap , 
can you point me to the link where that error was printed ?  (I can't seem to find that in the tests` logs)

2023-10-22 13:34 UTC, pinikomarov commented
/retest

2023-10-23 07:11 UTC, mrKisaoLamb commented
> thanks @mrKisaoLamb , I have uploaded a fix in all locations I saw a syntax mishap , can you point me to the link where that error was printed ? (I can't seem to find that in the tests` logs)

hey @pinikomarov I run locally `GINKGO_ARGS="--output-interceptor-mode=none" make test ` to got full error output. Now I see that syntax is fixed, thanks!

2023-11-23 16:17 UTC, bogdando commented
lgtm

2023-12-04 15:26 UTC, mrkisaolamb commented
recheck

2023-12-05 09:37 UTC, gibizer approved these changes

2023-12-05 09:37 UTC, gibizer commented on controllers/nova_controller.go
> +			handler.EnqueueRequestsFromMapFunc(r.GetSecretMapperFor(&novav1.NovaList{}, context.TODO()))).
yeah this does call does not part of a reconcile loop hence no context. Look OK to pass an empty context and get an empty logger.

2023-12-05 09:39 UTC, gibizer commented on controllers/nova_controller.go
> +			handler.EnqueueRequestsFromMapFunc(r.GetSecretMapperFor(&novav1.NovaList{}, context.TODO()))).
The empty logger still produces a valid log:
```
  2023-12-05T10:38:28.600+0100	INFO	Controllers.ReconcilerBase	Requesting reconcile due to secret change	{"Secret": "8ad70b41-29e4-4824-81b4-f-cell1", "CR": "8ad70b41-29e4-4824-81b4-f-cell1-novncproxy"}
```

2023-12-05 10:04 UTC, merged