Refactor using of gophercloud client
openstack-k8s-operators/nova-operator pull request #610
Opened 2023-11-29 12:04 UTC by mrkisaolamb

Improve testing and code

Depends on: https://github.com/openstack-k8s-operators/lib-common/pull/405

2023-12-05 09:55 UTC, gibizer reviewed
good step forward. Looks good just waiting for the dependency to land

2023-12-05 09:55 UTC, gibizer commented on test/functional/nova_scheduler_test.go
> +			// set up in a way that it always respond with a  list of  services in down state.
supernit: s/of  services/of services/

2023-12-05 13:04 UTC, SeanMooney requested changes

2023-12-05 13:04 UTC, SeanMooney commented on controllers/common.go
> -	gophercloud_openstack "github.com/gophercloud/gophercloud/openstack"
you likely inted to keep this?

2023-12-05 13:04 UTC, SeanMooney commented on controllers/common.go
> +	computeClient, err := openstack.GetNovaOpenStackClient(cfg)
openstack is now undefiend.

2023-12-05 13:06 UTC, SeanMooney commented on controllers/common.go
> +	computeClient, err := openstack.GetNovaOpenStackClient(cfg)
ah "github.com/openstack-k8s-operators/lib-common/modules/openstack"

so this is defiend but the function is not found because the github action does not understand depends on.

2023-12-07 09:47 UTC, gibizer commented
/retest

2023-12-07 09:50 UTC, mrkisaolamb commented
lib-common function need small refactor to work fully with internal and public endpoints. Currently even if keystone is internal we still use public endpoints

2023-12-07 11:05 UTC, gibizer commented on controllers/common.go
> +		Availability: gophercloud.AvailabilityInternal,
Cool, so this will ensure that the client uses the nova internal endpoint.

2023-12-07 14:05 UTC, merged