[zuul]Use the common content provider
openstack-k8s-operators/nova-operator pull request #615
Opened 2023-12-01 17:27 UTC by gibizer

2023-12-01 17:27 UTC, gibizer commented
/hold lets see if it fixes the build or not

2023-12-04 13:41 UTC, SeanMooney requested changes

2023-12-04 13:41 UTC, SeanMooney commented on .zuul.yaml
> -          image_base: nova
we use this one to specifically ensure we build the opesntack operator with the new content form the nova-operator patch under test.

i don't think we can make this change and have the ci work correctly unless they have change that job to rebuild every operator in the required projects automatically ?

2023-12-05 09:26 UTC, gibizer commented
This was a failed attempt to troubleshoot the build failure.

2023-12-05 09:26 UTC, closed without merging