WIP: Add memcached instance
openstack-k8s-operators/nova-operator pull request #667
Opened 2024-02-05 10:22 UTC by mrkisaolamb

2024-02-05 10:33 UTC, gibizer reviewed
good first steps.

2024-02-05 10:33 UTC, gibizer commented on api/v1beta1/nova_types.go
> +	// Global memcached instance name.
nit: "MemcachedInstance is the name of the Memcached CR that all nova service will use.

2024-02-05 10:33 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	MemcachedInstance string `json:"memcachedInstance"`
nit: "MemcachedInstance is the name of the Memcached CR that the services in the cell will use. If defined then this takes precedence over Nova.Spec.MemcachedInstance for this cell."

2024-02-05 10:33 UTC, gibizer commented on controllers/nova_controller.go
> +		return ctrl.Result{}, fmt.Errorf("memcached %s is not ready", memcached.Name)
Can we mirror the Ready condition of the Memcached CR into our MemcachedReadyCondition? That would give more information about the user as they don't have to look up the Memcached Cr separately to look at the reason.

2024-02-20 08:18 UTC, gibizer commented
tempest job fails as nova-operator is crashing:
```
2024-02-19T10:28:55.266Z	ERROR	controller-runtime.source.EventHandler	kind must be registered to the Scheme	{"error": "no kind is registered for the type v1beta1.Memcached in scheme \"go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/runtime/scheme.go:100\""}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/source/kind.go:66
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/loop.go:73
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/loop.go:74
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/source/kind.go:56
2024-02-19T10:29:05.267Z	ERROR	controller-runtime.source.EventHandler	kind must be registered to the Scheme	{"error": "no kind is registered for the type v1beta1.Memcached in scheme \"go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/runtime/scheme.go:100\""}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/source/kind.go:66
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/loop.go:73
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/loop.go:74
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/source/kind.go:56
```

2024-02-20 08:44 UTC, gibizer commented on controllers/common.go
> +	return memcached, err
we could probably move the result calculation and condition setting logic here as well, similarly how we do it with ensure secret

2024-02-20 08:44 UTC, gibizer commented on controllers/nova_controller.go
> +	if err := r.Client.List(context.Background(), novaList, listOpts...); err != nil {
use the ctx from the function  params

2024-02-20 08:44 UTC, gibizer commented on test/functional/nova_controller_test.go
> +			}
we can move this and below to novaNames

2024-02-20 08:44 UTC, gibizer commented on test/functional/nova_controller_test.go
> +			DeferCleanup(infra.DeleteMemcached, infra.CreateMemcached(novaNames.NovaName.Namespace, MemcachedInstance, memcachedSpec))
nit: Could be th.DeleteInstance

2024-02-20 08:44 UTC, gibizer commented on templates/nova.conf
we need some negative tests for memcached not found or not ready cases

2024-02-20 14:25 UTC, mrkisaolamb commented on controllers/common.go
> +	return memcached, err
done

2024-02-20 14:25 UTC, mrkisaolamb commented on controllers/nova_controller.go
> +	if err := r.Client.List(context.Background(), novaList, listOpts...); err != nil {
done

2024-02-20 14:25 UTC, mrkisaolamb commented on test/functional/nova_controller_test.go
> +			}
done

2024-02-20 14:25 UTC, mrkisaolamb commented on templates/nova.conf
done

2024-02-20 14:49 UTC, gibizer commented on controllers/novascheduler_controller.go
> +		"api_db_name":            instance.Spec.APIDatabaseUser, // fixme
this feels like a rebase artifact

2024-02-20 14:49 UTC, gibizer commented on controllers/novascheduler_controller.go
> +		"cell_db_name":           instance.Spec.Cell0DatabaseUser, // fixme
ditto

2024-02-20 15:29 UTC, gibizer commented on controllers/nova_controller.go
> +// ensureTopLevelSecret makes sure that the internal Cell Secret exists and up to
thanks!

2024-02-20 15:29 UTC, gibizer commented on controllers/nova_controller.go
> +	if err := r.Client.List(context.TODO(), novaList, listOpts...); err != nil {
you can use the `ctx` from the function parameter

2024-02-20 15:29 UTC, gibizer commented on controllers/nova_controller.go
> +		).
we need this watch in each sub CR controller. It is not enough to detect the change on the top level as we don't have a piece of data that is changing and sent down to the sub CRs to trigger reconcile there when only the status of the Memcached CR changes. I.e. we only propagate the name of the CR but not the status so we need to watch the status.

2024-02-20 15:29 UTC, gibizer commented on controllers/common.go
We need to add finalizer to the Memcached instance when we start using it to prevent it to be deleted while our services is configured to connect to it.

2024-02-20 15:29 UTC, gibizer commented on test/functional/nova_controller_test.go
> +			}
did you forget to add the change to the commit? :)

2024-02-20 15:29 UTC, gibizer commented on test/functional/nova_controller_test.go
> +			corev1.ConditionFalse,
Could you assert the message please. I guess it will tell us the that the Memcached instance is not found.

2024-02-20 15:29 UTC, gibizer commented on test/functional/novaapi_controller_test.go
> +				Expect(configData).To(ContainSubstring("memcache_servers="))
can we assert some value in the right side of the '='?

2024-02-20 15:29 UTC, gibizer commented on test/functional/novaapi_controller_test.go
> +				Expect(configData).To(ContainSubstring("memcached_servers="))
`memcached_servers` or `memcache_server` ? Otherwise this two asserts are very similar.

2024-02-20 15:29 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
could you add a reconfiguration test. Maybe change the status of the Memchached CR to show a different set of addresses and assert that the generated service config is changed.

2024-02-20 15:29 UTC, gibizer commented on test/functional/suite_test.go
would be nice to have a test case where the top level services get a different Memcached than one of our cells to see that the override behavior works.

2024-02-21 10:13 UTC, mrkisaolamb commented on controllers/nova_controller.go
> +	_, err = getMemcached(ctx, h, instance.Namespace, instance.Spec.MemcachedInstance, &instance.Status.Conditions)
done, issue created https://github.com/openstack-k8s-operators/nova-operator/issues/699

2024-02-21 10:13 UTC, mrkisaolamb commented on controllers/nova_controller.go
> +	if err := r.Client.List(context.TODO(), novaList, listOpts...); err != nil {
done

2024-02-21 10:14 UTC, mrkisaolamb commented on controllers/nova_controller.go
> +		).
done

2024-02-21 10:17 UTC, mrkisaolamb commented on controllers/common.go
done

2024-02-21 10:17 UTC, mrkisaolamb commented on test/functional/novaapi_controller_test.go
> +				Expect(configData).To(ContainSubstring("memcache_servers="))
done

2024-02-21 10:18 UTC, mrkisaolamb commented on test/functional/novaapi_controller_test.go
> +				Expect(configData).To(ContainSubstring("memcached_servers="))
done, both asserts are with value now

2024-02-21 13:31 UTC, gibizer commented on test/functional/nova_reconfiguration_test.go
> +	})
```diff
diff --git a/test/functional/nova_reconfiguration_test.go b/test/functional/nova_reconfiguration_test.go
index 740e70f2..c53e8369 100644
--- a/test/functional/nova_reconfiguration_test.go
+++ b/test/functional/nova_reconfiguration_test.go
@@ -669,11 +669,13 @@ var _ = Describe("Nova reconfiguration", func() {
                }, timeout, interval).Should(Succeed())
 
                // (ksambor) this should failed
-               configDataMap = th.GetSecret(novaNames.SchedulerConfigDataName)
-               Expect(configDataMap).ShouldNot(BeNil())
-               Expect(configDataMap.Data).Should(HaveKey("01-nova.conf"))
-               configData = string(configDataMap.Data["01-nova.conf"])
-               Expect(configData).To(ContainSubstring("memcache_servers=memcached-0.memcached:11211,memcached-1.memcached:11211,memcached-2.memcached:11211"))
-               Expect(configData).To(ContainSubstring("memcached_servers=inet:[memcached-0.memcached]:11211,inet:[memcached-1.memcached]:11211,inet:[memcached-2.memcached]:11211"))
+               Eventually(func(g Gomega) {
+                       configDataMap = th.GetSecret(novaNames.SchedulerConfigDataName)
+                       g.Expect(configDataMap).ShouldNot(BeNil())
+                       g.Expect(configDataMap.Data).Should(HaveKey("01-nova.conf"))
+                       configData = string(configDataMap.Data["01-nova.conf"])
+                       g.Expect(configData).To(ContainSubstring("memcache_servers=new"))
+                       g.Expect(configData).To(ContainSubstring("memcached_servers=inet_new"))
+               }, timeout, interval).Should(Succeed())
        })
 })

```

you need eventually as reconcile is async.

2024-02-21 14:02 UTC, mrkisaolamb commented on test/functional/suite_test.go
done

2024-02-21 14:02 UTC, mrkisaolamb commented on test/functional/nova_reconfiguration_test.go
done

2024-02-22 10:06 UTC, gibizer commented on controllers/novascheduler_controller.go
> +		"api_db_name":            instance.Spec.APIDatabaseUser, // fixme
this is not fixed yet

2024-02-22 10:16 UTC, gibizer requested changes

2024-02-22 10:16 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			memcachedNamespace := types.NamespacedName{
nit: cell1 specific variable name would be better to differentiate it from the global memcached

2024-02-22 10:16 UTC, gibizer commented on controllers/common.go
i only see the rbac for the finalizer but not the actual finalize addition and removal for the Memcached instance

2024-02-22 11:57 UTC, mrkisaolamb commented on controllers/novascheduler_controller.go
> +		"api_db_name":            instance.Spec.APIDatabaseUser, // fixme
should be fixed across all controllers

2024-02-22 11:58 UTC, mrkisaolamb commented on controllers/common.go
thanks, done finalizers and deleding are added inside all controllers

2024-02-22 14:31 UTC, gibizer requested changes

2024-02-22 14:31 UTC, gibizer commented on controllers/novaapi_controller.go
> +
this needs tho happen before the self finalizer is removed at L777

2024-02-22 14:31 UTC, gibizer commented on controllers/novaconductor_controller.go
> +
this only works if we have a self finalizer added, otherwise there wont be reconcile called during deletion, and the Conductor CR would be deleted by k8s directly

2024-02-22 14:31 UTC, gibizer commented on controllers/novaconductor_controller.go
> +
we need to remove the self finalizer here

2024-02-22 14:31 UTC, gibizer commented on controllers/novametadata_controller.go
> +	}
needs self finalizer handling

2024-02-22 14:31 UTC, gibizer commented on controllers/novanovncproxy_controller.go
> +	}
needs self finalizer handling

2024-02-22 14:31 UTC, gibizer commented on controllers/novascheduler_controller.go
> +
needs self finalize handling

2024-02-22 14:31 UTC, gibizer commented on test/functional/base_test.go
could you please add some tests that ensures the finalizers are added and removed?

2024-02-26 11:29 UTC, gibizer commented on controllers/common.go
> +// ensureMemcached - gets the Memcached instance cell specific used for nova services cache backend
nit:getMemcached

2024-02-26 11:29 UTC, gibizer commented on controllers/common.go
> +// ensureMemcached - gets the Memcached instance cell specific used for nova services cache backend
nit:it not just gets it but ensures it is ready

2024-02-26 11:30 UTC, gibizer approved these changes
I only have nits and those can be done in a folloup. So this is good to go when CI is green

2024-02-26 12:05 UTC, gibizer commented
when deployed I see this
```
  - lastTransitionTime: "2024-02-26T11:52:38Z"
    message: ' Memcached error occurred memcacheds.memcached.openstack.org "memcached"
      is forbidden: User "system:serviceaccount:openstack-operators:nova-operator-controller-manager"
      cannot update resource "memcacheds" in API group "memcached.openstack.org" in
      the namespace "openstack"'
    reason: Error
    severity: Warning
    status: "False"
    type: NovaConductorReady
```

2024-02-26 12:06 UTC, gibizer commented
CI shows it too https://review.rdoproject.org/zuul/build/9b961c9010554ae0a1f172e44ef9e14c/log/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/novaconductors.nova.openstack.org/nova-cell0-conductor.yaml#63-67

2024-02-26 12:17 UTC, mrkisaolamb commented
> CI shows it too https://review.rdoproject.org/zuul/build/9b961c9010554ae0a1f172e44ef9e14c/log/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/novaconductors.nova.openstack.org/nova-cell0-conductor.yaml#63-67

thanks yes it miss update in role for memcached apigroup

2024-02-26 12:41 UTC, gibizer requested changes

2024-02-26 12:41 UTC, gibizer commented on api/v1beta1/nova_types.go
> +	// +kubebuilder:default=memcached
hm, either required, or defaulted, otherwise it is confusing

2024-02-26 15:24 UTC, mrkisaolamb commented on api/v1beta1/nova_types.go
> +	// +kubebuilder:default=memcached
done

2024-02-26 17:21 UTC, gibizer requested changes

2024-02-26 17:21 UTC, gibizer commented on controllers/novaapi_controller.go
> +	if !k8s_errors.IsNotFound(err) && memcached != nil {
this will exit in error if the memcached is not found. But we should ignore the not found as there is no finalizer to remove form memcached in that case

2024-02-26 17:21 UTC, gibizer commented on controllers/novaconductor_controller.go
> +	if !k8s_errors.IsNotFound(err) && memcached != nil {
here and in other controllers we need to ignore the not found error

2024-02-27 08:17 UTC, mrkisaolamb commented on controllers/novaconductor_controller.go
> +	if !k8s_errors.IsNotFound(err) && memcached != nil {
done

2024-02-27 10:01 UTC, mrkisaolamb commented
/retest

2024-02-27 12:23 UTC, merged