Add NovaAPITemplate to be used in NovaSpec
openstack-k8s-operators/nova-operator pull request #67
Opened 2022-09-21 10:01 UTC by gibizer

We need to split what input is coming from outside (i.e. from the user) and what input is generated by a controller for our service CRs.

This patch create a NovaAPITemplate for the external input and use that in the NovaSpec instead of the NovaAPISpec.

2022-09-21 12:06 UTC, SeanMooney requested changes
im much happier with this as our interface

2022-09-21 12:06 UTC, SeanMooney commented on config/samples/nova_v1beta1_nova-multi-cell.yaml
> +    containerImage: quay.io/tripleowallabycentos9/openstack-nova-api:zed-tripleo
for reasons i dont understand they are publishing each release to a different organisation on quay

quay.io/tripleowallabycentos9 has the wallaby images
https://quay.io/repository/tripleomastercentos9 has the master images.

so the tag might stay current-tripleo to get the latest image but the org would chagne to tripleozedcentos9

can you change this quay.io/tripleowallabycentos9/openstack-nova-api:zed-tripleo to
quay.io/tripleomastercentos9/openstack-nova-api:current-tripleo

2022-09-21 16:27 UTC, kk7ds commented
Yeah agreed this is looking cool to me. I think the ContainerImage thing is probably something we should table for the moment and just keep it like you have here. I don't understand how we're going to know if we need to do major or minor upgrade type tasks purely based on updates to an otherwise opaque URL, but presumably that's a larger discussion.

2022-09-22 08:22 UTC, gibizer commented on config/samples/nova_v1beta1_nova-multi-cell.yaml
> +    containerImage: quay.io/tripleowallabycentos9/openstack-nova-api:zed-tripleo
Based on the discussion https://coreos.slack.com/archives/CQXJFGMK6/p1663752237261069 I think we will keep an non templated `containerImage` both in each Spec and in each Template too. Version tags cannot be used as offline installation needs to refer images by hash.

2022-09-22 11:47 UTC, gibizer commented on api/v1beta1/novaapi_types.go
> +
We can make KeystoneAuthURL in the Spec required now.

2022-09-22 12:56 UTC, gibizer commented on api/v1beta1/novaapi_types.go
> +
Done

2022-09-22 21:31 UTC, SeanMooney commented on config/samples/nova_v1beta1_nova-multi-cell.yaml
> +    containerImage: quay.io/tripleowallabycentos9/openstack-nova-api:zed-tripleo
ack i was more pointing out thtat the url you used in the sample was not vaild.

the way tags are used upstream for ooo and downstream fo our product differ so upstream the branch is contoled by the org in the url and the tag is just a a sha or current-tripleo for the head of the branch

so there is no zed-tripleo in tripleowallabycentos9

2022-09-22 21:41 UTC, SeanMooney commented
the only nit i have this this is the curren url in the sample is not a real image can you just put it back to the defuatl or use the master url instead.

2022-09-23 09:36 UTC, gibizer commented on config/samples/nova_v1beta1_nova-multi-cell.yaml
> +    containerImage: quay.io/tripleowallabycentos9/openstack-nova-api:zed-tripleo
Ah. OK. Fixed it.

2022-09-27 10:33 UTC, SeanMooney approved these changes

2022-09-27 10:41 UTC, merged