Split spec template for services in the cell
openstack-k8s-operators/nova-operator pull request #68
Opened 2022-09-22 12:57 UTC by gibizer

Depends on https://github.com/openstack-k8s-operators/nova-operator/pull/67

2022-09-22 13:46 UTC, SeanMooney commented on api/v1beta1/novaapi_types.go
>  	APIDatabaseUser string `json:"apiDatabaseUser"`
we shoudl review perhaps taking the db and message bus parmaters as a rendered connection string in the secret in the future but for now thsi makes sesne to require.

2022-09-22 14:27 UTC, SeanMooney requested changes
over all im continuing to like the direction is is moving in one minor thing in line but over all looking good

2022-09-22 14:27 UTC, SeanMooney commented on api/v1beta1/novacell_types.go
> +	// +kubebuilder:validation:Required
we could make this optional since the db and message bus will be on the cell.
depending on our default for the replicas of the conductor you woudl get 3 or 1 by defualt unless you passed null or set it to 0 in the template.

2022-09-22 14:27 UTC, SeanMooney commented on config/samples/nova_v1beta1_nova-multi-cell.yaml
> +      logging.conf: >
i think i said thie before but we shoudl use | not >

https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#yaml-basics

Values can span multiple lines using | or >. Spanning multiple lines using a “Literal Block Scalar” | will include the newlines and any trailing spaces. Using a “Folded Block Scalar” > will fold newlines to spaces; it’s used to make what would otherwise be a very long line easier to read and edit. In either case the indentation will be ignored. Examples are:

`include_newlines: |
            exactly as you see
            will appear these three
            lines of poetry

fold_newlines: >
            this is really a
            single line of text
            despite appearances
`

this is why the orveride was being collapsed into a singel line when i was testing with customServiceConfig
can you fix this in a new revision

2022-09-22 14:27 UTC, SeanMooney commented on config/samples/nova_v1beta1_novacell1-upcall.yaml
> +  # Here we have to have both api and cell passwords selectors
ack ill update my config gen patch to enable/disble the upcall based on if we have both dbs or not.

right now im hardcoding it to off.

2022-09-22 18:36 UTC, gibizer commented on api/v1beta1/novaapi_types.go
>  	APIDatabaseUser string `json:"apiDatabaseUser"`
Yeah, this is pending the Secret discussion. If the Nova CRD controller will generate individual Secret objects to lower level CRs then we can put the rendered connection string in that Secret instead of putting the pieces there.

2022-09-22 18:37 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	// NoVNCProxyServiceTemplate - defines the novvncproxy serive dedicated for
yepp.

2022-09-22 18:44 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	// +kubebuilder:validation:Optional
Yes, It is optional as it either runs on the top or per cell. I think the Nova CR can default to either create it on the top or per cell. I would default it to run on the top level just simply because that is the simpler setup.

2022-09-22 19:16 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	// +kubebuilder:validation:Required
Done.

2022-09-22 19:42 UTC, gibizer commented on config/samples/nova_v1beta1_nova.yaml
> +      metadataServiceTemplate: null
The cell template is broken now. There is no way to specify the CellDB and CellMq.

2022-09-22 20:04 UTC, gibizer commented on config/samples/nova_v1beta1_nova.yaml
> +      metadataServiceTemplate: null
Fixed it with adding new fields to the NovaCellTemplate. Note that CellDatabaseInstance and CellMessageBusInstance already follow the convention to pass depnedencies by CR name instead of label selector. See also https://github.com/openstack-k8s-operators/nova-operator/pull/71

2022-09-23 15:20 UTC, kk7ds reviewed
Just one comment about consistency but not critical. Otherwise I like how this is going :)

2022-09-23 15:20 UTC, kk7ds commented on api/v1beta1/novacell_types.go
> +	CellDatabaseInstance string `json:"cellDatabaseInstance"`
I wonder if it makes sense to name these exactly like the top-level and other operators do? Like I wonder if the same argument will be applied here for consistency? So:

```
NovaSpec:
  DatabaseInstance foodb
  MessageBusInstance foomq
  CellTemplates:
    - DatabaseInstance bardb
      MessageBusInstance barmq
    - ...
```

Unless you think it would be confusing to have multiple of the same parameters in the hierarchy, I think maybe we should consider making them the same.

2022-09-23 16:04 UTC, gibizer commented on api/v1beta1/novacell_types.go
> +	CellDatabaseInstance string `json:"cellDatabaseInstance"`
Do you mean only differentiate between the API and the Cell DB on the Cell level. 

A cell with upcall support:
```
NovaSpec:
  DatabaseInstance foodb
  MessageBusInstance foomq
  CellTemplates:
      DatabaseInstance bardb
      MessageBusInstance barmq
      APIDatabaseInstance foodb
      APIMessageBusInstance foomq
```

I think in this case it is confusing that the DatabaseInstance on the top means the same as APIDatabaseInstance in the cell.

2022-09-23 16:33 UTC, SeanMooney commented on api/v1beta1/novacell_types.go
> +	CellDatabaseInstance string `json:"cellDatabaseInstance"`
i guess you also meant drop the nova prefix form  NovaCellTemplate to just be CellTemplate

which I think makes sense.

if I'm not reading between the line too much 

NovaSpec:
  DatabaseInstance foodb
  MessageBusInstance foomq
  CellTemplates:
    - DatabaseInstance bardb
      MessageBusInstance barmq
    - ...

dan might have been suggesting a list of dictoaries of 
NovaSpec:
  DatabaseInstance foodb
  MessageBusInstance foomq
  CellTemplates:
    - DatabaseInstance apidb
      MessageBusInstance apimq
    - DatabaseInstance celldb
      MessageBusInstance cellmq

if That is what you meant by the ...
i ferfer what we have now as its clear which is which

2022-09-23 17:08 UTC, kk7ds commented on api/v1beta1/novacell_types.go
> +	CellDatabaseInstance string `json:"cellDatabaseInstance"`
All I meant was use "DatabaseInstance" anywhere we need one and not call it a "CellDatabaseInstance". If it's inside a CR where it's the only one, then there's no reason to prefix it with "Cell" I think.

2022-09-23 17:34 UTC, kk7ds commented on api/v1beta1/novacell_types.go
> +	CellDatabaseInstance string `json:"cellDatabaseInstance"`
> Do you mean only differentiate between the API and the Cell DB on the Cell level.
> 
> A cell with upcall support:
> 
> ```
> NovaSpec:
>   DatabaseInstance foodb
>   MessageBusInstance foomq
>   CellTemplates:
>       DatabaseInstance bardb
>       MessageBusInstance barmq
>       APIDatabaseInstance foodb
>       APIMessageBusInstance foomq
> ```
> 
> I think in this case it is confusing that the DatabaseInstance on the top means the same as APIDatabaseInstance in the cell.

Sorry I just saw this. You're right, it may be somewhat confusing in the spec, although I'm not super concerned about it, because it's kindof a pointer to something outside the cell. It's not "My cell's database instance" it's "that other thing over there".

Anyway, it seems like from the template point of view (i.e. our API) that keeping the names the same would be the better approach for consistency. But, I understand the concern, and it's just a matter of naming preference. I thought it might be a good thing to make us "look" more like the typical operator, but it's not critical :)

2022-09-27 10:37 UTC, SeanMooney approved these changes
lets pick up this converstation when dan and i are back form pto next week but i generally agree with the idea of useing

DatabaseInstance anywhere its appropriate

this particular case is less clean and im unsure which is better.

user CellDatabaseInstance for clarity or DatabaseInstance for consitency

since we can simple change this next week with liitle impact im going to appvoed this now since i didnt get to it friday evening and we can chat about this more on monday

2022-09-27 11:05 UTC, SeanMooney approved these changes
simple rebase for merge conflict this still looks fine for now so re approving

2022-09-27 11:05 UTC, merged