Wait for DB writes to propagate (causality checks)
openstack-k8s-operators/nova-operator pull request #776
Opened 2024-05-29 12:46 UTC by gibizer

Because we deploy the database in multi-master mode we can have cases
where reading data from the DB fails after the data was written to
another galera master node.

We saw this happening during Flavor creation where nova first creates
the flavor in the DB then the notification sending code tries to read
back the flavor projects from the DB and the query fails as the flavor
is not found.

In this patch we change the default value on the DB engine to wait for
previous write to sync before read.

This will have a performance impact.

We use `mysql_wsrep_sync_wait` from oslo.db [1] setting it to 1 as per
the documented values of this parameter in the DBMS [2][3].

[1]: https://opendev.org/openstack/oslo.db/commit/009d23df45969036c70e4cf59eb4019aaace9a55
[2]: https://mariadb.com/docs/server/ref/mdb/system-variables/wsrep_sync_wait/
[3]: https://galeracluster.com/library/documentation/mysql-wsrep-options.html

Fixes: https://issues.redhat.com/browse/OSPRH-7198

2024-05-29 13:32 UTC, zzzeek approved these changes

2024-05-29 13:52 UTC, zzzeek requested changes
let's try starting with the setting at 1, which is the equivalent of wsrep_causal_reads = true.   we should not need a wsrep check on INSERTs and unlikely for UPDATE/DELETE

2024-05-29 13:53 UTC, SeanMooney approved these changes

2024-05-29 13:53 UTC, SeanMooney commented on templates/nova.conf
> +mysql_wsrep_sync_wait = 7
ack based on the doc 7 is

Performs causality checks on read, update, and insert operations, such as SELECT, UPDATE, DELETE, INSERT, and REPLACE statements

that looks correct to me.

2024-05-29 13:53 UTC, SeanMooney commented on test/functional/nova_controller_test.go
> +			Expect(configData).To(ContainSubstring("mysql_wsrep_sync_wait = 7"))
ack this is really the only thing we can test
+1

2024-05-29 13:53 UTC, zzzeek commented
https://forums.percona.com/t/stability-of-8-0-x/13005/5

> wsrep_sync_wait = 7 is quite intense and will certainly cause slowness in your application. Have you tested with this disabled or maybe =1?

2024-05-29 13:56 UTC, zzzeek commented on templates/nova.conf
> +mysql_wsrep_sync_wait = 7
are we doing INSERTs that rely on existing data being read?    Whats the INSERT scenario here?   note that this flag started in earlier galera as wsrep_causal_reads=1, which is equivalent to "1" here.   I dont think we should dampen performance ahead of what's needed

2024-05-29 13:57 UTC, gibizer commented
/hold

2024-05-29 14:01 UTC, zzzeek commented
> > let's try starting with the setting at 1, which is the equivalent of wsrep_causal_reads = true. we should not need a wsrep check on INSERTs and unlikely for UPDATE/DELETE
> 
> for db sync perhaps but insert are likely important for online migrations

an INSERT is a row with new data in it.   doing a causality check for an INSERT seems unnecessary for anything I can think of.     if the goal is that an INSERT with conflicting data should fail, that will happen anyway when the write-sets try to reconcile.    note that setting this to 1 will give you causality check for all SELECTs.

2024-05-29 14:06 UTC, SeanMooney commented
if we belive 1 is sufficent to ensure when we do the min comptue service version check  as part of adoption the I'm ok with starting with 1

Nova in general is not expecting Galara to be eventually consistent
it may work but it will impact scheduling,  provided transactions are still atomic
i.e. we will never use outdated data to make decisions because reads force synchronisation
then it might be fine.

why I expected 7 was to ensure when we claim a PCI device or similar in the db we want to ensure those are visible to the scheduler.

2024-05-29 14:08 UTC, SeanMooney commented
based on your last respocne 1 is probably sufficient as the read to get the aviabel PCI devices will enforce the causality check.

our expectation however is that if we create a writer transaction and do an insert form 2 different process in parallel only one of them will complete. and the other will raise a db conflict

2024-05-29 14:11 UTC, zzzeek commented
So I'd discourage the term "Eventually consistent" since galera is not really an "eventually" model, where "eventually" is usually taken to mean "can be any amount of time, seconds, minutes".   it's not strictly incorrect however I think is misleading; this is a very brief latent period in all cases.

we should start with SELECT being the tool we are using for visibility; an INSERT just pushes a new row.   an UPDATE or DELETE is also questionable as to whether it needs to see an up to date cluster.    if we do "UPDATE ..WHERE col='foobar'", even without multi-master, other processes can set/unset "foobar" in the database after this UPDATE takes place.

2024-05-29 14:13 UTC, zzzeek commented
> our expectation however is that if we create a writer transaction and do an insert form 2 different process in parallel only one of them will complete. and the other will raise a db conflict

this will happen anyway without wsrep_causal_reads / sync_wait.   the write-sets do this conflict in any case

cc @dciabrin

2024-05-29 14:14 UTC, zzzeek commented
that is, if the conflict is being raised because there's a UNIQUE/INDEX/FOREIGN KEY/CHECK doing a check, those are enforced. galera transactions are consistent across masters

2024-05-29 14:16 UTC, SeanMooney commented
ok then we can regert this to 1

all write are done in a transaction so if "galera transactions are consistent across masters"
then all our insert will be consistent.

2024-05-29 15:40 UTC, gibizer commented
Set it to 1

2024-05-29 15:41 UTC, zzzeek approved these changes

2024-05-29 16:11 UTC, SeanMooney approved these changes

2024-05-30 04:02 UTC, karelyatin commented
recheck live-migration test fail 6.0 sec

2024-05-30 07:31 UTC, merged