Modify job to use metadata per cell
openstack-k8s-operators/nova-operator pull request #812
Opened 2024-07-05 09:49 UTC by mrkisaolamb

2024-07-05 10:18 UTC, SeanMooney approved these changes
thansk this looks good to me
approving pending ci conformation

2024-07-08 08:23 UTC, mrkisaolamb commented
recheck

2024-07-08 11:26 UTC, bogdando reviewed
lgtm

2024-07-08 11:28 UTC, gibizer requested changes

2024-07-08 11:28 UTC, gibizer commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                value: true
wouldn't we need to also disable metadata at the top level too?

2024-07-08 11:30 UTC, bogdando commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                value: true
hm, I thought cell0 is the top level :)

2024-07-08 11:32 UTC, bogdando commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                value: true
so it should be ``/spec/nova/template/metadataServiceTemplate/enabled`` instead of cell0 path (that is a special celll, should not run computes, nor metadata service for them, right?)

2024-07-08 11:35 UTC, gibizer commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                value: true
`/spec/nova/template/metadataServiceTemplate/enabled` is the top level yes. 
you are right cell0 should not have computes and therefore no point to run metadata in it. The operator also rejects it https://github.com/openstack-k8s-operators/nova-operator/blob/3ace225b81d57da287cd052eceafd000819fc5db/api/v1beta1/novametadata_webhook.go#L136-L142

2024-07-08 11:47 UTC, mrkisaolamb commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                value: true
no, cell0 is different than top lvl so that was reason why I go with explicit disabling on cell0 but forgot disable for top lvl, also I correct operation type

2024-07-08 12:14 UTC, gibizer reviewed
looks better, thanks

2024-07-09 07:32 UTC, gibizer commented
```
Monday 08 July 2024  09:49:17 -0400 (0:00:00.035)       0:00:00.220 *********** 
fatal: [localhost]: FAILED! => changed=false 
  details: |-
    error: add operation does not apply: doc is missing path: "/spec/nova/template/cellTemplates/cell0/metadataServiceTemplate/enabled": missing value
```
https://review.rdoproject.org/zuul/build/b436ea857a464d6ba897149baae1b40e/log/controller/ci-framework-data/logs/ci_script_011_run_82_kustomize_and_update.log#37

2024-07-09 07:35 UTC, gibizer requested changes

2024-07-09 07:35 UTC, gibizer commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                path: /spec/neutron/template/metadataServiceTemplate/enabled
this should be /spec/nova

2024-07-09 13:18 UTC, SeanMooney commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                      enabled: true
looking at the ci output we have the following annotation on the top level service

metadata:
                    annotations:
                      metallb.universe.tf/address-pool: internalapi
                      metallb.universe.tf/allow-shared-ip: internalapi
                      metallb.universe.tf/loadBalancerIPs: 172.17.0.80

i wonder if that is the problem here? 

https://logserver.rdoproject.org/12/812/f5ac7314ae6ac3c88fe797be09f01c9811665b2d/github-check/nova-operator-tempest-multinode/4d74ffe/controller/ci-framework-data/logs/ci_script_011_run_82_kustomize_and_update.log

i assume we need to copy them to the cell1 defintions

2024-07-09 13:24 UTC, SeanMooney commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                      enabled: true
ah no its simpler then that

 lastTransitionTime: "2024-07-09T11:23:35Z"
    message: DB creation failed for cell0(accountName is empty),cell1(accountName
      is empty)
    reason: Error
    severity: Error
    status: "False"
    type: NovaAllCellDBReady
  - lastTransitionTime: "2024-07-09T11:23:35Z"
    message: NovaCell creation waits for DB creation for cell0,cell1
    reason: Init
    severity: Warning
    status: "False"
    type: NovaAllCellReady
  - lastTransitionTime: "2024-07-09T11:23:36Z"
    message: All message busses created successfully
    reason: Ready
    status: "True"
    type: NovaAllCellsMQReady

https://logserver.rdoproject.org/12/812/f5ac7314ae6ac3c88fe797be09f01c9811665b2d/github-check/nova-operator-tempest-multinode/4d74ffe/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/nova.nova.openstack.org/nova.yaml

2024-07-09 13:31 UTC, SeanMooney commented
the ceph job failure look to be DNS related

https://logserver.rdoproject.org/12/812/f5ac7314ae6ac3c88fe797be09f01c9811665b2d/github-check/nova-operator-tempest-multinode-ceph/050407b/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/tempest-tests-zd8w6/logs/tempest-tests-tests-runner.log

but maybe its something else but that is not related to this patch

2024-07-12 13:26 UTC, SeanMooney commented on ci/nova-operator-tempest-multinode/ci_fw_vars.yaml
> +
this is incorrect

the job you are modifying  is for non ceph so you should not be using the hci customisation here.

2024-07-18 08:26 UTC, mrkisaolamb commented
/retest

2024-07-25 13:16 UTC, gibizer commented
While the logic looks good CI disagrees:
https://softwarefactory-project.io/zuul/t/rdoproject.org/build/510d0ac60578445f8d6e503173db671e/log/controller/ci-framework-data/logs/ci_script_011_run_85_patch_neutron.log
```
  stderr: 'Error from server (NotFound): openstackdataplaneservices.dataplane.openstack.org "neutron-metadata" not found'
```

I think at post_ctlplane_deploy we don't yet have the default services defined.

2024-07-25 13:31 UTC, gibizer commented
> While the logic looks good CI disagrees: https://softwarefactory-project.io/zuul/t/rdoproject.org/build/510d0ac60578445f8d6e503173db671e/log/controller/ci-framework-data/logs/ci_script_011_run_85_patch_neutron.log
> 
> ```
>   stderr: 'Error from server (NotFound): openstackdataplaneservices.dataplane.openstack.org "neutron-metadata" not found'
> ```
> 
> I think at post_ctlplane_deploy we don't yet have the default services defined.

As far as I see the default services created only when the first NodeSet is created https://github.com/openstack-k8s-operators/openstack-operator/blob/76b853500f9f8867044db03e4fa1408539a48643/controllers/dataplane/openstackdataplanenodeset_controller.go#L221  So we would need a hook that is after NodeSet creation and before the Deployment creation OR we need a way to pass a kustomization to the NodeSet creation codepath in ci-framework.

2024-07-25 13:35 UTC, gibizer commented
> > While the logic looks good CI disagrees: https://softwarefactory-project.io/zuul/t/rdoproject.org/build/510d0ac60578445f8d6e503173db671e/log/controller/ci-framework-data/logs/ci_script_011_run_85_patch_neutron.log
> > ```
> >   stderr: 'Error from server (NotFound): openstackdataplaneservices.dataplane.openstack.org "neutron-metadata" not found'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think at post_ctlplane_deploy we don't yet have the default services defined.
> 
> As far as I see the default services created only when the first NodeSet is created https://github.com/openstack-k8s-operators/openstack-operator/blob/76b853500f9f8867044db03e4fa1408539a48643/controllers/dataplane/openstackdataplanenodeset_controller.go#L221 So we would need a hook that is after NodeSet creation and before the Deployment creation OR we need a way to pass a kustomization to the NodeSet creation codepath in ci-framework.

I don't know if this could help or not https://github.com/openstack-k8s-operators/ci-framework/blob/90eda0fcb2b4ac1e25a462ed362a6c3a0c234f26/roles/ci_gen_kustomize_values/README.md

2024-08-12 07:14 UTC, mrkisaolamb commented
recheck

2024-08-12 11:37 UTC, SeanMooney commented
the test operator had a seg fault

https://logserver.rdoproject.org/12/812/21504e851ce8dd82a8ff4ddadc5a8c81f3e72c0b/github-check/nova-operator-tempest-multinode/7cf20fa/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/test-operator-controller-manager-8568bff7d4-jvclp/logs/manager-previous.log


2024-08-12T09:06:10Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "tempest", "controllerGroup": "test.openstack.org", "controllerKind": "Tempest", "Tempest": {"name":"tempest-tests","namespace":"openstack"}, "namespace": "openstack", "name": "tempest-tests", "reconcileID": "96394cd0-4fb0-4010-90b4-5c625b665302"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x17212ba]

goroutine 354 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:116 +0x1fa
panic({0x1920ba0, 0x2a6ea00})
	/usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/openstack-k8s-operators/lib-common/modules/common/pod.GetPodListWithLabel({0x1df34a0, 0xc0017ea420}, 0xc0005186e0, {0xc0015e4bb6, 0x9}, 0xc002ae95c0)
	/opt/app-root/src/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/common@v0.4.1-0.20240730142703-7fd3da600c9d/pod/pod.go:42 +0x7a
github.com/openstack-k8s-operators/lib-common/modules/common/networkattachment.VerifyNetworkStatusFromAnnotation({0x1df34a0, 0xc0017ea420}, 0xc0005186e0, {0xc0017ac710, 0x1, 0x0?}, 0x0?, 0x1)
	/opt/app-root/src/go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/common@v0.4.1-0.20240730142703-7fd3da600c9d/networkattachment/networkattachment.go:112 +0xc5
github.com/openstack-k8s-operators/test-operator/controllers.(*TempestReconciler).Reconcile(0xc0002d4a40, {0x1df34a0, 0xc0017ea420}, {{{0xc001903db6?, 0x5?}, {0xc001903dc0?, 0xc001853d08?}}})
	/remote-source/controllers/tempest_controller.go:299 +0x17e5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1df5800?, {0x1df34a0?, 0xc0017ea420?}, {{{0xc001903db6?, 0xb?}, {0xc001903dc0?, 0x0?}}})
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:119 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00012ef00, {0x1df33f8, 0xc0001476d0}, {0x19c5480?, 0xc00199e140?})
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:316 +0x3ca
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00012ef00, {0x1df33f8, 0xc0001476d0})
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:266 +0x1c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:223 +0x587

thats why the tests didnt run and the jobs timed out.

2024-08-19 13:57 UTC, mrkisaolamb commented
recheck

2024-08-19 13:58 UTC, mrkisaolamb commented
error looks like not related to this patch, error occure in multinode-ceph job . So this looks like some instabilities:

> BadRequestException: 400: Client Error for url: https://neutron-public-openstack.apps-crc.testing/v2.0/subnets, Invalid input for operation: Requested subnet with cidr: 192.168.122.0/24 for network: 2c3933ac-2197-4c53-beba-0a0cc2669a04 overlaps with another subnet.
    command terminated with exit code 1

2024-08-20 10:58 UTC, SeanMooney approved these changes
ci is now green and this seam to be working as intended.

2024-08-20 10:58 UTC, SeanMooney commented on ci/nova-operator-tempest-multinode/control_plane_hook.yaml
> +                            type: LoadBalancer
cell1:
          cellDatabaseAccount: nova-cell1
          cellDatabaseInstance: openstack-cell1
          cellMessageBusInstance: rabbitmq-cell1
          conductorServiceTemplate:
            customServiceConfig: ""
            replicas: 1
            resources: {}
          dbPurge:
            archiveAge: 30
            purgeAge: 90
            schedule: 0 0 * * *
          hasAPIAccess: true
          memcachedInstance: ""
          metadataServiceTemplate:
            customServiceConfig: ""
            enabled: true
            override:
              service:
                metadata:
                  annotations:
                    metallb.universe.tf/address-pool: internalapi
                    metallb.universe.tf/allow-shared-ip: internalapi
                    metallb.universe.tf/loadBalancerIPs: 172.17.0.80
                spec:
                  type: LoadBalancer
            replicas: 1
            resources: {}
            tls: {}
          noVNCProxyServiceTemplate:
            customServiceConfig: ""
            enabled: true
            override: {}
            replicas: 1
            resources: {}
            tls:
              service: {}
              vencrypt: {}
      computeContainerImageURL: quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified
      conductorContainerImageURL: quay.io/podified-antelope-centos9/openstack-nova-conductor:current-podified
      keystoneInstance: keystone
      memcachedInstance: memcached
      metadataContainerImageURL: quay.io/podified-antelope-centos9/openstack-nova-api:current-podified
      metadataServiceTemplate:
        customServiceConfig: ""
        enabled: false
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
        replicas: 1
        resources: {}
        tls: {}

https://logserver.rdoproject.org/12/812/da7bf6d58ac73b0c15b2e74be5ab64cc73842077/github-check/nova-operator-tempest-multinode/7c42e8f/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/openstackcontrolplanes.core.openstack.org/controlplane.yaml

this looks correct to me

if we also check the created nova metadata crs we see only 1 for cell 1

https://logserver.rdoproject.org/12/812/da7bf6d58ac73b0c15b2e74be5ab64cc73842077/github-check/nova-operator-tempest-multinode/7c42e8f/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/novametadata.nova.openstack.org/

and if we check the secrets we also only have the cell1 secret

https://logserver.rdoproject.org/12/812/da7bf6d58ac73b0c15b2e74be5ab64cc73842077/github-check/nova-operator-tempest-multinode/7c42e8f/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/secrets/nova/

so this all looks good to me.

2024-08-20 11:01 UTC, merged