DNM: test with heal_instance_info_cache_interval=0
openstack-k8s-operators/nova-operator pull request #888
Opened 2024-10-30 17:05 UTC by gibizer

2024-10-30 17:23 UTC, gibizer commented
/hold

2024-11-04 09:48 UTC, gibizer commented
recheck
Seems to be working OK.

2024-11-08 14:20 UTC, gibizer commented
recheck so far so good
no heal period is visible now in the nova-compute logs.

2024-11-20 15:24 UTC, gibizer commented
recheck unrelated
```
2024-11-18 14:07:12.745706 | controller |   msg: 'Failed to download metadata for repo ''delorean-component-barbican'': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried'
```

2024-11-21 07:50 UTC, gibizer commented
recheck content provider

2024-11-21 08:06 UTC, gibizer commented
lets try a rebase as it seems to be a compile error due to a recent change on main/openstack-operator.

2025-01-15 16:26 UTC, karelyatin commented
/lgtm

2025-01-16 13:13 UTC, mrkisaolamb approved these changes
lgtm

2025-01-16 13:16 UTC, gibizer commented
/unhold
We have +1 both form network and compute perspective so I will let this merge.

2025-01-16 13:16 UTC, bogdando commented
/lgtm

2025-01-16 13:35 UTC, SeanMooney requested changes
i apparently my request to not do this downstream only in the installer was not widely known

so just for psoperity when the jira that motivated this was filed i asked that we not diverge between the upstream behaviour of nova and the behavior of the installer.


ill propose a patch to nova to make this change there and we can see what upstream thinks of that.

2025-01-16 13:36 UTC, gibizer commented
/hold

2025-01-17 10:40 UTC, bogdando commented
based on inputs provided by @SeanMooney we can unfroze this one after https://review.opendev.org/c/openstack/nova/+/939453 is merged upstream

2025-01-29 17:06 UTC, bogdando commented
So, https://review.opendev.org/c/openstack/nova/+/939453 was merged, we can restore the merging path for this one

2025-01-29 17:07 UTC, bogdando commented
/retest-required

2025-01-31 13:08 UTC, gibizer commented
I suggest to backport https://review.opendev.org/c/openstack/nova/+/939453 to nova 18.0 instead.

2025-01-31 13:08 UTC, closed without merging