Delete next cell irrespective of last deletion
openstack-k8s-operators/nova-operator pull request #901
Opened 2024-11-27 06:34 UTC by auniyal61

Right now when multiple cells gets deleted if any one the cell deletion fails, the control exits with error msg.
This change stores the errors in a list and let next cells deleted.

Closes #OSPRH-10550

2024-11-27 06:36 UTC, auniyal61 commented
The jira report says, we need to do this for cellCreation as well, but I think its already taken care of at here https://github.com/openstack-k8s-operators/nova-operator/blob/main/controllers/nova_controller.go#L328-L356

2024-11-27 10:20 UTC, mrkisaolamb requested changes
Please add some func tests for cell deletion to assert if deletion is working and returning errors for all cells. Also it will be nice to assert what are conditions of nova instance

2024-12-20 10:19 UTC, gibizer reviewed
Deletion logic looks good with a small request about ordering. I have couple of comments on the testing side.

2024-12-20 10:19 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +			}, timeout, interval).Should(Succeed())
I'm not sure how this proves that the cell2 delete failed. It checks for the cell2 delete job to exists
.

2024-12-20 10:19 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +				delete(nova.Spec.CellTemplates, "cell3")
Maybe the way to make it testable is to sort the cells be cell name when iterated in the controller. We do that for cell creation anyhow in https://github.com/openstack-k8s-operators/nova-operator/pull/903 to avoid the unstable ordering to cause unstable condition messages.

2024-12-20 10:19 UTC, gibizer commented on controllers/nova_controller.go
>  	for _, cr := range novaCellList.Items {
I would sort this list by cell name for two reasons:
* https://github.com/openstack-k8s-operators/nova-operator/pull/903 does it for cell creation already to make the error messages stable even if the order of the list of cells in the api is not stable.
* this makes testing possible as we can rely on the ordering to prove that even if cell2 failed to delete cell3 deletion is tried.

2024-12-20 12:30 UTC, gibizer commented
Running the test locally shows that cell2 is also successfully deleted so the current test does not recreate the necessary scenario to prove that failure in one cell does not prevent the deletion of the other.

2025-01-22 13:56 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +
I have added a bit of check here:
```golang
                       nova := GetNova(novaNames.NovaName)
                       Expect(nova.Status.RegisteredCells).To(HaveKey(cell3.CellCRName.Name), "cell3 is not in the RegisteredCells", nova.Status.RegisteredCells)
```

This shows that the starting point of the test is probably incomplete as cell3 is not in RegisteredCells. So I suggest to investigate why cell3 is not there yet.

2025-01-22 13:56 UTC, gibizer commented on test/functional/nova_multicell_test.go
> +
Maybe this is a source of the instability we saw during our call when first we saw that the controller loggedd it deleted cell3 then later we was not able to reproduce that.

2025-01-23 04:55 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +
`[FAILED] cell3 is not in the RegisteredCells%!(EXTRA map[string]string=map[])`

got same for cell0 and cell1 too.

2025-01-23 05:56 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +			}, timeout, interval).Should(Succeed())
removed

2025-01-23 05:57 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +
in updated change cell0, cell1, cell2 are listed.

2025-01-23 07:07 UTC, auniyal61 commented on controllers/nova_controller.go
>  	for _, cr := range novaCellList.Items {
novaCellList is already sorted. so deleteErrs will be sorted automatically.

2025-01-23 07:09 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +			Expect(k8sClient.Delete(ctx, mariadb.GetMariaDBDatabase(cell1.MariaDBDatabaseName))).To(Succeed())
this is not reproducing cell-deletion error

2025-01-23 07:19 UTC, auniyal61 commented on controllers/nova_controller.go
> +		return ctrl.Result{}, fmt.Errorf("errors: %v", deleteErrs)
updated, thanks

2025-01-23 15:41 UTC, gibizer commented
@auniyal61 so you pinged me on slack about the DeferCleanup issue. 
> so I am deleting a cell, but cell-resource (like secret ) is defined in setup (Before each or another funciton).
now once tests is finished deferecleanup runs and look for secret, but as we already deleted cell, its not present in DB, so defercleanup complains,
how to resolve this

The DeferCleanup doc says:
https://onsi.github.io/ginkgo/#cleaning-up-our-cleanup-code-defercleanup
> DeferCleanup can be passed a function that takes no arguments and returns no value. You can also pass a function that returns values. DeferCleanup ignores all these return value except for the last. If the last return value is a non-nil error - a common go pattern - DeferCleanup will fail the spec.

So I guess the situation is that 
1. we create cell3 during the BeforeEach() section and put a DeferCleanup() call to the all the pieces we created
2. then delete the cell during the normal It() section
3. then the test runner executes the deferred cleanups where the client.Delete call returns a non nil error as the last return value  because the resource is not found and that causes the test cleanup to fail as defined by the doc.

This means we have multiple options:
* a) we wrap the client.Delete call and ignore the NotFound error. So cleanup still tries to delete the resources but if they do not exists then the cleanup still succeeds.
* b) we don't create the cell3 in the shared CreateNovaWith3CellsAndEnsureReady() helper. But create it just for our test case (in our BeforeEach or in the It ) and we don't put DeferCleanup for the pieces of cell3 as we expect that the our test will delete them anyhow.

I would do option b) as it is more explicit about why we do thing differently.

(I need to get back to your other comments above a bit later)

2025-01-27 09:54 UTC, auniyal61 commented
> So I guess the situation is that
> 
> 1. we create cell3 during the BeforeEach() section and put a DeferCleanup() call to the all the pieces we created
> 2. then delete the cell during the normal It() section
> 3. then the test runner executes the deferred cleanups where the client.Delete call returns a non nil error as the last return value  because the resource is not found and that causes the test cleanup to fail as defined by the doc.
>
Yes
 
> This means we have multiple options:
> 
> * a) we wrap the client.Delete call and ignore the NotFound error. So cleanup still tries to delete the resources but if they do not exists then the cleanup still succeeds.

> * b) we don't create the cell3 in the shared CreateNovaWith3CellsAndEnsureReady() helper. But create it just for our test case (in our BeforeEach or in the It ) and we don't put DeferCleanup for the pieces of cell3 as we expect that the our test will delete them anyhow.
> 
> I would do option b) as it is more explicit about why we do thing differently.

we have to create new-cell in CreateNovaWith3CellsAndEnsureReady, because that's where `CR-spec` is defined and saved, we can't pass and update spec later in our `Describe("Nova multi cell deletion")` 

the oher way would be to redefine all cells again, which is just a duplicate code of CreateNovaWith3CellsAndEnsureReady.

2025-01-28 09:44 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +			NovaCellNotExists(cell3.CellCRName)
yet to read delete-err msg

2025-01-28 09:45 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +			Expect(k8sClient.Delete(ctx, mariadb.GetMariaDBDatabase(cell1.MariaDBDatabaseName))).To(Succeed())
went with updating secret to empty string.

2025-01-28 09:45 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +			// Expect(k8sClient.Delete(ctx, mariadb.GetMariaDBAccount(cell3.MariaDBDatabaseName))).To(Succeed())
thanks Gibi, updated.

2025-01-30 14:53 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +			NovaCellNotExists(cell3.CellCRName)
Verifying cell2 exists is enough here.
this will update controlplane status after CR update

2025-01-30 14:56 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +				delete(nova.Spec.CellTemplates, "cell3")
yes novaCellList is already sorted and cell2 always comes before cell3 in reconciler.

2025-02-04 10:43 UTC, auniyal61 commented
/retest

2025-02-17 03:46 UTC, auniyal61 commented
/retest

2025-02-25 05:12 UTC, auniyal61 commented
/retest

2025-03-06 10:20 UTC, mrkisaolamb commented on controllers/nova_controller.go
>  	for _, cr := range novaCellList.Items {
I think what @gibi meant is that novaCellList can be retrieved from the database in any order. So, if we want to sort it by name, we need to do something like this:
`// SortNovaCellListByName sorts the NovaCellList by name
func SortNovaCellListByName(cellList *novav1.NovaCellList) {
    sort.SliceStable(cellList.Items, func(i, j int) bool {
        return cellList.Items[i].Name < cellList.Items[j].Name
    })
}`

Similar to what we did with orderedCellNames, where we ensured cell0 was placed first.

2025-03-06 14:04 UTC, auniyal61 commented on controllers/nova_controller.go
>  	for _, cr := range novaCellList.Items {
added sortNovaCellListByName

2025-03-11 01:33 UTC, auniyal61 commented on test/functional/nova_multicell_test.go
> +				delete(nova.Spec.CellTemplates, "cell3")
sorted

2025-03-13 09:30 UTC, gibizer approved these changes
I have couple of follow up requests but the current code and test looks good to me so lets land this and do the refactors in a separate PR

2025-03-13 09:38 UTC, mrkisaolamb commented on controllers/nova_controller.go
> +	sortNovaCellListByName := func(cellList *novav1.NovaCellList) {
it will be nice to move it to common and write some test

2025-03-13 09:38 UTC, mrkisaolamb commented on controllers/nova_controller.go
> +		delErrs := errors.Join(deleteErrs...)
It will be good to land this changes before https://github.com/openstack-k8s-operators/nova-operator/pull/917 then we will don't need to change logic in this pr but directly in 917

2025-03-13 09:38 UTC, mrkisaolamb approved these changes

2025-03-13 09:47 UTC, merged

2025-03-19 02:06 UTC, auniyal61 commented on controllers/nova_controller.go
> +		delErrs := errors.Join(deleteErrs...)
done

2025-03-19 02:07 UTC, auniyal61 commented on controllers/nova_controller.go
> +	sortNovaCellListByName(novaCellList)
follow-up patch https://github.com/openstack-k8s-operators/nova-operator/pull/940

2025-06-10 01:54 UTC, auniyal61 commented on controllers/nova_controller.go
> +	sortNovaCellListByName := func(cellList *novav1.NovaCellList) {
done #940