Sort cell-names in nova_controller
openstack-k8s-operators/nova-operator pull request #903
Opened 2024-11-28 12:31 UTC by ratailor

This change sorts the cell-names and also make sure that the cell0 is the first element in the orderedCellNames slice.

Closes: #OSPRH-9980

2024-11-28 13:51 UTC, SeanMooney requested changes

2024-12-04 12:59 UTC, ratailor commented
> How does the code on main leads to unstable condition messages? Could you please add that description to the PR's message?

Done

2024-12-20 10:27 UTC, gibizer commented on controllers/nova_controller.go
> +	// unnecessary reconcile loop runs, as the map iteration order is undefined.
This is not for avoiding reconcile loops. It is for avoiding that different reconcile loops sees a different cell order while the cell creation is in the same state but generate a different condition message due to the different order.

2024-12-20 10:28 UTC, gibizer commented
I still would like to get a commit message / PR description that describes why we are doing this instead of what the patch does.

2025-01-07 08:38 UTC, mrkisaolamb commented
IMO it will be good to have some functional tests

2025-06-04 14:16 UTC, bogdando reviewed
any updates?

2026-05-28 09:25 UTC, closed without merging

2026-05-28 09:27 UTC, mrkisaolamb commented
original ticket has been closed, and this PR is now outdated